/**
 * # Bounty hunting: the admin panel
 *
 * Owner: P8 admin. Owns this file and the tests in
 * voidcrew/modules/unit_tests/voidcrew_bounty_admin.dm. Do not edit this file outside P8.
 *
 * What it owns: the "Bounty Panel" admin verb, with tgui input lists and no .tsx (spec section 11):
 * spawn any archetype, kit or tier at your feet; spawn a decoy beside a criminal; post a bounty now;
 * list, close, relist, jump to and fetch bounties; force capture states; list the prisoner pool, admit
 * a record into a chosen prison, drop a record or add a test one; run the board forward. It works
 * through the other packages' procs only (bounty_types.dm and the spec's API table), never through
 * vars[] or call().
 *
 * Everything goes through /datum/bounty_admin_panel. The menu procs (menu_*) ask the questions; the
 * action procs (admin_*) take plain arguments, check the admin again, act and log, so a unit test can
 * call either with no admin client (voidcrew_bounty_admin.dm overrides authorized(), log_action(), tell()
 * and the ask_* prompts). An action that is refused returns null or FALSE and leaves the reason in
 * `error`.
 *
 * The shared vars are declared in bounty_types.dm and nowhere else; a var only P8 uses goes here
 * with an `admin_` prefix.
 */

/// Most board ticks one fast-forward runs
#define BOUNTY_ADMIN_MAX_TICKS 60
/// Most minutes one clock skip takes off the postings
#define BOUNTY_ADMIN_MAX_MINUTES 120
/// How long a forced stun lasts
#define BOUNTY_ADMIN_STUN_TIME (30 SECONDS)
/// Most questions one opening of the panel asks before it closes itself: a guard, never reached by hand
#define BOUNTY_ADMIN_MAX_STEPS 200
/// What an admin-spawned decoy wears: the concourse loiterers' clothes
#define BOUNTY_ADMIN_DECOY_OUTFIT /datum/outfit/job/assistant
/// Who the pool's test records say brought them in
#define BOUNTY_ADMIN_TEST_CAPTOR "Admin test"

// The downed line is P2's number. If P2 renames it, the panel falls back to the spec's 25%.
#ifdef BOUNTY_DOWNED_FRACTION
#define BOUNTY_ADMIN_DOWNED_FRACTION BOUNTY_DOWNED_FRACTION
#else
#define BOUNTY_ADMIN_DOWNED_FRACTION 0.25
#endif

// The main menu, in the order it shows
#define BOUNTY_ADMIN_MENU_SPAWN "Spawn a criminal at my feet"
#define BOUNTY_ADMIN_MENU_DECOY "Spawn a decoy next to a criminal"
#define BOUNTY_ADMIN_MENU_POST "Post a bounty now"
#define BOUNTY_ADMIN_MENU_POSTINGS "Live postings"
#define BOUNTY_ADMIN_MENU_FORCE "Force a capture state"
#define BOUNTY_ADMIN_MENU_POOL "Prisoner pool"
#define BOUNTY_ADMIN_MENU_BOARD "Fast-forward the board"

ADMIN_VERB(bounty_panel, R_ADMIN, "Bounty Panel", "Spawn, post, list and force bounty criminals, manage the prisoner pool and run the bounty board forward.", ADMIN_CATEGORY_SHUTTLE)
	var/datum/bounty_admin_panel/panel = new(user.mob)
	BLACKBOX_LOG_ADMIN_VERB("Bounty Panel")
	panel.run_menu(user.mob)
	qdel(panel)

/**
 * One opening of the Bounty Panel by one admin. Holds nothing between actions but the admin and the
 * last refusal; it is deleted when the admin closes the menu.
 */
/datum/bounty_admin_panel
	/// The admin who opened it
	var/mob/admin
	/// Why the last action was refused, or null
	var/error

/datum/bounty_admin_panel/New(mob/user)
	. = ..()
	admin = user

/datum/bounty_admin_panel/Destroy()
	admin = null
	return ..()

// ===== CHECKS, LOGS AND PROMPTS =====
// A unit test overrides these to act without an admin client.

/// Whether `user` may use it now: the admin who opened it, still holding R_ADMIN. Checked again after every prompt.
/datum/bounty_admin_panel/proc/authorized(mob/user)
	return !QDELETED(src) && !isnull(user) && user == admin && check_rights_for(user.client, R_ADMIN)

/// Logs a done action, as the prison admin tools do
/datum/bounty_admin_panel/proc/log_action(mob/user, operation)
	log_admin("[key_name(user)] used the Bounty Panel to [operation].")
	message_admins("[key_name_admin(user)] used the Bounty Panel to [operation].")

/// Tells the admin something in chat
/datum/bounty_admin_panel/proc/tell(mob/user, message)
	to_chat(user, message)

/// A choice from `options` (the keys of an assoc list, or plain entries), or null if cancelled
/datum/bounty_admin_panel/proc/ask_list(mob/user, message, title, list/options)
	if(!length(options))
		return null
	return tgui_input_list(user, message, title || "Bounty Panel", options)

/// A whole number from `min_value` to `max_value`, or null if cancelled
/datum/bounty_admin_panel/proc/ask_number(mob/user, message, title, default, max_value, min_value)
	return tgui_input_number(user, message, title || "Bounty Panel", default, max_value, min_value)

/// Keeps `text` as the reason in `error` and tells the admin. Returns null, for `return refuse(...)`.
/datum/bounty_admin_panel/proc/refuse(mob/user, text)
	error = text
	tell(user, span_warning(text))
	return null

// ===== THE MENU =====

/// Asks what to do, does it and asks again, until the admin cancels
/datum/bounty_admin_panel/proc/run_menu(mob/user)
	var/static/list/menu = list(
		BOUNTY_ADMIN_MENU_SPAWN,
		BOUNTY_ADMIN_MENU_DECOY,
		BOUNTY_ADMIN_MENU_POST,
		BOUNTY_ADMIN_MENU_POSTINGS,
		BOUNTY_ADMIN_MENU_FORCE,
		BOUNTY_ADMIN_MENU_POOL,
		BOUNTY_ADMIN_MENU_BOARD,
	)
	for(var/asked in 1 to BOUNTY_ADMIN_MAX_STEPS)
		if(!authorized(user))
			return
		var/choice = ask_list(user, summary_text(), "Bounty Panel", menu)
		if(!choice || !authorized(user))
			return
		error = null
		switch(choice)
			if(BOUNTY_ADMIN_MENU_SPAWN)
				menu_spawn(user)
			if(BOUNTY_ADMIN_MENU_DECOY)
				menu_decoy(user)
			if(BOUNTY_ADMIN_MENU_POST)
				menu_post(user)
			if(BOUNTY_ADMIN_MENU_POSTINGS)
				menu_postings(user)
			if(BOUNTY_ADMIN_MENU_FORCE)
				menu_force(user)
			if(BOUNTY_ADMIN_MENU_POOL)
				menu_pool(user)
			if(BOUNTY_ADMIN_MENU_BOARD)
				menu_board(user)

/// The menu's heading: how much is going on
/datum/bounty_admin_panel/proc/summary_text()
	var/open = 0
	for(var/datum/criminal_bounty/posting in GLOB.criminal_bounties)
		if(!QDELETED(posting) && posting.status == BOUNTY_POSTING_OPEN)
			open++
	var/about = length(live_criminals())
	return "[open] open bount[open == 1 ? "y" : "ies"], [about] criminal\s about, [length(GLOB.bounty_prisoner_pool)] record\s in the prisoner pool."

/datum/bounty_admin_panel/proc/menu_spawn(mob/user)
	var/list/archetypes = archetype_choices()
	var/archetype_choice = ask_list(user, "Which archetype?", "Spawn a criminal", archetypes)
	if(!archetype_choice || !authorized(user))
		return
	var/archetype = archetypes[archetype_choice]
	var/tier = ask_tier(user, "Spawn a criminal")
	if(!tier)
		return
	var/variant
	if(archetype == BOUNTY_ARCHETYPE_BOSS)
		var/list/kits = list("Random" = null) + kit_choices()
		var/kit_choice = ask_list(user, "Which kit?", "Spawn a criminal", kits)
		if(!kit_choice || !authorized(user))
			return
		variant = kits[kit_choice]
	else if(archetype == BOUNTY_ARCHETYPE_NORMAL)
		var/list/styles = list("Let the record pick" = null) + style_choices()
		var/style_choice = ask_list(user, "Which fighting style?", "Spawn a criminal", styles)
		if(!style_choice || !authorized(user))
			return
		variant = styles[style_choice]
	var/list/activities = list("None" = null) + activity_choices()
	var/activity_choice = ask_list(user, "Doing what?", "Spawn a criminal", activities)
	if(!activity_choice || !authorized(user))
		return
	admin_spawn_criminal(user, tier, archetype, variant, activities[activity_choice], get_turf(user))

/datum/bounty_admin_panel/proc/menu_decoy(mob/user)
	var/mob/living/basic/bounty_criminal/wanted = pick_criminal(user, "Spawn a decoy next to whom?")
	if(!wanted)
		return
	var/static/list/shares = list("One of their features" = 1, "Two of their features" = 2)
	var/share_choice = ask_list(user, "The decoy shares how much of their look?", "Spawn a decoy", shares)
	if(!share_choice || !authorized(user))
		return
	admin_spawn_decoy(user, wanted, shares[share_choice])

/datum/bounty_admin_panel/proc/menu_post(mob/user)
	var/tier = ask_tier(user, "Post a bounty")
	if(!tier)
		return
	var/list/kinds = placement_choices()
	var/kind_choice = ask_list(user, "Where?", "Post a bounty", kinds)
	if(!kind_choice || !authorized(user))
		return
	var/kind = kinds[kind_choice]
	var/list/sites = list("Let the board pick" = null) + site_choices(kind)
	var/site_choice = ask_list(user, "Which site? Only loaded ones are listed.", "Post a bounty", sites)
	if(!site_choice || !authorized(user))
		return
	var/list/audiences = list("Public" = null) + ship_choices()
	var/audience_choice = ask_list(user, "Public, or a private offer to one ship?", "Post a bounty", audiences)
	if(!audience_choice || !authorized(user))
		return
	var/datum/weakref/site_ref = sites[site_choice]
	var/obj/structure/overmap/site = site_ref?.resolve()
	if(site_ref && QDELETED(site))
		refuse(user, "That site is gone.")
		return
	var/datum/weakref/ship_ref = audiences[audience_choice]
	var/obj/structure/overmap/ship/private_to = ship_ref?.resolve()
	if(ship_ref && QDELETED(private_to))
		refuse(user, "That ship is gone.")
		return
	admin_post_bounty(user, tier, kind, site, private_to)

/datum/bounty_admin_panel/proc/menu_postings(mob/user)
	var/list/choices = list()
	var/list/lines = list()
	for(var/datum/criminal_bounty/posting in GLOB.criminal_bounties)
		if(QDELETED(posting))
			continue
		var/list/row = posting_row(posting)
		lines += posting_line(row)
		choices[unique_label(choices, "[row["tier"]] [row["name"]] at [row["place"]] ([row["status"]])")] = WEAKREF(posting)
	if(!length(choices))
		tell(user, span_notice("No bounties are posted."))
		return
	tell(user, boxed_message("<b>Bounty postings</b><br>[jointext(lines, "<br>")]"))
	var/posting_choice = ask_list(user, "Which bounty?", "Live postings", choices)
	if(!posting_choice || !authorized(user))
		return
	var/datum/weakref/posting_ref = choices[posting_choice]
	var/static/list/actions = list("Close it", "Relist it", "Jump to the criminal", "Bring the criminal here")
	var/action = ask_list(user, "Do what with it?", "Live postings", actions)
	if(!action || !authorized(user))
		return
	var/datum/criminal_bounty/posting = posting_ref?.resolve()
	if(QDELETED(posting))
		refuse(user, "That bounty is gone.")
		return
	switch(action)
		if("Close it")
			admin_close_posting(user, posting)
		if("Relist it")
			admin_relist_posting(user, posting)
		if("Jump to the criminal")
			admin_jump(user, posting.criminal())
		if("Bring the criminal here")
			admin_bring(user, posting.criminal())

/datum/bounty_admin_panel/proc/menu_force(mob/user)
	var/mob/living/basic/bounty_criminal/criminal = pick_criminal(user, "Force a capture state on whom?")
	if(!criminal)
		return
	var/static/list/states = list(
		"Downed" = BOUNTY_STATE_DOWNED,
		"Stunned" = BOUNTY_STATE_STUNNED,
		"Restrained (cuffs on)" = BOUNTY_STATE_RESTRAINED,
		"Dead" = BOUNTY_STATE_DEAD,
		"Free (healed, uncuffed, worst state cleared)" = BOUNTY_STATE_FREE,
	)
	var/state_choice = ask_list(user, "Which state?", "Force a capture state", states)
	if(!state_choice || !authorized(user))
		return
	admin_force_state(user, criminal, states[state_choice])

/datum/bounty_admin_panel/proc/menu_pool(mob/user)
	var/static/list/actions = list("List the records", "Admit a record into a prison now", "Drop a record", "Add a test record")
	var/action = ask_list(user, "The pool holds [length(GLOB.bounty_prisoner_pool)] record\s.", "Prisoner pool", actions)
	if(!action || !authorized(user))
		return
	switch(action)
		if("List the records")
			var/list/lines = list()
			for(var/list/row as anything in pool_rows())
				lines += "<b>[row["name"]]</b>: [row["tier"]] [row["archetype"]], [row["status"]], for [row["prison"]], [row["age"]]"
			if(!length(lines))
				tell(user, span_notice("The prisoner pool is empty."))
				return
			tell(user, boxed_message("<b>Prisoner pool</b><br>[jointext(lines, "<br>")]"))
		if("Admit a record into a prison now")
			var/datum/bounty_record/record = pick_record(user, "Admit which record?")
			if(!record)
				return
			var/datum/outpost_prison/prison = pick_prison(user, "Into which prison?")
			if(!prison)
				return
			admin_pool_admit(user, record, prison)
		if("Drop a record")
			var/datum/bounty_record/record = pick_record(user, "Drop which record?")
			if(!record)
				return
			admin_pool_drop(user, record)
		if("Add a test record")
			var/list/archetypes = archetype_choices()
			var/archetype_choice = ask_list(user, "Which archetype?", "Add a test record", archetypes)
			if(!archetype_choice || !authorized(user))
				return
			var/tier = ask_tier(user, "Add a test record")
			if(!tier)
				return
			var/list/prisons = list("Any prison" = null) + prison_choices()
			var/prison_choice = ask_list(user, "Reserved for which prison?", "Add a test record", prisons)
			if(!prison_choice || !authorized(user))
				return
			var/datum/weakref/prison_ref = prisons[prison_choice]
			var/datum/outpost_prison/prison = prison_ref?.resolve()
			if(prison_ref && QDELETED(prison))
				refuse(user, "That prison is gone.")
				return
			admin_pool_add(user, tier, archetypes[archetype_choice], prison)

/datum/bounty_admin_panel/proc/menu_board(mob/user)
	var/static/list/actions = list("Run the board's tick several times", "Skip the post gap: post a public bounty now", "Take minutes off every open bounty's clock")
	var/action = ask_list(user, "The board ticks every 10 seconds of the round.", "Fast-forward the board", actions)
	if(!action || !authorized(user))
		return
	switch(action)
		if("Run the board's tick several times")
			var/count = ask_number(user, "How many ticks?", "Fast-forward the board", 1, BOUNTY_ADMIN_MAX_TICKS, 1)
			if(isnull(count) || !authorized(user))
				return
			admin_board_ticks(user, count)
		if("Skip the post gap: post a public bounty now")
			admin_skip_post_gap(user)
		if("Take minutes off every open bounty's clock")
			var/minutes = ask_number(user, "How many minutes?", "Fast-forward the board", 5, BOUNTY_ADMIN_MAX_MINUTES, 1)
			if(isnull(minutes) || !authorized(user))
				return
			admin_skip_clocks(user, minutes)

// ===== PICKERS =====

/// The tier the admin picks, or null
/datum/bounty_admin_panel/proc/ask_tier(mob/user, title)
	var/list/tiers = tier_choices()
	var/tier_choice = ask_list(user, "Which tier?", title, tiers)
	if(!tier_choice || !authorized(user))
		return null
	return tiers[tier_choice]

/// The live criminal the admin picks (never a decoy), or null
/datum/bounty_admin_panel/proc/pick_criminal(mob/user, message)
	var/list/choices = list()
	for(var/mob/living/basic/bounty_criminal/criminal as anything in live_criminals())
		choices[unique_label(choices, criminal_label(criminal))] = WEAKREF(criminal)
	if(!length(choices))
		return refuse(user, "No bounty criminals are about. Spawn one first.")
	var/choice = ask_list(user, message, "Bounty Panel", choices)
	if(!choice || !authorized(user))
		return null
	var/datum/weakref/criminal_ref = choices[choice]
	var/mob/living/basic/bounty_criminal/criminal = criminal_ref?.resolve()
	if(QDELETED(criminal))
		return refuse(user, "That criminal is gone.")
	return criminal

/// The pool record the admin picks, or null
/datum/bounty_admin_panel/proc/pick_record(mob/user, message)
	var/list/choices = list()
	for(var/datum/bounty_record/record in GLOB.bounty_prisoner_pool)
		choices[unique_label(choices, "[record.name] ([record_kind(record)])")] = WEAKREF(record)
	if(!length(choices))
		return refuse(user, "The prisoner pool is empty.")
	var/choice = ask_list(user, message, "Prisoner pool", choices)
	if(!choice || !authorized(user))
		return null
	var/datum/weakref/record_ref = choices[choice]
	var/datum/bounty_record/record = record_ref?.resolve()
	if(QDELETED(record))
		return refuse(user, "That record is gone.")
	return record

/// The running prison the admin picks, or null
/datum/bounty_admin_panel/proc/pick_prison(mob/user, message)
	var/list/choices = prison_choices()
	if(!length(choices))
		return refuse(user, "No outpost runs a prison.")
	var/choice = ask_list(user, message, "Prisoner pool", choices)
	if(!choice || !authorized(user))
		return null
	var/datum/weakref/prison_ref = choices[choice]
	var/datum/outpost_prison/prison = prison_ref?.resolve()
	if(QDELETED(prison))
		return refuse(user, "That prison is gone.")
	return prison

/// Every live bounty criminal in the world, decoys only if asked for
/datum/bounty_admin_panel/proc/live_criminals(include_decoys = FALSE)
	var/list/found = list()
	for(var/mob/living/basic/bounty_criminal/criminal in GLOB.mob_living_list)
		if(QDELETED(criminal))
			continue
		if(!include_decoys && istype(criminal, /mob/living/basic/bounty_criminal/decoy))
			continue
		found += criminal
	return found

/// `label`, or `label (2)` and on if the list already has it: a tgui list needs unique entries
/datum/bounty_admin_panel/proc/unique_label(list/choices, label)
	if(!(label in choices))
		return label
	var/number = 2
	while("[label] ([number])" in choices)
		number++
	return "[label] ([number])"

/// The values of an assoc list of choices
/datum/bounty_admin_panel/proc/choice_values(list/choices)
	var/list/values = list()
	for(var/label in choices)
		values += choices[label]
	return values

/datum/bounty_admin_panel/proc/tier_choices()
	return list("Petty" = BOUNTY_TIER_PETTY, "Wanted" = BOUNTY_TIER_WANTED, "Most Wanted" = BOUNTY_TIER_MOST_WANTED)

/datum/bounty_admin_panel/proc/archetype_choices()
	return list("Meek" = BOUNTY_ARCHETYPE_MEEK, "Normal" = BOUNTY_ARCHETYPE_NORMAL, "Mini-boss" = BOUNTY_ARCHETYPE_BOSS)

/datum/bounty_admin_panel/proc/kit_choices()
	return list(
		"Juggernaut" = BOUNTY_KIT_JUGGERNAUT,
		"Pyromaniac" = BOUNTY_KIT_PYROMANIAC,
		"Demolitionist" = BOUNTY_KIT_DEMOLITIONIST,
		"Ghost" = BOUNTY_KIT_GHOST,
		"Heavy" = BOUNTY_KIT_HEAVY,
	)

/// A normal criminal's styles; the meek always carry the holdout, so the menu doesn't offer it
/datum/bounty_admin_panel/proc/style_choices()
	return list(
		"Brawler" = BOUNTY_STYLE_BRAWLER,
		"Knife" = BOUNTY_STYLE_KNIFE,
		"Pistol" = BOUNTY_STYLE_PISTOL,
		"Shotgun" = BOUNTY_STYLE_SHOTGUN,
		"Club" = BOUNTY_STYLE_CLUB,
		"Bottle thrower" = BOUNTY_STYLE_BOTTLE,
	)

/datum/bounty_admin_panel/proc/activity_choices()
	return list(
		"At a bar" = BOUNTY_ACTIVITY_BAR,
		"Chatting" = BOUNTY_ACTIVITY_CHAT,
		"Trading" = BOUNTY_ACTIVITY_TRADE,
		"Exploring" = BOUNTY_ACTIVITY_EXPLORE,
		"Looting" = BOUNTY_ACTIVITY_LOOT,
		"Camping" = BOUNTY_ACTIVITY_CAMP,
		"Blending in" = BOUNTY_ACTIVITY_BLEND,
	)

/datum/bounty_admin_panel/proc/placement_choices()
	return list(
		"Planet" = BOUNTY_PLACEMENT_PLANET,
		"Space ruin" = BOUNTY_PLACEMENT_RUIN,
		"NPC pirate ship" = BOUNTY_PLACEMENT_NPC_SHIP,
		"Trader outpost" = BOUNTY_PLACEMENT_TRADER_OUTPOST,
	)

/// The loaded sites of `kind`, labelled with their zone and overmap position
/datum/bounty_admin_panel/proc/site_choices(kind)
	var/list/sites = list()
	switch(kind)
		if(BOUNTY_PLACEMENT_PLANET)
			for(var/obj/structure/overmap/planet/planet in GLOB.overmap_planets)
				if(!QDELETED(planet) && planet.loaded)
					sites += planet
		if(BOUNTY_PLACEMENT_RUIN)
			for(var/obj/structure/overmap/space_ruin/ruin in GLOB.space_ruin_signals)
				if(!QDELETED(ruin) && ruin.loaded)
					sites += ruin
		if(BOUNTY_PLACEMENT_NPC_SHIP)
			for(var/obj/structure/overmap/ship/npc/ship in SSnpc_ships.active_ships)
				if(!QDELETED(ship) && !ship.abandoned)
					sites += ship
		if(BOUNTY_PLACEMENT_TRADER_OUTPOST)
			for(var/obj/structure/overmap/trader_outpost/outpost in GLOB.trader_outposts)
				if(!QDELETED(outpost) && outpost.loaded)
					sites += outpost
	var/list/choices = list()
	for(var/obj/structure/overmap/site as anything in sites)
		choices[unique_label(choices, "[site_name(site)] ([site_where(site)])")] = WEAKREF(site)
	return choices

/// Every player ship, for a private offer
/datum/bounty_admin_panel/proc/ship_choices()
	var/list/choices = list()
	for(var/obj/structure/overmap/ship/ship in SSovermap.simulated_ships)
		if(QDELETED(ship) || ship.abandoned || istype(ship, /obj/structure/overmap/ship/npc))
			continue
		choices[unique_label(choices, "Private to [site_name(ship)]")] = WEAKREF(ship)
	return choices

/// Every running prison, labelled with its free cells
/datum/bounty_admin_panel/proc/prison_choices()
	var/list/choices = list()
	for(var/datum/outpost_prison/prison in GLOB.outpost_prisons)
		if(QDELETED(prison))
			continue
		var/free = prison.free_slots()
		choices[unique_label(choices, "[prison_name(prison)]: [free] free cell\s")] = WEAKREF(prison)
	return choices

// ===== DESCRIPTIONS =====

/datum/bounty_admin_panel/proc/criminal_name(mob/living/basic/bounty_criminal/criminal)
	if(!criminal)
		return "nobody"
	return criminal.record?.name || criminal.real_name || criminal.name

/// "Wanted normal (knife)", "Most Wanted boss (juggernaut)"
/datum/bounty_admin_panel/proc/record_kind(datum/bounty_record/record)
	if(!record)
		return "no record"
	var/variant = record.kit || record.style
	return "[bounty_tier_name(record.tier)] [record.archetype || "criminal"][variant ? " ([variant])" : ""]"

/datum/bounty_admin_panel/proc/criminal_label(mob/living/basic/bounty_criminal/criminal)
	var/area/place = get_area(criminal)
	return "[criminal_name(criminal)]: [record_kind(criminal.record)], [criminal.capture_state()], in [place?.name || "nowhere"]"

/datum/bounty_admin_panel/proc/site_name(obj/structure/overmap/site)
	if(QDELETED(site))
		return "no site"
	return site.display_name || site.name

/// "red, 12,4": the site's zone band and overmap position
/datum/bounty_admin_panel/proc/site_where(obj/structure/overmap/site)
	var/turf/spot = get_turf(site)
	if(!spot)
		return "off the map"
	var/zone = "unknown zone"
	switch(SSovermap.get_zone_band_for_turf(spot))
		if(ZONE_GREEN)
			zone = "green"
		if(ZONE_YELLOW)
			zone = "yellow"
		if(ZONE_RED)
			zone = "red"
	var/list/coords = site.get_relative_overmap_coords()
	return length(coords) >= 2 ? "[zone], [coords[1]],[coords[2]]" : zone

/datum/bounty_admin_panel/proc/prison_name(datum/outpost_prison/prison)
	if(QDELETED(prison))
		return "any prison"
	return prison.outpost?.name || "an unnamed prison"

/**
 * One posting as the panel shows it: tier, name, placement kind, place, status, who it is for,
 * hunters, where the criminal is (with a jump link), time left and value.
 */
/datum/bounty_admin_panel/proc/posting_row(datum/criminal_bounty/posting)
	var/datum/bounty_record/record = posting.record
	var/obj/structure/overmap/site = posting.site_ref?.resolve()
	var/obj/structure/overmap/ship/private_ship = posting.private_to?.resolve()
	var/hunters = 0
	for(var/datum/weakref/claimant in posting.claimants)
		if(!QDELETED(claimant.resolve()))
			hunters++
	var/mob/living/basic/bounty_criminal/criminal = posting.criminal()
	var/location = criminal ? "[ADMIN_VERBOSEJMP(criminal)], [criminal.capture_state()]" : "not spawned (its site is not loaded)"
	return list(
		"tier" = bounty_tier_name(record?.tier),
		"name" = record?.name || "nobody",
		"kind" = posting.placement_kind || "no placement",
		"place" = site ? "[site_name(site)] ([site_where(site)])" : "no site",
		"status" = posting.status,
		"for" = posting.private_to ? "private to [site_name(private_ship)]" : "public",
		"hunters" = hunters,
		"location" = location,
		"time_left" = time_left_text(posting),
		"value" = posting.value,
	)

/// "20 minutes left", "no time left", or "no clock" for a posting that never runs out
/datum/bounty_admin_panel/proc/time_left_text(datum/criminal_bounty/posting)
	if(!posting.expires_at)
		return "no clock"
	var/left = posting.expires_at - world.time
	return left >= 1 SECONDS ? "[DisplayTimeText(left, 1)] left" : "no time left"

/// posting_row() as one line of chat
/datum/bounty_admin_panel/proc/posting_line(list/row)
	return "<b>[row["tier"]]: [row["name"]]</b> ([row["kind"]]) at [row["place"]]. [capitalize(row["status"])], [row["for"]], [row["hunters"]] hunting, [row["time_left"]], [row["value"]] cr. Criminal: [row["location"]]"

/// The pool's records as the panel shows them: name, tier, archetype, status, the prison they wait for, and age
/datum/bounty_admin_panel/proc/pool_rows()
	var/list/rows = list()
	for(var/datum/bounty_record/record in GLOB.bounty_prisoner_pool)
		rows += list(list(
			"id" = record.id,
			"name" = record.name || "nobody",
			"tier" = bounty_tier_name(record.tier),
			"archetype" = record.archetype || "criminal",
			"status" = record.status,
			"prison" = prison_name(record.preferred_prison?.resolve()),
			"age" = age_text(world.time - record.created_at),
		))
	return rows

/// "new" or "5 minutes old", for a record made `age` deciseconds ago
/datum/bounty_admin_panel/proc/age_text(age)
	return age >= 1 SECONDS ? "[DisplayTimeText(age, 1)] old" : "new"

// ===== SPAWNING =====

/**
 * Spawns a criminal of `tier` and `archetype` at `where`, with no posting: a new record from P1 with
 * the kit (a boss) or style (anyone else) set to `variant` when given, then P2's spawn, then P3's
 * `activity` when given. Returns the criminal, or null.
 */
/datum/bounty_admin_panel/proc/admin_spawn_criminal(mob/user, tier, archetype, variant, activity, turf/where)
	error = null
	if(!authorized(user))
		return null
	if(!(tier in choice_values(tier_choices())))
		return refuse(user, "Pick Petty, Wanted or Most Wanted.")
	if(!(archetype in choice_values(archetype_choices())))
		return refuse(user, "Pick meek, normal or mini-boss.")
	var/list/kits = choice_values(kit_choices())
	if(variant)
		if(archetype == BOUNTY_ARCHETYPE_BOSS && !(variant in kits))
			return refuse(user, "A mini-boss needs a kit, not [variant].")
		var/list/styles = choice_values(style_choices()) + BOUNTY_STYLE_HOLDOUT
		if(archetype != BOUNTY_ARCHETYPE_BOSS && !(variant in styles))
			return refuse(user, "[variant] is not a fighting style.")
	if(activity && !(activity in choice_values(activity_choices())))
		return refuse(user, "[activity] is not an activity.")
	where = get_turf(where)
	if(!where)
		return refuse(user, "There is no floor there to put them on.")
	var/datum/bounty_record/record = generate_bounty_record(tier, archetype, BOUNTY_PLACEMENT_PLANET)
	if(!record)
		return refuse(user, "No record was made for them.")
	record.tier = tier
	record.archetype = archetype
	if(archetype == BOUNTY_ARCHETYPE_BOSS)
		record.kit = variant || record.kit || pick(kits)
		record.style = null
	else
		record.kit = null
		if(variant)
			record.style = variant
	var/mob/living/basic/bounty_criminal/criminal = spawn_bounty_criminal(record, where, null)
	if(QDELETED(criminal))
		return refuse(user, "The criminal did not spawn.")
	if(activity)
		criminal.start_activity(activity, null)
	log_action(user, "spawn [criminal_name(criminal)], [record_kind(record)][activity ? ", [activity]" : ""], at [AREACOORD(where)]")
	tell(user, span_notice("Spawned [criminal_name(criminal)]: [record_kind(record)], wanted for [record.crime || "nothing yet"]."))
	return criminal

/// A free open tile next to `center` for a decoy to stand on, or `center` itself
/datum/bounty_admin_panel/proc/decoy_spot(turf/center)
	for(var/turf/open/candidate in orange(1, center))
		if(isspaceturf(candidate) || candidate.is_blocked_turf(FALSE))
			continue
		return candidate
	return center

/**
 * Spawns a decoy next to `wanted` who shares `shared` of their features (P1's decoy record), on
 * their posting if they have one, blending in (P3). Returns the decoy, or null.
 */
/datum/bounty_admin_panel/proc/admin_spawn_decoy(mob/user, mob/living/basic/bounty_criminal/wanted, shared = 1)
	error = null
	if(!authorized(user))
		return null
	if(QDELETED(wanted) || istype(wanted, /mob/living/basic/bounty_criminal/decoy))
		return refuse(user, "Pick a wanted criminal, not a decoy.")
	if(!wanted.record)
		return refuse(user, "[criminal_name(wanted)] has no record to copy.")
	var/turf/center = get_turf(wanted)
	if(!center)
		return refuse(user, "[criminal_name(wanted)] is nowhere.")
	var/datum/bounty_record/decoy_record = make_decoy_record(wanted.record, isnum(shared) ? clamp(round(shared), 1, 2) : 1)
	if(!decoy_record)
		return refuse(user, "No decoy record was made.")
	var/mob/living/basic/bounty_criminal/decoy/decoy = new(decoy_spot(center))
	decoy.record = decoy_record
	decoy.posting_ref = wanted.posting_ref
	var/datum/criminal_bounty/posting = wanted.posting()
	if(posting)
		posting.decoys += WEAKREF(decoy)
	INVOKE_ASYNC(GLOBAL_PROC, GLOBAL_PROC_REF(apply_bounty_look), decoy, decoy_record, BOUNTY_ADMIN_DECOY_OUTFIT)
	decoy.start_activity(BOUNTY_ACTIVITY_BLEND, null)
	log_action(user, "spawn a decoy of [criminal_name(wanted)] at [AREACOORD(decoy)]")
	tell(user, span_notice("Spawned a decoy of [criminal_name(wanted)]."))
	return decoy

// ===== POSTINGS =====

/// Posts a bounty now through the board (P5). Returns the posting, or null.
/datum/bounty_admin_panel/proc/admin_post_bounty(mob/user, tier, kind, obj/structure/overmap/site, obj/structure/overmap/ship/private_to)
	error = null
	if(!authorized(user))
		return null
	if(!(tier in choice_values(tier_choices())))
		return refuse(user, "Pick Petty, Wanted or Most Wanted.")
	if(!(kind in choice_values(placement_choices())))
		return refuse(user, "Pick a planet, a ruin, a pirate ship or a trader outpost.")
	if(site && QDELETED(site))
		return refuse(user, "That site is gone.")
	if(private_to && QDELETED(private_to))
		return refuse(user, "That ship is gone.")
	var/datum/criminal_bounty/posting = post_criminal_bounty(tier, kind, site, private_to)
	if(QDELETED(posting))
		return refuse(user, "The board did not post it: no site fits, or the board refused.")
	var/audience = private_to ? "private to [site_name(private_to)]" : "public"
	log_action(user, "post a [bounty_tier_name(tier)] bounty on [posting.record?.name || "nobody"] at a [kind] ([site ? site_name(site) : "the board's pick"], [audience])")
	tell(user, span_notice("Posted: [posting_line(posting_row(posting))]"))
	return posting

/// Closes `posting` as an admin close (P5's close()). Returns TRUE if it closed.
/datum/bounty_admin_panel/proc/admin_close_posting(mob/user, datum/criminal_bounty/posting)
	error = null
	if(!authorized(user))
		return FALSE
	if(QDELETED(posting))
		return refuse(user, "That bounty is gone.")
	if(posting.status != BOUNTY_POSTING_OPEN)
		return refuse(user, "That bounty is already closed.")
	var/wanted_name = posting.record?.name || "nobody"
	posting.close(BOUNTY_CLOSE_ADMIN, null)
	log_action(user, "close the bounty on [wanted_name]")
	tell(user, span_notice("Closed the bounty on [wanted_name]."))
	return TRUE

/// Takes `posting` off its site and lists it again elsewhere (P5's relist()). Returns TRUE if asked.
/datum/bounty_admin_panel/proc/admin_relist_posting(mob/user, datum/criminal_bounty/posting)
	error = null
	if(!authorized(user))
		return FALSE
	if(QDELETED(posting))
		return refuse(user, "That bounty is gone.")
	if(posting.status != BOUNTY_POSTING_OPEN)
		return refuse(user, "Only an open bounty can be relisted.")
	var/wanted_name = posting.record?.name || "nobody"
	posting.relist("the board moved it")
	log_action(user, "relist the bounty on [wanted_name]")
	tell(user, span_notice("Relisted the bounty on [wanted_name]."))
	return TRUE

/// Moves the admin to `criminal`. Returns TRUE if they moved.
/datum/bounty_admin_panel/proc/admin_jump(mob/user, mob/living/basic/bounty_criminal/criminal)
	error = null
	if(!authorized(user))
		return FALSE
	var/turf/spot = get_turf(criminal)
	if(QDELETED(criminal) || !spot)
		return refuse(user, "The criminal is not spawned: their site is not loaded.")
	user.abstract_move(spot)
	log_action(user, "jump to [criminal_name(criminal)] at [AREACOORD(spot)]")
	return TRUE

/// Brings `criminal` to the admin's tile, out of any locker or crate. Returns TRUE if they came.
/datum/bounty_admin_panel/proc/admin_bring(mob/user, mob/living/basic/bounty_criminal/criminal)
	error = null
	if(!authorized(user))
		return FALSE
	if(QDELETED(criminal))
		return refuse(user, "The criminal is not spawned: their site is not loaded.")
	var/turf/spot = get_turf(user)
	if(!spot)
		return refuse(user, "You are nowhere.")
	var/turf/from = get_turf(criminal)
	criminal.pulledby?.stop_pulling()
	criminal.buckled?.unbuckle_mob(criminal, TRUE)
	criminal.forceMove(spot)
	log_action(user, "bring [criminal_name(criminal)] from [AREACOORD(from)] to [AREACOORD(spot)]")
	return TRUE

// ===== CAPTURE STATES =====

/// Health at or below which `criminal` counts as downed (P2's line)
/datum/bounty_admin_panel/proc/downed_line(mob/living/basic/bounty_criminal/criminal)
	return FLOOR(criminal.maxHealth * BOUNTY_ADMIN_DOWNED_FRACTION, 1)

/**
 * Puts `criminal` in capture state `state` (BOUNTY_STATE_*) by the means the game itself uses: damage
 * to the downed line, a stun, real handcuffs, death, or a heal that takes all of it off again. P2's
 * capture_state() then reads the result. Returns TRUE if done.
 */
/datum/bounty_admin_panel/proc/admin_force_state(mob/user, mob/living/basic/bounty_criminal/criminal, state)
	error = null
	if(!authorized(user))
		return FALSE
	if(QDELETED(criminal))
		return refuse(user, "That criminal is gone.")
	var/done = FALSE
	switch(state)
		if(BOUNTY_STATE_DOWNED)
			done = force_downed(user, criminal)
		if(BOUNTY_STATE_STUNNED)
			done = force_stunned(user, criminal)
		if(BOUNTY_STATE_RESTRAINED)
			done = force_restrained(user, criminal)
		if(BOUNTY_STATE_DEAD)
			done = force_dead(user, criminal)
		if(BOUNTY_STATE_FREE)
			done = force_free(user, criminal)
		else
			return refuse(user, "[state] is not a capture state.")
	if(!done)
		return FALSE
	var/now = criminal.capture_state()
	log_action(user, "force [criminal_name(criminal)] to [state] (capture state now [now], worst [criminal.worst_state])")
	var/note = ""
	if(state == BOUNTY_STATE_FREE && criminal.is_downed())
		note = " They still count as downed until they get back up."
	tell(user, span_notice("[criminal_name(criminal)] is now [now].[note]"))
	return TRUE

/// Damage straight to the downed line, past armour and multipliers; P2's downed state follows from the health
/datum/bounty_admin_panel/proc/force_downed(mob/user, mob/living/basic/bounty_criminal/criminal)
	if(criminal.stat == DEAD)
		return refuse(user, "[criminal_name(criminal)] is dead.")
	var/line = downed_line(criminal)
	var/excess = criminal.health - line
	if(excess > 0)
		criminal.adjust_health(excess, TRUE, TRUE)
	if(criminal.health > line)
		return refuse(user, "Something kept [criminal_name(criminal)] above the downed line ([criminal.health] health, line [line]).")
	return TRUE

/// A long paralysis, past stun immunity
/datum/bounty_admin_panel/proc/force_stunned(mob/user, mob/living/basic/bounty_criminal/criminal)
	if(criminal.stat == DEAD)
		return refuse(user, "[criminal_name(criminal)] is dead.")
	criminal.Paralyze(BOUNTY_ADMIN_STUN_TIME, TRUE)
	if(!criminal.IsParalyzed())
		return refuse(user, "[criminal_name(criminal)] shrugged the stun off.")
	return TRUE

/**
 * A new pair of real handcuffs in their contents, held as their `restraints`, as P2's restraints put
 * them; COMSIG_BOUNTY_CRIMINAL_RESTRAINED tells whoever listens. Admin cuffs never slip.
 */
/datum/bounty_admin_panel/proc/force_restrained(mob/user, mob/living/basic/bounty_criminal/criminal)
	if(criminal.stat == DEAD)
		return refuse(user, "[criminal_name(criminal)] is dead: the cuffs would only fall off.")
	if(!QDELETED(criminal.restraints))
		return refuse(user, "[criminal_name(criminal)] is already cuffed.")
	var/obj/item/restraints/handcuffs/cuffs = new(criminal)
	criminal.restraints = cuffs
	criminal.ai_controller?.CancelActions()
	SEND_SIGNAL(criminal, COMSIG_BOUNTY_CRIMINAL_RESTRAINED, user)
	criminal.update_appearance(UPDATE_OVERLAYS)
	return TRUE

/datum/bounty_admin_panel/proc/force_dead(mob/user, mob/living/basic/bounty_criminal/criminal)
	if(criminal.stat == DEAD)
		return refuse(user, "[criminal_name(criminal)] is already dead.")
	criminal.death()
	if(criminal.stat != DEAD)
		return refuse(user, "[criminal_name(criminal)] did not die.")
	return TRUE

/**
 * Takes every capture state off: the cuffs drop, the surrender ends, stuns end, all damage heals, and
 * the worst state goes back to free so a full-pay turn-in can be tried again. The dead stay dead (a
 * criminal can't be revived). P2's own downed state ends when they get back up.
 */
/datum/bounty_admin_panel/proc/force_free(mob/user, mob/living/basic/bounty_criminal/criminal)
	if(criminal.stat == DEAD)
		return refuse(user, "[criminal_name(criminal)] is dead, and the dead stay dead.")
	var/obj/item/restraints/handcuffs/cuffs = criminal.restraints
	if(cuffs)
		criminal.restraints = null
		if(!QDELETED(cuffs) && cuffs.loc == criminal)
			cuffs.forceMove(criminal.drop_location())
		SEND_SIGNAL(criminal, COMSIG_BOUNTY_CRIMINAL_UNRESTRAINED, user)
	REMOVE_TRAIT(criminal, TRAIT_BOUNTY_SURRENDERED, BOUNTY_TRAIT)
	criminal.SetParalyzed(0, TRUE)
	criminal.SetKnockdown(0, TRUE)
	criminal.SetStun(0, TRUE)
	criminal.SetImmobilized(0, TRUE)
	criminal.fully_heal(HEAL_DAMAGE)
	criminal.worst_state = BOUNTY_STATE_FREE
	criminal.update_appearance(UPDATE_OVERLAYS)
	return TRUE

// ===== THE PRISONER POOL =====

/**
 * Admits `record` from the pool into `prison` now, in its lowest free cell, past the cell's ready
 * time, the intake setting and the bounty caps, as the manipulator's own spawn is. The record leaves
 * the pool before the prisoner is built, with no sleep between (AR-F7). Returns the prisoner, or null.
 */
/datum/bounty_admin_panel/proc/admin_pool_admit(mob/user, datum/bounty_record/record, datum/outpost_prison/prison)
	error = null
	if(!authorized(user))
		return null
	if(!record || !(record in GLOB.bounty_prisoner_pool))
		return refuse(user, "That record is no longer in the pool.")
	if(QDELETED(prison) || !(prison in GLOB.outpost_prisons))
		return refuse(user, "That prison is gone.")
	var/datum/outpost_prison_cell/free_cell
	var/turf/spot
	if(prison.free_slots())
		for(var/datum/outpost_prison_cell/cell as anything in prison.cells)
			if(cell.occupant)
				continue
			spot = cell.arrival_turf()
			if(spot)
				free_cell = cell
				break
	if(!free_cell)
		return refuse(user, "[prison_name(prison)] has no free cell.")
	GLOB.bounty_prisoner_pool -= record
	var/mob/living/basic/outpost_prisoner/prisoner = new(spot, record)
	if(QDELETED(prisoner))
		return refuse(user, "The prisoner was not made, and [record.name]'s record is out of the pool.")
	prison.admit(prisoner, free_cell)
	prisoner.beam_in()
	if(record.status == BOUNTY_RECORD_POOLED || record.status == BOUNTY_RECORD_WANTED)
		record.status = BOUNTY_RECORD_IMPRISONED
	log_action(user, "admit bounty record [record.name] ([record_kind(record)]) into cell [free_cell.number] of [prison_name(prison)]")
	tell(user, span_notice("[record.name] is beaming into cell [free_cell.number] of [prison_name(prison)]."))
	return prisoner

/// Takes `record` out of the pool and closes it. Returns TRUE if dropped.
/datum/bounty_admin_panel/proc/admin_pool_drop(mob/user, datum/bounty_record/record)
	error = null
	if(!authorized(user))
		return FALSE
	if(!record || !(record in GLOB.bounty_prisoner_pool))
		return refuse(user, "That record is no longer in the pool.")
	GLOB.bounty_prisoner_pool -= record
	record.status = BOUNTY_RECORD_CLOSED
	log_action(user, "drop bounty record [record.name] ([record_kind(record)]) from the prisoner pool")
	tell(user, span_notice("Dropped [record.name] from the pool."))
	return TRUE

/**
 * Makes a record of `tier` and `archetype` as if a crew had just caught them alive and unhurt, and
 * adds it to the pool (P7), reserved for `preferred` if given. Returns the record, or null.
 */
/datum/bounty_admin_panel/proc/admin_pool_add(mob/user, tier, archetype, datum/outpost_prison/preferred)
	error = null
	if(!authorized(user))
		return null
	if(!(tier in choice_values(tier_choices())))
		return refuse(user, "Pick Petty, Wanted or Most Wanted.")
	if(!(archetype in choice_values(archetype_choices())))
		return refuse(user, "Pick meek, normal or mini-boss.")
	if(preferred && (QDELETED(preferred) || !(preferred in GLOB.outpost_prisons)))
		return refuse(user, "That prison is gone.")
	var/datum/bounty_record/record = generate_bounty_record(tier, archetype, BOUNTY_PLACEMENT_PLANET)
	if(!record)
		return refuse(user, "No record was made.")
	record.tier = tier
	record.archetype = archetype
	if(archetype == BOUNTY_ARCHETYPE_BOSS && !record.kit)
		record.kit = pick(choice_values(kit_choices()))
	record.captor_name = BOUNTY_ADMIN_TEST_CAPTOR
	record.hurt_fraction = 0
	if(!bounty_pool_add(record))
		return refuse(user, "The pool refused the record.")
	if(record.status == BOUNTY_RECORD_WANTED)
		record.status = BOUNTY_RECORD_POOLED
	if(preferred)
		record.preferred_prison = WEAKREF(preferred)
	log_action(user, "add test record [record.name] ([record_kind(record)]) to the prisoner pool, for [prison_name(preferred)]")
	tell(user, span_notice("Added [record.name] to the pool, for [prison_name(preferred)]."))
	return record

// ===== THE BOARD CLOCK =====

/// Runs the board's tick `count` times now. Returns how many ran.
/datum/bounty_admin_panel/proc/admin_board_ticks(mob/user, count)
	error = null
	if(!authorized(user))
		return 0
	if(!isnum(count) || count != round(count) || count < 1 || count > BOUNTY_ADMIN_MAX_TICKS)
		refuse(user, "Run 1 to [BOUNTY_ADMIN_MAX_TICKS] whole ticks.")
		return 0
	for(var/ran in 1 to count)
		SScriminal_bounties.board_tick()
		CHECK_TICK
	log_action(user, "run the bounty board's tick [count] time\s")
	tell(user, span_notice("Ran the board's tick [count] time\s."))
	return count

/**
 * What the board does once its gap between public bounties runs out: posts one public bounty now, of
 * a random tier at a placement that tier allows, at a site the board picks. Returns the posting.
 */
/datum/bounty_admin_panel/proc/admin_skip_post_gap(mob/user)
	error = null
	if(!authorized(user))
		return null
	var/tier = pick(BOUNTY_TIER_PETTY, BOUNTY_TIER_WANTED, BOUNTY_TIER_MOST_WANTED)
	var/list/kinds = list(BOUNTY_PLACEMENT_PLANET, BOUNTY_PLACEMENT_RUIN)
	if(tier != BOUNTY_TIER_MOST_WANTED)
		kinds += BOUNTY_PLACEMENT_TRADER_OUTPOST
	if(tier != BOUNTY_TIER_PETTY)
		kinds += BOUNTY_PLACEMENT_NPC_SHIP
	var/kind = pick(kinds)
	var/datum/criminal_bounty/posting = post_criminal_bounty(tier, kind)
	if(QDELETED(posting))
		return refuse(user, "The board posted nothing for a [bounty_tier_name(tier)] bounty at a [kind]: no site fits, or the board refused.")
	log_action(user, "skip the board's post gap: a [bounty_tier_name(tier)] bounty on [posting.record?.name || "nobody"] at a [kind]")
	tell(user, span_notice("Posted: [posting_line(posting_row(posting))]"))
	return posting

/// Takes `minutes` off every open posting's time left. Returns how many postings changed.
/datum/bounty_admin_panel/proc/admin_skip_clocks(mob/user, minutes)
	error = null
	if(!authorized(user))
		return 0
	if(!isnum(minutes) || minutes != round(minutes) || minutes < 1 || minutes > BOUNTY_ADMIN_MAX_MINUTES)
		refuse(user, "Take 1 to [BOUNTY_ADMIN_MAX_MINUTES] whole minutes off.")
		return 0
	var/count = 0
	for(var/datum/criminal_bounty/posting in GLOB.criminal_bounties)
		if(QDELETED(posting) || posting.status != BOUNTY_POSTING_OPEN || !posting.expires_at)
			continue
		posting.expires_at -= minutes MINUTES
		count++
	log_action(user, "take [minutes] min off [count] open bount[count == 1 ? "y" : "ies"]")
	tell(user, span_notice("Took [minutes] min off [count] open bount[count == 1 ? "y" : "ies"]. The board expires them on its next tick."))
	return count

#undef BOUNTY_ADMIN_MAX_TICKS
#undef BOUNTY_ADMIN_MAX_MINUTES
#undef BOUNTY_ADMIN_STUN_TIME
#undef BOUNTY_ADMIN_MAX_STEPS
#undef BOUNTY_ADMIN_DECOY_OUTFIT
#undef BOUNTY_ADMIN_TEST_CAPTOR
#undef BOUNTY_ADMIN_DOWNED_FRACTION
#undef BOUNTY_ADMIN_MENU_SPAWN
#undef BOUNTY_ADMIN_MENU_DECOY
#undef BOUNTY_ADMIN_MENU_POST
#undef BOUNTY_ADMIN_MENU_POSTINGS
#undef BOUNTY_ADMIN_MENU_FORCE
#undef BOUNTY_ADMIN_MENU_POOL
#undef BOUNTY_ADMIN_MENU_BOARD
