/**
 * # Bounty hunting: restraints on a criminal
 *
 * Owner: P2 body. Do not edit this file outside P2.
 *
 * What it owns: /datum/component/bounty_restraints, a port of the prisoner's cuff pattern
 * (outpost_prison_capture.dm) to bounty criminals. Any tg handcuffs, zipties or cable cuffs; cuff
 * and uncuff times; restrained means no attacks, no abilities, no plans and draggable; cuffs
 * slipping; the handcuff overlay; cuffs dropped on death (spec section 4). Cuffing a criminal gives
 * no claim on it: whoever gets it onto their own pad is paid.
 *
 * The shared vars (`restraints` and the rest) are declared in bounty_types.dm and nowhere else; a
 * var only P2 uses goes here with a `body_` prefix.
 */
