/**
 * # Bounty hunting: fugitives at trader outposts
 *
 * Owner: P6 outposts. Owns this file, voidcrew/_DEFINES/bounty_outpost.dm, the "Ask about" hook in
 * voidcrew/modules/trade/trader_npc.dm, the wanted board on the trader outpost maps
 * (trader_outpost_black_market.dmm, trader_outpost_general.dmm, trader_outpost_outfitter.dmm),
 * tgui/packages/tgui/interfaces/WantedBoard.tsx and the tests in
 * voidcrew/modules/unit_tests/voidcrew_bounty_outpost.dm. Do not edit this file outside P6.
 *
 * What it owns: identifying the fugitive (decision 16, spec section 7, abuse review section C):
 * - Blending in. The fugitive and BOUNTY_DECOY_COUNT decoys wear the zone's patron clothes and go
 *   by the same generic name ("patron", "dockhand", "spacer"); the alias is never shown. While
 *   they blend in nobody can pull them, turrets leave them alone and stray shots pass through them
 *   (/datum/component/bounty_outpost_blend).
 * - Decoys (/mob/living/basic/bounty_criminal/decoy): look-alikes with the same body and routine
 *   as the fugitive. Showing one the warrant, or hitting one on purpose, raises the posting's
 *   alert; a hit is also an outpost strike for the hitter.
 * - Traders' clues: any trader, the barkeep included, gives a ship hunting a fugitive there one
 *   true clue, a different one per trader.
 * - The warrant (/obj/item/paper/bounty_warrant): shown to the fugitive it exposes them (P3's
 *   on_confronted()); shown to anyone else they protest. A ship can show one every
 *   BOUNTY_WARRANT_COOLDOWN.
 * - The alert: at BOUNTY_OUTPOST_ALERT_SLIP the fugitive slips away and the bounty relists (P5's
 *   relist()).
 * - The walk out: when the posting closes or the fugitive slips away, the decoys and an uncaught
 *   fugitive walk to the hangar lift and fade out (/datum/component/bounty_outpost_exit).
 * - The wanted board (/obj/structure/bounty_wanted_board): a locked board on each concourse
 *   listing the public bounties.
 *
 * The shared vars are declared in bounty_types.dm and nowhere else; the vars below that only P6
 * uses carry an `outpost_` prefix.
 */

// =========================================================================
// THE ZONE'S LOOK
// =========================================================================
// Everyone blending in wears the same clothes, so faces, hair and the features are what tell them
// apart. None of the outfits has a hat: hair is a clue.

/// Halcyon (green): a customer in their good shirt
/datum/outfit/bounty_outpost_patron
	name = "Outpost patron"
	uniform = /obj/item/clothing/under/costume/buttondown/slacks
	suit = /obj/item/clothing/suit/jacket/bomber
	shoes = /obj/item/clothing/shoes/laceup

/// The Quartermain (yellow): a day hand from the loading bays, dressed like the depot's own
/datum/outfit/bounty_outpost_dockhand
	name = "Outpost dockhand"
	uniform = /obj/item/clothing/under/rank/cargo/tech
	suit = /obj/item/clothing/suit/hazardvest
	gloves = /obj/item/clothing/gloves/fingerless
	shoes = /obj/item/clothing/shoes/workboots

/// The Undertow (red): a spacer between ships
/datum/outfit/bounty_outpost_spacer
	name = "Outpost spacer"
	uniform = /obj/item/clothing/under/pants/jeans
	suit = /obj/item/clothing/suit/jacket/leather
	gloves = /obj/item/clothing/gloves/fingerless
	shoes = /obj/item/clothing/shoes/jackboots

/// What everyone blending in at `outpost` is called (AR-C2): never a name, never the alias
/proc/bounty_outpost_display_name(obj/structure/overmap/trader_outpost/outpost)
	if(istype(outpost, /obj/structure/overmap/trader_outpost/general))
		return "patron"
	if(istype(outpost, /obj/structure/overmap/trader_outpost/outfitter))
		return "dockhand"
	return "spacer"

/// Their description at `outpost`: the same for everyone blending in there
/proc/bounty_outpost_display_desc(obj/structure/overmap/trader_outpost/outpost)
	if(istype(outpost, /obj/structure/overmap/trader_outpost/general))
		return "Another customer passing through."
	if(istype(outpost, /obj/structure/overmap/trader_outpost/outfitter))
		return "Works the loading bays, or dresses like they do."
	return "Keeps to themselves. Most people here do."

/// What everyone blending in at `outpost` wears
/proc/bounty_outpost_outfit(obj/structure/overmap/trader_outpost/outpost)
	if(istype(outpost, /obj/structure/overmap/trader_outpost/general))
		return /datum/outfit/bounty_outpost_patron
	if(istype(outpost, /obj/structure/overmap/trader_outpost/outfitter))
		return /datum/outfit/bounty_outpost_dockhand
	return /datum/outfit/bounty_outpost_spacer

/// What a decoy says when shown a warrant, if the dialogue file has nothing for it
GLOBAL_LIST_INIT(bounty_decoy_protest_lines, list(
	"Not me, pal.",
	"Wrong person. Here, look.",
	"You've got the wrong one.",
))

/// What a decoy says when someone hits it, if the dialogue file has nothing for it
GLOBAL_LIST_INIT(bounty_decoy_hurt_lines, list(
	"Hey! What's your problem?",
	"Get off me!",
	"I didn't do anything!",
))

/// A trader's answer when they know nothing the others haven't said
#define BOUNTY_OUTPOST_NO_CLUE "Can't help you there."

// =========================================================================
// THE POSTING'S TRADER-OUTPOST STATE
// =========================================================================

/datum/criminal_bounty
	/// The trader outpost this posting is set up at, as a weakref (/obj/structure/overmap/trader_outpost)
	var/datum/weakref/outpost_site
	/// When each ship may show a warrant again: REF of the ship (or of the person, without one) -> world.time
	var/list/outpost_warrant_ready_at = list()
	/// Clues no trader has given yet at this site, each list(BOUNTY_CLUE_*, index); built on the first question
	var/list/outpost_clue_pool
	/// The clue each trader gives: REF of the trader -> list(BOUNTY_CLUE_*, index)
	var/list/outpost_trader_clues = list()
	/// What each trader told each ship: "trader REF|ship REF" -> the words
	var/list/outpost_clues_told = list()
	/// How many of the fugitive's features each decoy was made to share, in spawn order
	var/list/outpost_decoy_shares = list()

/**
 * Sets a trader-outpost bounty up to blend in, once P5 has spawned the criminal at the outpost
 * (site_ref and criminal_ref set):
 * - the record gets its old look, so the listing's mugshot shows how they used to look (AR-C1);
 * - the fugitive wears the zone's clothes and the zone's generic name, and blends in;
 * - BOUNTY_DECOY_COUNT decoys spawn out of sight, each sharing one or two of its features;
 * - the alert and the traders' clues start over.
 *
 * Refuses (FALSE) a mini-boss (AR-C9), an outpost that already has BOUNTY_OUTPOST_MAX_FUGITIVES,
 * and a posting whose site is not a loaded trader outpost. Returns TRUE when set up.
 */
/datum/criminal_bounty/proc/setup_outpost_blend()
	var/obj/structure/overmap/trader_outpost/outpost = site_ref?.resolve()
	var/mob/living/basic/bounty_criminal/fugitive = criminal()
	if(!istype(outpost) || !outpost.template_bottom_left || !outpost.outpost_template || !fugitive || !record)
		return FALSE
	if(istype(fugitive, /mob/living/basic/bounty_criminal/boss) || record.archetype == BOUNTY_ARCHETYPE_BOSS)
		log_game("BOUNTY: a mini-boss ([record.name]) was refused at [outpost]. Mini-bosses never go to trader outposts.")
		return FALSE
	if(!bounty_outpost_has_room(outpost, src))
		log_game("BOUNTY: [record.name] was refused at [outpost], which already has [BOUNTY_OUTPOST_MAX_FUGITIVES] fugitives.")
		return FALSE

	// A fresh start: decoys from an earlier site leave, and the alert and the clues start over.
	outpost_dismiss_decoys()
	outpost_site = WEAKREF(outpost)
	alert = 0
	outpost_clue_pool = null
	outpost_trader_clues = list()
	outpost_clues_told = list()
	outpost_decoy_shares = list()
	outpost_warrant_ready_at = list()

	// The listing's mugshot shows them before they changed their hair or clothes (AR-C1).
	if(!record.old_look && make_old_look(record))
		record.mugshot = null
		static_data_serial++

	var/display_name = bounty_outpost_display_name(outpost)
	var/display_desc = bounty_outpost_display_desc(outpost)
	var/outfit = bounty_outpost_outfit(outpost)

	// Nobody travels with them here: a companion standing by one patron would give them away.
	for(var/datum/weakref/companion_ref as anything in fugitive.companions | companions)
		var/mob/living/companion = companion_ref?.resolve()
		if(!QDELETED(companion))
			bounty_outpost_walk_out(companion, outpost)
	fugitive.companions.Cut()
	companions.Cut()

	if(!fugitive.site_bounds)
		fugitive.site_bounds = bounty_outpost_bounds(outpost)
	fugitive.AddComponent(/datum/component/bounty_outpost_blend, src, FALSE, display_name, display_desc)
	INVOKE_ASYNC(GLOBAL_PROC, GLOBAL_PROC_REF(apply_bounty_look), fugitive, record, outfit)
	fugitive.start_activity(BOUNTY_ACTIVITY_BLEND, null)

	var/feature_count = length(record.features)
	for(var/turf/spot as anything in bounty_outpost_spawn_spots(outpost, BOUNTY_DECOY_COUNT, fugitive))
		// One or two of its features each, and never all of them (make_decoy_record() holds to that too)
		var/shared = rand(1, 2)
		if(feature_count)
			shared = clamp(shared, 1, max(1, feature_count - 1))
		outpost_decoy_shares += shared
		var/mob/living/basic/bounty_criminal/decoy/decoy = new(spot)
		decoy.outpost_become(fugitive, make_decoy_record(record, shared), src, outpost, display_name, display_desc, outfit)
		decoys += WEAKREF(decoy)

	RegisterSignal(src, COMSIG_BOUNTY_POSTING_CLOSED, PROC_REF(outpost_on_closed), override = TRUE)
	log_game("BOUNTY: [record.name] is blending in at [outpost] as a [display_name], with [length(decoys)] decoys.")
	return TRUE

/**
 * Raises the fugitive's alert for `reason` (BOUNTY_ALERT_*): a wrong warrant, or a hit on a decoy,
 * whoever did it. At BOUNTY_OUTPOST_ALERT_SLIP a fugitive still blending in slips away: it walks
 * out to the hangar with its decoys, and the bounty relists at another trader outpost (P5's
 * relist()). Returns TRUE if the alert went up.
 */
/datum/criminal_bounty/proc/raise_alert(reason)
	if(status != BOUNTY_POSTING_OPEN || placement_kind != BOUNTY_PLACEMENT_TRADER_OUTPOST)
		return FALSE
	alert++
	log_game("BOUNTY: [record?.name]'s alert rose to [alert] after [reason].")
	if(alert >= BOUNTY_OUTPOST_ALERT_SLIP)
		outpost_slip_away()
	return TRUE

/**
 * The fugitive has noticed too much fuss: while it is still blending in and free, it and its
 * decoys leave, and the bounty relists. An exposed fugitive is already running or fighting and
 * stays. Returns TRUE if it slipped away.
 */
/datum/criminal_bounty/proc/outpost_slip_away()
	var/mob/living/basic/bounty_criminal/fugitive = criminal()
	if(!fugitive || !fugitive.blended || fugitive.capture_state() != BOUNTY_STATE_FREE)
		return FALSE
	var/obj/structure/overmap/trader_outpost/outpost = outpost_site?.resolve() || site_ref?.resolve()
	var/where = outpost ? outpost.name : "the outpost"
	log_game("BOUNTY: [record?.name] slipped away from [where].")
	// Detached first (outpost_release_site()), so relist() never deletes them mid-walk. P5 shows the
	// reason as "WANTED: <name>: <reason>."
	outpost_release_site()
	relist("slipped away from [where]")
	return TRUE

/// The decoys at the current site leave and fade out, and the posting forgets them
/datum/criminal_bounty/proc/outpost_dismiss_decoys()
	var/obj/structure/overmap/trader_outpost/outpost = outpost_site?.resolve()
	for(var/datum/weakref/decoy_ref as anything in decoys)
		var/mob/living/basic/bounty_criminal/decoy = decoy_ref?.resolve()
		if(!QDELETED(decoy))
			bounty_outpost_walk_out(decoy, outpost)
	decoys.Cut()

/**
 * Everyone this posting put at its trader outpost leaves: the decoys, and the fugitive if it is
 * still at the outpost. The posting lets go of them first, so closing or relisting it never
 * deletes them mid-walk, and the fugitive's own link to the posting is cut, so its body going away
 * is not read as a death. A fugitive already taken off the outpost (on a ship, say) stays with the
 * posting for P5 to deal with.
 */
/datum/criminal_bounty/proc/outpost_release_site()
	var/obj/structure/overmap/trader_outpost/outpost = outpost_site?.resolve()
	outpost_dismiss_decoys()
	var/mob/living/basic/bounty_criminal/fugitive = criminal()
	if(!fugitive || !outpost || get_trader_outpost_for_turf(get_turf(fugitive)) != outpost)
		return
	criminal_ref = null
	fugitive.posting_ref = null
	bounty_outpost_walk_out(fugitive, outpost)

/// The posting closed (P5's close()): the decoys and an uncaught fugitive walk out
/datum/criminal_bounty/proc/outpost_on_closed(datum/source, reason, obj/structure/overmap/ship/winner)
	SIGNAL_HANDLER
	UnregisterSignal(src, COMSIG_BOUNTY_POSTING_CLOSED)
	outpost_release_site()

/**
 * Whether `outpost` can take another fugitive (AR-C9): fewer than BOUNTY_OUTPOST_MAX_FUGITIVES open
 * postings set up to blend in there, not counting `except`. A posting refused at setup (a
 * mini-boss, say) never counts. P5 asks before it places a bounty at a trader outpost.
 */
/proc/bounty_outpost_has_room(obj/structure/overmap/trader_outpost/outpost, datum/criminal_bounty/except)
	var/count = 0
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(QDELETED(posting) || posting == except || posting.status != BOUNTY_POSTING_OPEN)
			continue
		if(posting.placement_kind != BOUNTY_PLACEMENT_TRADER_OUTPOST || posting.site_ref?.resolve() != outpost)
			continue
		if(posting.outpost_site?.resolve() != outpost)
			continue
		count++
	return count < BOUNTY_OUTPOST_MAX_FUGITIVES

/// The concourse as a leash, list(min_x, min_y, max_x, max_y, z) (the shape of site_bounds)
/proc/bounty_outpost_bounds(obj/structure/overmap/trader_outpost/outpost)
	var/turf/bottom_left = outpost?.template_bottom_left
	if(!bottom_left || !outpost.outpost_template)
		return null
	return list(
		bottom_left.x,
		bottom_left.y,
		bottom_left.x + outpost.outpost_template.width - 1,
		bottom_left.y + outpost.outpost_template.height - 1,
		bottom_left.z,
	)

/**
 * Up to `count` free floor tiles where customers go, for decoys: out of every player's sight if
 * possible, so nobody watches a patron appear (AR-C10). Never behind a counter, in a staff room
 * or on the hangar lift.
 */
/proc/bounty_outpost_spawn_spots(obj/structure/overmap/trader_outpost/outpost, count, atom/near)
	var/list/bounds = bounty_outpost_bounds(outpost)
	if(!bounds)
		return list()
	var/list/seeds = outpost.lobby_alcove_turfs.Copy()
	var/turf/near_turf = get_turf(near)
	if(near_turf)
		seeds += near_turf
	var/list/floor = bounty_outpost_public_floor(outpost, seeds)
	floor -= outpost.lobby_alcove_turfs
	var/list/watched = list()
	for(var/mob/player as anything in GLOB.player_list)
		var/turf/player_turf = get_turf(player)
		if(!player_turf || player_turf.z != bounds[5])
			continue
		for(var/turf/seen in view(world.view, player))
			watched[seen] = TRUE
	var/list/unseen = list()
	var/list/seen = list()
	for(var/turf/candidate as anything in floor)
		if(candidate.is_blocked_turf(exclude_mobs = FALSE))
			continue
		if(watched[candidate])
			seen += candidate
		else
			unseen += candidate
	var/list/spots = list()
	while(length(spots) < count && (length(unseen) || length(seen)))
		spots += pick_n_take(length(unseen) ? unseen : seen)
	return spots

/**
 * The concourse floor customers can walk: every open tile reachable from `seeds` (the hangar lift,
 * where the fugitive stands) without climbing a counter or passing a door that wants an ID.
 */
/proc/bounty_outpost_public_floor(obj/structure/overmap/trader_outpost/outpost, list/seeds)
	var/list/bounds = bounty_outpost_bounds(outpost)
	if(!bounds)
		return list()
	var/list/reached = list()
	var/list/floor = list()
	for(var/turf/seed as anything in seeds)
		if(!reached[seed] && bounty_outpost_turf_in_bounds(seed, bounds))
			reached[seed] = TRUE
			floor += seed
	var/index = 1
	while(index <= length(floor))
		var/turf/current = floor[index++]
		for(var/direction in GLOB.cardinals)
			var/turf/next = get_step(current, direction)
			if(!next || reached[next] || !bounty_outpost_turf_in_bounds(next, bounds))
				continue
			reached[next] = TRUE
			if(!isopenturf(next) || isspaceturf(next))
				continue
			var/area/place = next.loc
			if(istype(place, /area/space) || istype(place, /area/template_noop))
				continue
			var/obj/machinery/door/airlock/airlock = locate() in next
			if(airlock)
				if(!airlock.check_access(null)) // staff only
					continue
			else if(next.is_blocked_turf(exclude_mobs = TRUE))
				continue
			floor += next
	return floor

/// Whether `spot` is inside `bounds` (the shape bounty_outpost_bounds() returns)
/proc/bounty_outpost_turf_in_bounds(turf/spot, list/bounds)
	return spot && spot.z == bounds[5] && spot.x >= bounds[1] && spot.x <= bounds[3] && spot.y >= bounds[2] && spot.y <= bounds[4]

// =========================================================================
// CONFRONTING
// =========================================================================

/// Who a warrant cooldown belongs to: the user's ship, or the user without one
/proc/bounty_outpost_hunter_key(mob/living/user)
	return get_crew_ship(user) || user?.mind || user

/// Seconds until `user`'s ship may show a warrant for this posting again (0: now)
/datum/criminal_bounty/proc/outpost_warrant_wait(mob/living/user)
	var/ready_at = outpost_warrant_ready_at[REF(bounty_outpost_hunter_key(user))]
	return ready_at ? max(0, ready_at - world.time) : 0

/// Starts `user`'s ship's warrant cooldown
/datum/criminal_bounty/proc/outpost_start_warrant_cooldown(mob/living/user)
	outpost_warrant_ready_at[REF(bounty_outpost_hunter_key(user))] = world.time + BOUNTY_WARRANT_COOLDOWN

/**
 * `user` showed this posting's warrant to its fugitive: it stops blending in, remembers who, and
 * reacts as its kind does (P3's on_confronted(): a meek one bolts, a normal one fights).
 */
/datum/criminal_bounty/proc/outpost_confront(mob/living/basic/bounty_criminal/fugitive, mob/living/user)
	fugitive.grudge |= WEAKREF(user)
	var/datum/component/bounty_outpost_blend/blend = fugitive.GetComponent(/datum/component/bounty_outpost_blend)
	blend?.stop_blending()
	fugitive.blended = FALSE
	log_game("BOUNTY: [key_name(user)] confronted [record?.name] with the warrant at [AREACOORD(fugitive)].")
	fugitive.on_confronted(user)
	fugitive.bounty_say("accused_rightly")

/**
 * `user` showed this posting's warrant to the wrong person, `target`: they protest and show their
 * papers. At this posting's trader outpost, it raises the alert.
 */
/datum/criminal_bounty/proc/outpost_wrong_accusation(mob/living/basic/bounty_criminal/target, mob/living/user)
	target.outpost_protest(user)
	to_chat(user, span_notice("Their papers are in order. Not who you're after."))
	var/obj/structure/overmap/trader_outpost/outpost = outpost_site?.resolve()
	if(!outpost || get_trader_outpost_for_turf(get_turf(target)) != outpost)
		return
	log_game("BOUNTY: [key_name(user)] showed [record?.name]'s warrant to the wrong person at [AREACOORD(target)].")
	if(raise_alert(BOUNTY_ALERT_WRONG_WARRANT) && alert < BOUNTY_OUTPOST_ALERT_SLIP && status == BOUNTY_POSTING_OPEN)
		to_chat(user, span_warning("Heads turn. One more mistake and whoever you're after will slip away."))

/**
 * Someone showed them a warrant that isn't theirs: they protest, and show a docking pass that
 * checks out. Nothing else happens to them.
 */
/mob/living/basic/bounty_criminal/proc/outpost_protest(mob/user)
	if(stat != CONSCIOUS)
		return
	// Forced: a protest always comes out, whatever was said a moment ago (P1's third argument)
	if(!bounty_say("accused_wrongly", null, TRUE))
		say(pick(GLOB.bounty_decoy_protest_lines), forced = "bounty protest")
	if(user)
		visible_message(span_notice("[src] holds up a docking pass for [user] to read."), vision_distance = COMBAT_MESSAGE_RANGE)

// =========================================================================
// DECOYS
// =========================================================================

// Built-in values, P6's. Everything that could tell a decoy from its fugitive is copied from the
// fugitive when the decoy is made (outpost_match_body()), whatever the fugitive's kind.
/mob/living/basic/bounty_criminal/decoy
	name = "patron"
	desc = "Another customer passing through."
	maxHealth = BOUNTY_MEEK_HEALTH
	health = BOUNTY_MEEK_HEALTH
	/// Barks when hit are rate-limited on their own, beside bounty_say()'s cooldown
	COOLDOWN_DECLARE(outpost_bark_cooldown)

/**
 * Makes this decoy a look-alike of `fugitive` wanted on `posting` at `outpost`: `decoy_record`'s
 * face in the zone's `outfit`, the fugitive's body and routine, the zone's generic name. The
 * decoy is NOT linked to the posting through posting_ref: it is not the criminal, and nothing the
 * pad, the proof of death or the board does may treat it as one.
 */
/mob/living/basic/bounty_criminal/decoy/proc/outpost_become(mob/living/basic/bounty_criminal/fugitive, datum/bounty_record/decoy_record, datum/criminal_bounty/posting, obj/structure/overmap/trader_outpost/outpost, display_name, display_desc, outfit)
	record = decoy_record
	if(decoy_record?.gender)
		gender = decoy_record.gender
	site_bounds = bounty_outpost_bounds(outpost)
	outpost_match_body(fugitive)
	// The same routine as the fugitive's (AR-C6): the same AI controller type, so start_activity()
	// sets the same blend-in routine on both.
	var/datum/ai_controller/fugitive_controller = fugitive.ai_controller
	if(istype(fugitive_controller))
		var/datum/ai_controller/current = ai_controller
		if(!istype(current) || current.type != fugitive_controller.type)
			if(istype(current))
				QDEL_NULL(ai_controller)
			var/controller_type = fugitive_controller.type
			new controller_type(src)
	AddComponent(/datum/component/bounty_outpost_blend, posting, TRUE, display_name, display_desc)
	INVOKE_ASYNC(GLOBAL_PROC, GLOBAL_PROC_REF(apply_bounty_look), src, decoy_record, outfit)
	start_activity(BOUNTY_ACTIVITY_BLEND, null)

/**
 * Copies everything about `fugitive`'s body that a player could compare (AR-C6): health, stamina,
 * damage taken, speed, size, how it breathes and talks, and how it reacts to a touch.
 */
/mob/living/basic/bounty_criminal/decoy/proc/outpost_match_body(mob/living/basic/bounty_criminal/fugitive)
	maxHealth = fugitive.maxHealth
	health = fugitive.maxHealth
	max_stamina = fugitive.max_stamina
	stamina_crit_threshold = fugitive.stamina_crit_threshold
	stamina_recovery = fugitive.stamina_recovery
	max_stamina_slowdown = fugitive.max_stamina_slowdown
	damage_coeff = fugitive.damage_coeff?.Copy()
	status_flags = fugitive.status_flags
	mob_size = fugitive.mob_size
	faction = LAZYCOPY(fugitive.faction)
	habitable_atmos = fugitive.habitable_atmos?.Copy()
	unsuitable_atmos_damage = fugitive.unsuitable_atmos_damage
	minimum_survivable_temperature = fugitive.minimum_survivable_temperature
	maximum_survivable_temperature = fugitive.maximum_survivable_temperature
	unsuitable_cold_damage = fugitive.unsuitable_cold_damage
	unsuitable_heat_damage = fugitive.unsuitable_heat_damage
	speak_emote = fugitive.speak_emote?.Copy()
	verb_say = fugitive.verb_say
	verb_ask = fugitive.verb_ask
	verb_exclaim = fugitive.verb_exclaim
	verb_yell = fugitive.verb_yell
	verb_whisper = fugitive.verb_whisper
	bubble_icon = fugitive.bubble_icon
	response_help_continuous = fugitive.response_help_continuous
	response_help_simple = fugitive.response_help_simple
	response_disarm_continuous = fugitive.response_disarm_continuous
	response_disarm_simple = fugitive.response_disarm_simple
	response_harm_continuous = fugitive.response_harm_continuous
	response_harm_simple = fugitive.response_harm_simple
	attacked_sound = fugitive.attacked_sound
	set_varspeed(fugitive.speed)
	updatehealth()

/// A decoy never fights anyone (P2's gate on attacks)
/mob/living/basic/bounty_criminal/decoy/may_attack(atom/target)
	return FALSE

/// Confronting a decoy, from anywhere: it protests. Nothing else happens.
/mob/living/basic/bounty_criminal/decoy/on_confronted(mob/user)
	outpost_protest(user)

/// Someone hit it on purpose: a bark, then it backs off from them for a few seconds
/mob/living/basic/bounty_criminal/decoy/proc/outpost_react_to_hit(mob/living/attacker)
	if(stat != CONSCIOUS || is_downed() || is_restrained())
		return
	if(COOLDOWN_FINISHED(src, outpost_bark_cooldown))
		COOLDOWN_START(src, outpost_bark_cooldown, 8 SECONDS)
		if(!bounty_say("hurt"))
			say(pick(GLOB.bounty_decoy_hurt_lines), forced = "bounty decoy")
	if(QDELETED(attacker) || !isturf(loc) || HAS_TRAIT(src, TRAIT_IMMOBILIZED))
		return
	GLOB.move_manager.move_away(src, attacker, BOUNTY_DECOY_FLEE_DISTANCE, max(cached_multiplicative_slowdown, 1), BOUNTY_DECOY_FLEE_TIME, priority = MOVEMENT_ABOVE_SPACE_PRIORITY)

// =========================================================================
// BLENDING IN
// =========================================================================

/**
 * # Blending in at a trader outpost
 *
 * On the fugitive and on each decoy, so the two behave the same way (AR-C6, C7, C8):
 * - the zone's generic name and description (set once, and kept);
 * - nobody can pull, drag, shove or stuff them anywhere;
 * - the outpost's turrets leave them alone;
 * - a shot not aimed at them passes through them;
 * - a deliberate hit by a person counts: on a decoy it raises the alert and is an outpost strike,
 *   on the fugitive it ends the act.
 *
 * The fugitive stops blending in when exposed (the warrant, or a hit); a decoy never does. The
 * component stays on an exposed fugitive for the rest of its time at the outpost: its own shots
 * there pass through anyone not on its grudge list (AR-C8).
 */
/datum/component/bounty_outpost_blend
	/// The posting they are part of, as a weakref (/datum/criminal_bounty)
	var/datum/weakref/posting_ref
	/// A decoy, not the fugitive
	var/decoy = FALSE
	/// Still blending in
	var/blending = TRUE
	/// Walking out to the hangar (/datum/component/bounty_outpost_exit): hits and warrants no longer count
	var/leaving = FALSE
	/// move_resist before they blended in
	var/saved_move_resist
	/// Whether blending in added FACTION_TURRET
	var/added_turret_faction = FALSE
	/// Blows closer together than BOUNTY_OUTPOST_HIT_GRACE are one scuffle
	COOLDOWN_DECLARE(hit_grace)

/datum/component/bounty_outpost_blend/Initialize(datum/criminal_bounty/posting, decoy = FALSE, display_name, display_desc)
	if(!istype(parent, /mob/living/basic/bounty_criminal))
		return COMPONENT_INCOMPATIBLE
	posting_ref = posting ? WEAKREF(posting) : null
	src.decoy = decoy
	var/mob/living/basic/bounty_criminal/owner = parent
	owner.blended = TRUE
	if(display_name)
		owner.name = display_name
		owner.real_name = display_name
	if(display_desc)
		owner.desc = display_desc
	saved_move_resist = owner.move_resist
	owner.move_resist = MOVE_FORCE_VERY_STRONG
	ADD_TRAIT(owner, TRAIT_NO_CONTAINMENT, BOUNTY_OUTPOST_TRAIT)
	ADD_TRAIT(owner, TRAIT_NO_STORAGE_INSERT, BOUNTY_OUTPOST_TRAIT)
	// The turrets skip faction-mates before anything else: a patron minding their own business is
	// never a target, whatever P2's rule for criminals says.
	if(!(FACTION_TURRET in owner.faction))
		var/list/new_faction = LAZYCOPY(owner.faction)
		new_faction += FACTION_TURRET
		owner.faction = new_faction
		added_turret_faction = TRUE

/datum/component/bounty_outpost_blend/Destroy(force)
	stop_blending()
	return ..()

/datum/component/bounty_outpost_blend/RegisterWithParent()
	RegisterSignal(parent, COMSIG_ATOM_CAN_BE_PULLED, PROC_REF(on_pull_attempt))
	RegisterSignal(parent, COMSIG_MOUSEDROP_ONTO, PROC_REF(on_dragged))
	RegisterSignal(parent, COMSIG_PROJECTILE_PREHIT, PROC_REF(on_projectile_prehit))
	RegisterSignal(parent, COMSIG_ATOM_AFTER_ATTACKEDBY, PROC_REF(on_item_attack))
	RegisterSignal(parent, COMSIG_ATOM_ATTACK_HAND, PROC_REF(on_hand_attack))
	RegisterSignal(parent, COMSIG_ATOM_ATTACK_HAND_SECONDARY, PROC_REF(on_shoved))
	RegisterSignal(parent, COMSIG_MOB_BATONED, PROC_REF(on_batoned))
	RegisterSignal(parent, COMSIG_ATOM_HULK_ATTACK, PROC_REF(on_hulk_attack))
	RegisterSignals(parent, list(COMSIG_ATOM_ATTACK_BASIC_MOB, COMSIG_ATOM_ATTACK_ANIMAL), PROC_REF(on_creature_attack))
	RegisterSignal(parent, COMSIG_PROJECTILE_FIRER_BEFORE_FIRE, PROC_REF(on_firing))

/datum/component/bounty_outpost_blend/UnregisterFromParent()
	UnregisterSignal(parent, list(
		COMSIG_ATOM_CAN_BE_PULLED,
		COMSIG_MOUSEDROP_ONTO,
		COMSIG_PROJECTILE_PREHIT,
		COMSIG_ATOM_AFTER_ATTACKEDBY,
		COMSIG_ATOM_ATTACK_HAND,
		COMSIG_ATOM_ATTACK_HAND_SECONDARY,
		COMSIG_MOB_BATONED,
		COMSIG_ATOM_HULK_ATTACK,
		COMSIG_ATOM_ATTACK_BASIC_MOB,
		COMSIG_ATOM_ATTACK_ANIMAL,
		COMSIG_PROJECTILE_FIRER_BEFORE_FIRE,
	))

/// Ends the act: pullable and containable again, and fair game for P2's turret rule. The name stays.
/datum/component/bounty_outpost_blend/proc/stop_blending()
	if(!blending)
		return
	blending = FALSE
	var/mob/living/basic/bounty_criminal/owner = parent
	if(QDELETED(owner))
		return
	owner.blended = FALSE
	if(!leaving)
		owner.move_resist = saved_move_resist
	REMOVE_TRAIT(owner, TRAIT_NO_CONTAINMENT, BOUNTY_OUTPOST_TRAIT)
	REMOVE_TRAIT(owner, TRAIT_NO_STORAGE_INSERT, BOUNTY_OUTPOST_TRAIT)
	if(added_turret_faction)
		var/list/new_faction = LAZYCOPY(owner.faction)
		new_faction -= FACTION_TURRET
		owner.faction = new_faction
		added_turret_faction = FALSE

/datum/component/bounty_outpost_blend/proc/on_pull_attempt(datum/source, mob/living/puller)
	SIGNAL_HANDLER
	if(blending || leaving)
		return COMSIG_ATOM_CANT_PULL
	return NONE

/// Drag-drops (onto a bed, into a crate or disposals) never check move_resist, so they are refused here
/datum/component/bounty_outpost_blend/proc/on_dragged(datum/source, atom/over, mob/user)
	SIGNAL_HANDLER
	if(blending || leaving)
		return COMPONENT_CANCEL_MOUSEDROP_ONTO
	return NONE

/**
 * A shot not aimed at someone blending in passes through them (AR-C7): nobody can use a decoy as a
 * shield, or shoot "past" one to make a rival hit it. A shot aimed at them is a deliberate hit.
 */
/datum/component/bounty_outpost_blend/proc/on_projectile_prehit(datum/source, obj/projectile/projectile)
	SIGNAL_HANDLER
	if(leaving)
		return PROJECTILE_INTERRUPT_HIT_PHASE
	if(!blending)
		return NONE
	if(projectile.original != parent)
		return PROJECTILE_INTERRUPT_HIT_PHASE
	if(projectile.is_hostile_projectile() && isliving(projectile.firer))
		deliberate_hit(projectile.firer)
	return NONE

/datum/component/bounty_outpost_blend/proc/on_item_attack(datum/source, obj/item/weapon, mob/living/attacker, list/modifiers, list/attack_modifiers)
	SIGNAL_HANDLER
	if(weapon?.force)
		deliberate_hit(attacker)

/datum/component/bounty_outpost_blend/proc/on_hand_attack(datum/source, mob/living/user, list/modifiers)
	SIGNAL_HANDLER
	if(isliving(user) && (user.combat_mode || LAZYACCESS(modifiers, RIGHT_CLICK)))
		deliberate_hit(user)

/datum/component/bounty_outpost_blend/proc/on_shoved(datum/source, mob/living/user, list/modifiers)
	SIGNAL_HANDLER
	deliberate_hit(user)

/datum/component/bounty_outpost_blend/proc/on_batoned(datum/source, mob/living/user, obj/item/baton)
	SIGNAL_HANDLER
	deliberate_hit(user)

/datum/component/bounty_outpost_blend/proc/on_hulk_attack(datum/source, mob/living/user)
	SIGNAL_HANDLER
	deliberate_hit(user)

/datum/component/bounty_outpost_blend/proc/on_creature_attack(datum/source, mob/living/user)
	SIGNAL_HANDLER
	if(isliving(user) && user.melee_damage_upper > 0)
		deliberate_hit(user)

/// Someone hit them on purpose. Only a person counts: thrown things, explosions and NPCs never do.
/datum/component/bounty_outpost_blend/proc/deliberate_hit(mob/living/attacker)
	if(leaving || !istype(attacker) || !attacker.mind || attacker == parent)
		return
	INVOKE_ASYNC(src, PROC_REF(handle_hit), attacker)

/**
 * A person hit them on purpose.
 * - The fugitive: the act is over (it remembers who, and reacts as its kind does).
 * - A decoy (AR-C5): one outpost strike for the hitter, as for hitting a trader, and the bounty's
 *   alert rises once per scuffle, whoever swung. The decoy barks and backs off.
 */
/datum/component/bounty_outpost_blend/proc/handle_hit(mob/living/attacker)
	var/mob/living/basic/bounty_criminal/owner = parent
	if(QDELETED(owner) || QDELETED(attacker) || leaving)
		return
	if(!decoy)
		if(!blending)
			return
		owner.grudge |= WEAKREF(attacker)
		stop_blending()
		owner.on_confronted(attacker)
		return
	var/obj/structure/overmap/trader_outpost/outpost = get_trader_outpost_for_turf(get_turf(owner))
	outpost?.register_aggression(attacker)
	if(COOLDOWN_FINISHED(src, hit_grace))
		COOLDOWN_START(src, hit_grace, BOUNTY_OUTPOST_HIT_GRACE)
		var/datum/criminal_bounty/posting = posting_ref?.resolve()
		if(posting && !QDELETED(posting))
			log_game("BOUNTY: [key_name(attacker)] hit a decoy of [posting.record?.name] at [AREACOORD(owner)].")
			posting.raise_alert(BOUNTY_ALERT_DECOY_HIT)
	// The alert may have sent everyone out already
	var/mob/living/basic/bounty_criminal/decoy/decoy_mob = owner
	if(!leaving && istype(decoy_mob))
		decoy_mob.outpost_react_to_hit(attacker)

/// The fugitive fired: at a trader outpost its shot passes through anyone not on its grudge list (AR-C8)
/datum/component/bounty_outpost_blend/proc/on_firing(datum/source, obj/projectile/projectile, atom/fired_from, atom/original)
	SIGNAL_HANDLER
	if(decoy || !is_trader_outpost_protected(parent))
		return
	RegisterSignal(projectile, COMSIG_PROJECTILE_SELF_PREHIT, PROC_REF(on_own_projectile_prehit))

/datum/component/bounty_outpost_blend/proc/on_own_projectile_prehit(obj/projectile/source, atom/target)
	SIGNAL_HANDLER
	if(!isliving(target) || target == parent)
		return NONE
	var/mob/living/basic/bounty_criminal/owner = parent
	if(WEAKREF(target) in owner.grudge)
		return NONE
	return PROJECTILE_INTERRUPT_HIT_PHASE

// =========================================================================
// WALKING OUT
// =========================================================================

/// `walker` leaves `outpost`: walks to the nearest hangar lift and fades out, or fades where they are if they can't walk there
/proc/bounty_outpost_walk_out(mob/living/walker, obj/structure/overmap/trader_outpost/outpost)
	if(QDELETED(walker) || walker.GetComponent(/datum/component/bounty_outpost_exit))
		return
	walker.AddComponent(/datum/component/bounty_outpost_exit, bounty_outpost_exit_turf(walker, outpost))

/// The hangar lift alcove tile nearest `from`, on its level, or null
/proc/bounty_outpost_exit_turf(atom/from, obj/structure/overmap/trader_outpost/outpost)
	var/turf/start = get_turf(from)
	if(!start || !outpost)
		return null
	var/turf/nearest
	var/nearest_distance = INFINITY
	for(var/turf/alcove as anything in outpost.lobby_alcove_turfs)
		if(alcove.z != start.z)
			continue
		var/distance = get_dist(start, alcove)
		if(distance < nearest_distance)
			nearest = alcove
			nearest_distance = distance
	return nearest

/**
 * # Walking out
 *
 * Someone P6 put at an outpost is done there: their AI stops, nobody can hurt or pull them, and
 * they walk to the hangar lift and fade out. Anyone who can't walk (down, cuffed, hidden, dead)
 * or still walking after BOUNTY_OUTPOST_EXIT_TIMEOUT fades where they are.
 */
/datum/component/bounty_outpost_exit
	/// The hangar lift tile they are walking to, or null
	var/turf/destination
	/// Fading out now
	var/fading = FALSE

/datum/component/bounty_outpost_exit/Initialize(turf/destination)
	if(!isliving(parent))
		return COMPONENT_INCOMPATIBLE
	src.destination = destination
	var/mob/living/walker = parent
	var/datum/component/bounty_outpost_blend/blend = walker.GetComponent(/datum/component/bounty_outpost_blend)
	if(blend)
		blend.leaving = TRUE
	ADD_TRAIT(walker, TRAIT_AI_PAUSED, BOUNTY_OUTPOST_TRAIT)
	ADD_TRAIT(walker, TRAIT_GODMODE, BOUNTY_OUTPOST_TRAIT)
	walker.move_resist = MOVE_FORCE_VERY_STRONG
	walker.pulledby?.stop_pulling()
	walker.stop_pulling()
	addtimer(CALLBACK(src, PROC_REF(fade_out)), BOUNTY_OUTPOST_EXIT_TIMEOUT, TIMER_DELETE_ME)
	if(!destination || !can_walk())
		fade_out()
		return
	RegisterSignal(walker, COMSIG_MOVABLE_MOVED, PROC_REF(on_moved))
	GLOB.move_manager.jps_move(walker, destination, delay = BOUNTY_OUTPOST_EXIT_DELAY, timeout = BOUNTY_OUTPOST_EXIT_TIMEOUT, repath_delay = 2 SECONDS, max_path_length = 150, simulated_only = TRUE, priority = MOVEMENT_ABOVE_SPACE_PRIORITY)

/datum/component/bounty_outpost_exit/Destroy(force)
	destination = null
	return ..()

/// Whether they can walk out on their own feet
/datum/component/bounty_outpost_exit/proc/can_walk()
	var/mob/living/walker = parent
	if(walker.stat != CONSCIOUS || !isturf(walker.loc) || walker.buckled)
		return FALSE
	if(HAS_TRAIT(walker, TRAIT_IMMOBILIZED) || HAS_TRAIT(walker, TRAIT_FLOORED) || HAS_TRAIT(walker, TRAIT_RESTRAINED))
		return FALSE
	if(istype(walker, /mob/living/basic/bounty_criminal))
		var/mob/living/basic/bounty_criminal/criminal = walker
		if(criminal.hidden || criminal.is_downed() || criminal.is_restrained())
			return FALSE
	return TRUE

/datum/component/bounty_outpost_exit/proc/on_moved(datum/source, atom/old_loc, dir, forced, list/old_locs)
	SIGNAL_HANDLER
	if(destination && get_dist(parent, destination) <= 1)
		fade_out()

/datum/component/bounty_outpost_exit/proc/fade_out()
	if(fading)
		return
	fading = TRUE
	var/mob/living/walker = parent
	UnregisterSignal(walker, COMSIG_MOVABLE_MOVED)
	GLOB.move_manager.stop_looping(walker)
	animate(walker, alpha = 0, time = BOUNTY_OUTPOST_FADE_TIME)
	addtimer(CALLBACK(src, PROC_REF(vanish)), BOUNTY_OUTPOST_FADE_TIME, TIMER_DELETE_ME)

/datum/component/bounty_outpost_exit/proc/vanish()
	qdel(parent)

// =========================================================================
// ASKING TRADERS
// =========================================================================

/**
 * The trader-outpost posting `user`'s ship is hunting at `trader`'s outpost, if any: what the
 * "Ask about the wanted person" option on the trader's radial asks about. Only a ship hunting it
 * (a claimant) asks.
 */
/proc/bounty_outpost_ask_posting(mob/living/basic/outpost_trader/trader, mob/living/user)
	var/obj/structure/overmap/trader_outpost/outpost = trader?.outpost
	var/obj/structure/overmap/ship/ship = outpost ? get_crew_ship(user) : null
	if(!ship)
		return null
	var/datum/weakref/ship_ref = WEAKREF(ship)
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(QDELETED(posting) || posting.status != BOUNTY_POSTING_OPEN || posting.placement_kind != BOUNTY_PLACEMENT_TRADER_OUTPOST)
			continue
		if(posting.site_ref?.resolve() != outpost || !(ship_ref in posting.claimants))
			continue
		return posting
	return null

/**
 * `user` asked `trader` about the fugitive their ship is hunting there: the trader leans in and
 * tells them their one clue, quietly. Returns TRUE if there was anything to ask about.
 */
/proc/bounty_outpost_ask(mob/living/basic/outpost_trader/trader, mob/living/user)
	var/datum/criminal_bounty/posting = bounty_outpost_ask_posting(trader, user)
	if(!posting)
		return FALSE
	var/words
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	if(!fugitive || get_trader_outpost_for_turf(get_turf(fugitive)) != trader.outpost)
		words = "They're not here any more." // slipped away, or someone already dragged them off
	else
		words = posting.outpost_clue_for(trader, bounty_outpost_hunter_key(user))
	trader.visible_message(span_notice("[trader] leans in and says something quietly to [user]."), vision_distance = COMBAT_MESSAGE_RANGE, ignored_mobs = list(user))
	to_chat(user, span_notice("<b>[trader]</b> says quietly, \"[words]\""))
	log_game("BOUNTY: [key_name(user)] asked [trader] about [posting.record?.name]: \"[words]\"")
	return TRUE

/**
 * What `trader` tells the ship `hunter_key` about this fugitive: one clue per trader per ship,
 * and each trader a different one. Asking again gets the same answer.
 */
/datum/criminal_bounty/proc/outpost_clue_for(mob/living/basic/outpost_trader/trader, hunter_key)
	var/told_key = "[REF(trader)]|[REF(hunter_key)]"
	var/told = outpost_clues_told[told_key]
	if(told)
		return told == BOUNTY_OUTPOST_NO_CLUE ? told : "I told you what I know. [told]"
	var/words = outpost_trader_clue(trader)
	outpost_clues_told[told_key] = words
	return words

/// The words of `trader`'s clue now: the kind they were given, or the next kind nobody has given yet
/datum/criminal_bounty/proc/outpost_trader_clue(mob/living/basic/outpost_trader/trader)
	var/trader_key = REF(trader)
	var/list/kind = outpost_trader_clues[trader_key]
	if(kind)
		var/words = outpost_clue_words(kind)
		if(words)
			return words
	if(isnull(outpost_clue_pool))
		outpost_clue_pool = outpost_build_clue_pool()
	for(var/list/candidate as anything in outpost_clue_pool)
		var/words = outpost_clue_words(candidate)
		if(!words)
			continue
		outpost_clue_pool -= list(candidate)
		outpost_trader_clues[trader_key] = candidate
		return words
	return BOUNTY_OUTPOST_NO_CLUE

/// Every clue the traders here could give, shuffled: where they were seen, their hair, each feature, each decoy ruled out
/datum/criminal_bounty/proc/outpost_build_clue_pool()
	var/list/pool = list(list(BOUNTY_CLUE_SEEN, 0))
	if(bounty_outpost_hair_clue(record))
		pool += list(list(BOUNTY_CLUE_HAIR, 0))
	var/list/lines = record?.feature_lines()
	for(var/index in 1 to length(lines))
		pool += list(list(BOUNTY_CLUE_FEATURE, index))
	for(var/index in 1 to length(decoys))
		pool += list(list(BOUNTY_CLUE_RULED_OUT, index))
	shuffle_inplace(pool)
	return pool

/**
 * The words for clue `kind` (list(BOUNTY_CLUE_*, index)), true now, or null if it can't be said
 * truthfully: the fugitive is gone, the decoy is gone, or where they stand could fit anyone else.
 */
/datum/criminal_bounty/proc/outpost_clue_words(list/kind)
	var/obj/structure/overmap/trader_outpost/outpost = outpost_site?.resolve()
	switch(kind[1])
		if(BOUNTY_CLUE_SEEN)
			var/mob/living/basic/bounty_criminal/fugitive = criminal()
			var/where = fugitive ? bounty_outpost_where(fugitive, outpost) : null
			return where ? "Saw someone like that [where], not long ago." : null
		if(BOUNTY_CLUE_HAIR)
			return bounty_outpost_hair_clue(record)
		if(BOUNTY_CLUE_FEATURE)
			var/list/lines = record?.feature_lines()
			var/index = kind[2]
			if(index < 1 || index > length(lines))
				return null
			var/line = trim(STRIP_HTML_FULL(lines[index], MAX_MESSAGE_LEN))
			return line ? "I remember one thing about them. [line]" : null
		if(BOUNTY_CLUE_RULED_OUT)
			var/index = kind[2]
			if(index < 1 || index > length(decoys))
				return null
			var/datum/weakref/decoy_ref = decoys[index]
			var/mob/living/basic/bounty_criminal/decoy = decoy_ref?.resolve()
			if(QDELETED(decoy) || decoy.stat == DEAD)
				return null
			var/where = bounty_outpost_where(decoy, outpost)
			if(!where)
				return null
			// Only if the place picks out one person: never a hint that could fit the fugitive
			for(var/mob/living/basic/bounty_criminal/other as anything in outpost_candidates())
				if(other != decoy && bounty_outpost_where(other, outpost) == where)
					return null
			return "The one [where]? Not who you're after."
	return null

/// The fugitive and its decoys, whoever of them still exists
/datum/criminal_bounty/proc/outpost_candidates()
	. = list()
	var/mob/living/basic/bounty_criminal/fugitive = criminal()
	if(fugitive)
		. += fugitive
	for(var/datum/weakref/decoy_ref as anything in decoys)
		var/mob/living/basic/bounty_criminal/decoy = decoy_ref?.resolve()
		if(!QDELETED(decoy))
			. += decoy

/**
 * Where `thing` is at `outpost`, as a trader would put it: "by the bar", "near the docks", "near
 * Dram's counter", "by the pond", "at one of the tables", or which side of the concourse. Null if
 * it isn't at the outpost.
 */
/proc/bounty_outpost_where(atom/thing, obj/structure/overmap/trader_outpost/outpost)
	var/turf/spot = get_turf(thing)
	var/list/bounds = bounty_outpost_bounds(outpost)
	if(!spot || !bounds)
		return null
	if(!bounty_outpost_turf_in_bounds(spot, bounds))
		return get_trader_outpost_for_turf(spot) == outpost ? "down in the hangars" : null
	if(locate(/obj/structure/chair/stool/bar) in range(2, spot))
		return "by the bar"
	for(var/turf/alcove as anything in outpost.lobby_alcove_turfs)
		if(alcove.z == spot.z && get_dist(alcove, spot) <= 4)
			return "near the docks"
	for(var/mob/living/basic/outpost_trader/trader as anything in outpost.traders)
		if(!QDELETED(trader) && trader.z == spot.z && get_dist(trader, spot) <= 3)
			return "near [trader.name]'s counter"
	if(locate(/turf/open/water/outpost_pond) in range(2, spot))
		return "by the pond"
	if(locate(/obj/structure/table) in range(1, spot))
		return "at one of the tables"
	var/turf/middle = locate(round((bounds[1] + bounds[3]) / 2), round((bounds[2] + bounds[4]) / 2), bounds[5])
	if(get_dist(middle, spot) <= max(1, round(min(bounds[3] - bounds[1], bounds[4] - bounds[2]) / 8)))
		return "in the middle of the concourse"
	return "on the [dir2text(get_dir(middle, spot))] side of the concourse"

/// How the fugitive's hair differs from the mugshot, as a trader would say it, or null if it doesn't
/proc/bounty_outpost_hair_clue(datum/bounty_record/record)
	var/datum/bounty_look/now = record?.look
	var/datum/bounty_look/then = record?.old_look
	if(!now || !then)
		return null
	var/style_changed = now.hairstyle && now.hairstyle != then.hairstyle
	var/colour_changed = now.hair_color && then.hair_color && lowertext(now.hair_color) != lowertext(then.hair_color)
	if(!style_changed && !colour_changed)
		return null
	if(style_changed && findtext(now.hairstyle, "Bald"))
		return "They've shaved their head since that picture was taken."
	var/style = style_changed ? bounty_outpost_hairstyle_words(now.hairstyle) : null
	var/colour = colour_changed ? bounty_outpost_colour_word(now.hair_color) : null
	if(style && colour)
		return "Their hair's not like that picture any more. [capitalize(style)], dyed [colour], last I saw."
	if(colour)
		return "Their hair's not like that picture any more. Dyed [colour], last I saw."
	return "Their hair's not like that picture any more. [capitalize(style)], last I saw."

/// A hairstyle's name as someone would say it: "Long Hair 2 (Alt)" is "long hair"
/proc/bounty_outpost_hairstyle_words(hairstyle)
	var/words = lowertext("[hairstyle]")
	var/bracket = findtext(words, "(")
	if(bracket)
		words = copytext(words, 1, bracket)
	var/static/regex/digits = regex(@"[0-9]+", "g")
	words = digits.Replace(words, "")
	return trim(words) || "different"

/// A "#rrggbb" hair colour in a word or two
/proc/bounty_outpost_colour_word(colour)
	if(!istext(colour) || length(colour) < 7 || colour[1] != "#")
		return "a different colour"
	var/list/hsv = rgb2num(colour, COLORSPACE_HSV)
	if(length(hsv) < 3)
		return "a different colour"
	var/hue = hsv[1] || 0
	var/saturation = hsv[2]
	var/value = hsv[3]
	if(value < 18)
		return "black"
	if(saturation < 15)
		if(value > 85)
			return "white"
		return value > 55 ? "grey" : "dark grey"
	if(hue < 15 || hue >= 340)
		return value < 45 ? "dark red" : "red"
	if(hue < 45)
		if(value < 55)
			return "brown"
		return saturation > 60 ? "ginger" : "light brown"
	if(hue < 70)
		return value > 60 ? "blond" : "dark blond"
	if(hue < 170)
		return "green"
	if(hue < 255)
		return "blue"
	if(hue < 290)
		return "purple"
	return "pink"

// =========================================================================
// THE WARRANT
// =========================================================================

// P6's values. P5 prints it on the pad and writes the listing on it.
/obj/item/paper/bounty_warrant
	name = "bounty warrant"
	desc = "A printed warrant: a mugshot, the charges and what to look for. Show it to someone to see if they're who you're after."

/obj/item/paper/bounty_warrant/Initialize(mapload)
	. = ..()
	register_item_context()

/obj/item/paper/bounty_warrant/add_item_context(obj/item/source, list/context, atom/target, mob/living/user)
	if(isliving(target) && target != user)
		context[SCREENTIP_CONTEXT_LMB] = "Show warrant"
		return CONTEXTUAL_SCREENTIP_SET
	return NONE

/obj/item/paper/bounty_warrant/interact_with_atom(atom/interacting_with, mob/living/user, list/modifiers)
	if(!isliving(interacting_with) || interacting_with == user)
		return ..()
	show_warrant(interacting_with, user)
	return ITEM_INTERACT_SUCCESS

/**
 * `user` holds the warrant up to `target`.
 * - The fugitive it is for: exposed (outpost_confront()).
 * - Any other criminal or decoy: they protest; at the fugitive's outpost that raises the alert.
 * - Anyone else (a person, a trader, a loiterer): a look, and nothing else.
 * Showing it to a criminal or decoy starts the ship's BOUNTY_WARRANT_COOLDOWN.
 */
/obj/item/paper/bounty_warrant/proc/show_warrant(mob/living/target, mob/living/user)
	var/datum/criminal_bounty/posting = posting_ref?.resolve()
	if(QDELETED(posting) || posting.status != BOUNTY_POSTING_OPEN)
		to_chat(user, span_warning("This warrant is out of date."))
		return
	if(!istype(target, /mob/living/basic/bounty_criminal))
		user.visible_message(span_notice("[user] holds up a warrant for [target] to see."), span_notice("You hold up the warrant for [target] to see."), vision_distance = COMBAT_MESSAGE_RANGE)
		if(target.client)
			to_chat(target, span_notice("[user] shows you a bounty warrant. It isn't for you."))
		return
	if(target.stat != CONSCIOUS)
		to_chat(user, span_warning("[target] is in no state to look at anything."))
		return
	var/wait = posting.outpost_warrant_wait(user)
	if(wait)
		balloon_alert(user, "wait [DisplayTimeText(wait)]!")
		return
	posting.outpost_start_warrant_cooldown(user)
	user.visible_message(span_notice("[user] holds up a warrant for [target] to see."), span_notice("You hold up the warrant for [target] to see."), vision_distance = COMBAT_MESSAGE_RANGE)
	var/mob/living/basic/bounty_criminal/criminal = target
	if(criminal == posting.criminal())
		posting.outpost_confront(criminal, user)
	else
		posting.outpost_wrong_accusation(criminal, user)

// =========================================================================
// THE WANTED BOARD
// =========================================================================

/**
 * # Wanted board
 *
 * A locked board on each trader outpost's concourse: the public bounties with their mugshots,
 * tier, reward and where they were last seen. Read-only; hunts start from a ship's mission
 * console. Outpost property. Mugshots go through ui_static_data(), never ui_data() (AR-G1).
 */
/obj/structure/bounty_wanted_board
	name = "wanted board"
	desc = "A locked board of wanted notices, kept current from the bounty network. Hunts are taken on at a ship's mission console."
	icon = 'icons/obj/wallmounts.dmi'
	icon_state = "noticeboard"
	density = FALSE
	anchored = TRUE
	resistance_flags = INDESTRUCTIBLE | LAVA_PROOF | FIRE_PROOF | UNACIDABLE | ACID_PROOF
	/// The public postings (record id and serial) the viewers' static data was last built from
	var/outpost_static_signature

MAPPING_DIRECTIONAL_HELPERS(/obj/structure/bounty_wanted_board, 32)

/obj/structure/bounty_wanted_board/Initialize(mapload)
	. = ..()
	AddElement(/datum/element/outpost_property)
	update_appearance(UPDATE_OVERLAYS)

/obj/structure/bounty_wanted_board/update_overlays()
	. = ..()
	. += "notices_4"

/obj/structure/bounty_wanted_board/examine(mob/user)
	. = ..()
	var/count = length(bounty_public_postings())
	. += span_notice(count ? "[count] wanted notice\s posted. Use it to read them." : "No wanted notices posted right now.")

/obj/structure/bounty_wanted_board/item_interaction(mob/living/user, obj/item/tool, list/modifiers)
	if(istype(tool, /obj/item/paper) || istype(tool, /obj/item/photo))
		balloon_alert(user, "it's locked!")
		return ITEM_INTERACT_BLOCKING
	return ..()

/obj/structure/bounty_wanted_board/ui_interact(mob/user, datum/tgui/ui)
	ui = SStgui.try_update_ui(user, src, ui)
	if(!ui)
		ui = new(user, src, "WantedBoard", name)
		ui.open()

/obj/structure/bounty_wanted_board/ui_static_data(mob/user)
	var/list/mugshots = list()
	for(var/datum/criminal_bounty/posting as anything in bounty_public_postings())
		var/datum/bounty_record/record = posting.record
		var/mugshot = bounty_record_mugshot(record)
		if(mugshot)
			mugshots[record.id] = "data:image/png;base64,[mugshot]"
			continue
		// P1 may serve mugshots as a registered asset instead
		var/asset = bounty_mugshot_asset(record)
		if(asset && SSassets.cache[asset])
			SSassets.transport.send_assets(user, asset)
			mugshots[record.id] = SSassets.transport.get_asset_url(asset)
	outpost_static_signature = bounty_public_board_signature()
	return list("mugshots" = mugshots)

/obj/structure/bounty_wanted_board/ui_data(mob/user)
	// A posting came or went, or its picture changed: send the pictures again, next tick
	if(bounty_public_board_signature() != outpost_static_signature)
		addtimer(CALLBACK(src, TYPE_PROC_REF(/datum, update_static_data_for_all_viewers)), 1, TIMER_UNIQUE)
	return list("entries" = outpost_board_entries())

/// The public postings as the board lists them
/obj/structure/bounty_wanted_board/proc/outpost_board_entries()
	var/list/entries = list()
	for(var/datum/criminal_bounty/posting as anything in bounty_public_postings())
		var/datum/bounty_record/record = posting.record
		entries += list(list(
			"id" = record.id,
			"name" = record.name,
			"alias" = (record.alias && record.alias != record.name) ? record.alias : null,
			"tier" = bounty_tier_name(record.tier),
			"tier_level" = record.tier,
			"crime" = record.crime,
			"reward" = posting.value,
			"place" = bounty_posting_place_words(posting),
			"time_left" = posting.expires_at ? max(0, round((posting.expires_at - world.time) / (1 SECONDS))) : null,
		))
	return entries

/// The open public postings, every ship's to hunt
/proc/bounty_public_postings()
	. = list()
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(QDELETED(posting) || posting.status != BOUNTY_POSTING_OPEN || posting.private_to || !posting.record)
			continue
		. += posting

/// Changes whenever the board's pictures need sending again: a posting added or gone, or its picture changed
/proc/bounty_public_board_signature()
	var/list/parts = list()
	for(var/datum/criminal_bounty/posting as anything in bounty_public_postings())
		parts += "[posting.record.id]:[posting.static_data_serial]"
	return parts.Join(",")

/// Where a posting's criminal was last seen, for the board
/proc/bounty_posting_place_words(datum/criminal_bounty/posting)
	var/atom/site = posting.site_ref?.resolve()
	if(!site)
		return "Whereabouts unknown"
	switch(posting.placement_kind)
		if(BOUNTY_PLACEMENT_TRADER_OUTPOST)
			return "Seen at [site.name]"
		if(BOUNTY_PLACEMENT_NPC_SHIP)
			return "Somewhere aboard [site.name]"
	return "Last seen at [site.name]"

#undef BOUNTY_OUTPOST_NO_CLUE
