/**
 * # Bounty hunting: mini-bosses, shared parts
 *
 * Owner: P4 bosses. Owns this file, bounty_boss_kits.dm, voidcrew/_DEFINES/bounty_bosses.dm and
 * the tests in voidcrew/modules/unit_tests/voidcrew_bounty_bosses.dm. Do not edit this file
 * outside P4.
 *
 * What it owns: /mob/living/basic/bounty_criminal/boss (its body, built-in values and AI tree), the
 * bounty ability base with its wind-up, telegraph and stale-serial guard (a port of the horror's,
 * not a reuse of its type), scaling for extra hunters, exhaustion below 30% health, the cap on
 * damage to player ships, and on_confronted() for bosses (spec section 5).
 *
 * The shared vars are declared in bounty_types.dm and nowhere else; a var only P4 uses goes here
 * with a `boss_` prefix, or on the /boss subtypes.
 */
