/**
 * # Bounty hunting: how a criminal looks
 *
 * Owner: P1 identity. Do not edit this file outside P1.
 *
 * What it owns: the look builder that puts the same face (a /datum/bounty_look) on any mob in any
 * outfit, for any species in the pool, cached per record and outfit; the old look a trader-outpost
 * fugitive's mugshot shows (AR-C1); and the mugshot, built once per record and served to the UI
 * through ui_static_data() as base64 (spec sections 2, 8 and 10; AR-G1). Mugshots never go through
 * a ui_data() payload.
 *
 * How a look is built: a throwaway human dummy gets the look's species features first (a species'
 * visible organs take their shape from dna.features as they go in), then its species, body, skin,
 * hair and eyes, then the outfit (visuals only), then the glasses or scarf a record's features name
 * when the outfit leaves the eyes or neck free (no scarf with a prisoner's outfit). Its appearance is cached under "[record id]|[outfit]"
 * and copied onto the mob the way set_outpost_npc_look() does. A dummy is built once per record and
 * outfit, and once per record for the mugshot.
 *
 * The shared vars are declared in bounty_types.dm and nowhere else; a var only P1 uses goes in
 * bounty_identity.dm with an `identity_` prefix.
 */

/// Built looks: "[record id]|[outfit]" -> appearance, oldest first
GLOBAL_LIST_EMPTY(bounty_looks)
/// Whose each built look is: the same key -> weakref to the record, so a closed or deleted record's looks can go
GLOBAL_LIST_EMPTY(bounty_look_owners)
/// Mugshots built this round; each record's is built once
GLOBAL_VAR_INIT(bounty_mugshot_builds, 0)

// ===== DRESSING A MOB =====

/**
 * Dresses `target` as the person in `record` wearing `outfit` (a typepath): the same face in any
 * outfit. A record with no look gets one rolled for its species and gender first, and keeps it.
 * Updates the target's own overlays afterwards (cuffs and the like). Can sleep, so call it from an
 * async proc.
 */
/proc/apply_bounty_look(mob/living/target, datum/bounty_record/record, outfit)
	if(QDELETED(target) || !record)
		return
	var/look = get_bounty_look(record, outfit)
	if(QDELETED(target) || !look)
		return
	target.icon = 'icons/mob/human/human.dmi'
	target.icon_state = ""
	target.appearance_flags |= KEEP_TOGETHER
	target.copy_overlays(look, cut_old = TRUE)
	target.update_appearance(UPDATE_OVERLAYS)

/**
 * The appearance of `record`'s person in `outfit`, built the first time it's asked for and cached
 * per record and outfit (an outfit passed as a datum is built every time). Can sleep.
 */
/proc/get_bounty_look(datum/bounty_record/record, outfit)
	var/datum/bounty_look/look = bounty_ensure_look(record)
	var/key = (isnull(outfit) || ispath(outfit)) ? "[record.id]|[outfit]" : null
	if(key && GLOB.bounty_looks[key])
		return GLOB.bounty_looks[key]
	// Glasses are theirs anywhere; a scarf stays with their things when they go to prison.
	var/neckwear = !ispath(outfit, /datum/outfit/outpost_prisoner)
	var/mob/living/carbon/human/dummy/dummy = bounty_look_dummy(look, outfit, record.features, neckwear)
	var/built = dummy.appearance
	qdel(dummy)
	if(!key)
		return built
	// Two mobs can build the same look at once; the first one built is kept.
	if(!GLOB.bounty_looks[key])
		bounty_trim_look_cache()
		GLOB.bounty_looks[key] = built
		GLOB.bounty_look_owners[key] = WEAKREF(record)
	return GLOB.bounty_looks[key]

/**
 * A new human dummy looking like `look` in `outfit`, wearing the glasses and (when `neckwear`) the
 * scarf that `features` name, where the outfit leaves room. The caller deletes it. Can sleep.
 */
/proc/bounty_look_dummy(datum/bounty_look/look, outfit, list/features, neckwear = TRUE)
	var/mob/living/carbon/human/dummy/dummy = new
	// Before the species: its visible organs take their shape from dna.features as they go in.
	for(var/feature in look.features)
		dummy.dna.features[feature] = look.features[feature]
	dummy.gender = look.physique == FEMALE ? FEMALE : MALE
	dummy.physique = dummy.gender
	if(ispath(look.species, /datum/species) && dummy.dna.species.type != look.species)
		dummy.set_species(look.species)
	if(look.skin_tone)
		dummy.skin_tone = look.skin_tone
	dummy.set_hairstyle(look.hairstyle || "Bald", update = FALSE)
	if(look.hair_color)
		dummy.set_haircolor(look.hair_color, update = FALSE)
	dummy.set_facial_hairstyle(look.facial_hairstyle || "Shaved", update = FALSE)
	if(look.facial_hair_color || look.hair_color)
		dummy.set_facial_haircolor(look.facial_hair_color || look.hair_color, update = FALSE)
	if(look.eye_color)
		dummy.set_eye_color(look.eye_color)
	dummy.underwear = "Nude"
	dummy.undershirt = "Nude"
	dummy.socks = "Nude"
	// Without is_creating the limbs keep the colours they were made with.
	dummy.update_body(is_creating = TRUE)
	if(outfit)
		dummy.equipOutfit(outfit, visuals_only = TRUE)
	bounty_wear_features(dummy, features, neckwear)
	return dummy

/// Puts on the glasses and (when `neckwear`) the scarf that `features` name, where `dummy`'s outfit left the eyes or neck free
/proc/bounty_wear_features(mob/living/carbon/human/dummy/dummy, list/features, neckwear = TRUE)
	if(!length(features))
		return
	var/glasses = features[BOUNTY_FEATURE_GLASSES]
	var/glasses_type = istext(glasses) ? bounty_glasses_items()[glasses] : null
	if(glasses_type && !dummy.glasses)
		dummy.equip_to_slot_or_del(new glasses_type(dummy), ITEM_SLOT_EYES, initial = TRUE)
	var/scarf = features[BOUNTY_FEATURE_CLOTHING]
	var/scarf_type = (neckwear && istext(scarf)) ? bounty_scarf_items()[scarf] : null
	if(scarf_type && !dummy.wear_neck)
		dummy.equip_to_slot_or_del(new scarf_type(dummy), ITEM_SLOT_NECK, initial = TRUE)

/// Makes room in the look cache for one more: drops the looks of closed or deleted records, then the oldest
/proc/bounty_trim_look_cache()
	var/static/list/closed = list(BOUNTY_RECORD_RELEASED, BOUNTY_RECORD_ESCAPED, BOUNTY_RECORD_DEAD, BOUNTY_RECORD_CLOSED)
	for(var/key in GLOB.bounty_look_owners.Copy())
		var/datum/weakref/owner_ref = GLOB.bounty_look_owners[key]
		var/datum/bounty_record/owner = owner_ref?.resolve()
		if(!owner || (owner.status in closed))
			GLOB.bounty_looks -= key
			GLOB.bounty_look_owners -= key
	while(length(GLOB.bounty_looks) >= BOUNTY_LOOK_CACHE_MAX)
		var/oldest = GLOB.bounty_looks[1]
		GLOB.bounty_looks -= oldest
		GLOB.bounty_look_owners -= oldest

/// Forgets every built look of `record`, for when it closes. Mobs already dressed keep their look.
/proc/bounty_forget_looks(datum/bounty_record/record)
	if(!record)
		return
	var/prefix = "[record.id]|"
	for(var/key in GLOB.bounty_looks.Copy())
		if(findtext(key, prefix) == 1)
			GLOB.bounty_looks -= key
			GLOB.bounty_look_owners -= key

// ===== THE OLD LOOK (AR-C1) =====

/**
 * Gives `record` an older look (record.old_look) whose hair reads differently from their current
 * hair: another style, another colour, or both, and sometimes the beard. Species, skin, eyes and
 * body features stay. The clothes differ because the mugshot is taken in plain civilian clothes. A
 * species without hair keeps its look; only the clothes differ. Returns the old look.
 *
 * Idempotent: a record that has an old look keeps it. Clears a mugshot built before, so the next
 * one shows the old look. Doesn't sleep.
 */
/proc/make_old_look(datum/bounty_record/record)
	if(!record)
		return null
	if(record.old_look)
		return record.old_look
	var/datum/bounty_look/current = bounty_ensure_look(record)
	var/datum/bounty_look/old = bounty_copy_look(current)
	if(bounty_species_has_hair(old.species))
		var/current_hair = bounty_hair_key(current)
		var/own_colour = bounty_species_own_hair_colour(old.species)
		for(var/attempt in 1 to 12)
			var/change = own_colour ? rand(1, 3) : 1
			if(change != 2)
				old.hairstyle = outpost_npc_hairstyle(old.physique) || "Bald"
			if(change != 1)
				old.hair_color = random_hair_color()
				old.facial_hair_color = old.hair_color
			if(bounty_hair_key(old) != current_hair)
				break
		if(old.physique == MALE && bounty_species_has_facial_hair(old.species) && prob(50))
			old.facial_hairstyle = old.facial_hairstyle == "Shaved" ? (outpost_npc_facial_hairstyle() || "Shaved") : "Shaved"
	record.old_look = old
	record.mugshot = null
	return old

// ===== MUGSHOTS =====

/// Plain civilian clothes for a mugshot: a button-down shirt
/datum/outfit/bounty_mugshot
	name = "Bounty mugshot"
	uniform = /obj/item/clothing/under/costume/buttondown/slacks
	shoes = /obj/item/clothing/shoes/sneakers/black

/// Plain civilian clothes for a mugshot: a bomber jacket
/datum/outfit/bounty_mugshot/bomber
	name = "Bounty mugshot (bomber)"
	uniform = /obj/item/clothing/under/color/black
	suit = /obj/item/clothing/suit/jacket/bomber

/// Plain civilian clothes for a mugshot: a sweater
/datum/outfit/bounty_mugshot/sweater
	name = "Bounty mugshot (sweater)"
	uniform = /obj/item/clothing/under/color/grey
	suit = /obj/item/clothing/suit/toggle/jacket/sweater

/**
 * Their mugshot as a base64 PNG (no "data:" prefix), built once and cached on record.mugshot:
 * head and shoulders against a height-lined wall, in plain civilian clothes, showing
 * record.old_look when they have one. Sends COMSIG_BOUNTY_RECORD_MUGSHOT_READY on the record when
 * built. Builds a dummy the first time, so call it async, or use bounty_mugshot_asset() from UI code.
 */
/proc/bounty_record_mugshot(datum/bounty_record/record)
	if(!record)
		return ""
	if(record.mugshot)
		return record.mugshot
	bounty_ensure_look(record)
	var/static/list/outfits = list(/datum/outfit/bounty_mugshot, /datum/outfit/bounty_mugshot/bomber, /datum/outfit/bounty_mugshot/sweater)
	var/icon/portrait = bounty_mugshot_icon(record.old_look || record.look, record.features, pick(outfits))
	// Another build may have finished while this one waited on the dummy.
	if(record.mugshot)
		return record.mugshot
	GLOB.bounty_mugshot_builds++
	var/encoded = icon2base64(portrait)
	record.mugshot = istext(encoded) ? encoded : ""
	record.identity_mugshot_queued = FALSE
	SEND_SIGNAL(record, COMSIG_BOUNTY_RECORD_MUGSHOT_READY)
	return record.mugshot

/**
 * What UI code sends for `record`'s mugshot, through ui_static_data() and never ui_data() (AR-G1):
 * the base64 PNG, shown as `data:image/png;base64,<value>`, or "" until it's built. Never sleeps or
 * builds in the caller: the first ask queues the build for the next tick, and the record sends
 * COMSIG_BOUNTY_RECORD_MUGSHOT_READY when it's ready, so the UI can resend its static data.
 */
/proc/bounty_mugshot_asset(datum/bounty_record/record)
	if(!record)
		return ""
	if(record.mugshot)
		return record.mugshot
	if(!record.identity_mugshot_queued)
		record.identity_mugshot_queued = TRUE
		addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(bounty_record_mugshot), record), 1)
	return ""

/// The mugshot image of `look` in `outfit`: head and shoulders, cropped and scaled up, against a wall. Builds a dummy; can sleep.
/proc/bounty_mugshot_icon(datum/bounty_look/look, list/features, outfit = /datum/outfit/bounty_mugshot)
	var/mob/living/carbon/human/dummy/dummy = bounty_look_dummy(look, outfit, features, neckwear = FALSE)
	dummy.setDir(SOUTH)
	var/icon/body = getFlatIcon(dummy, SOUTH, no_anim = TRUE)
	qdel(dummy)
	var/icon/portrait = icon('icons/blanks/32x32.dmi', "nothing")
	portrait.DrawBox(BOUNTY_MUGSHOT_BACKDROP, 1, 1, 32, 32)
	for(var/line_y in list(22, 27, 32))
		portrait.DrawBox(BOUNTY_MUGSHOT_LINES, 1, line_y, 32, line_y)
	portrait.Blend(body, ICON_OVERLAY)
	portrait.Crop(BOUNTY_MUGSHOT_X1, BOUNTY_MUGSHOT_Y1, BOUNTY_MUGSHOT_X2, BOUNTY_MUGSHOT_Y2)
	portrait.Scale((BOUNTY_MUGSHOT_X2 - BOUNTY_MUGSHOT_X1 + 1) * BOUNTY_MUGSHOT_SCALE, (BOUNTY_MUGSHOT_Y2 - BOUNTY_MUGSHOT_Y1 + 1) * BOUNTY_MUGSHOT_SCALE)
	return portrait
