/**
 * # Bounty hunting: fugitives at trader outposts
 *
 * Owner: P6 outposts. Owns this file, voidcrew/_DEFINES/bounty_outpost.dm, the "Ask about" hook in
 * voidcrew/modules/trade/trader_npc.dm, the wanted board on the trader outpost maps
 * (trader_outpost_black_market.dmm, trader_outpost_general.dmm, trader_outpost_outfitter.dmm) and
 * the tests in voidcrew/modules/unit_tests/voidcrew_bounty_outpost.dm. Do not edit this file
 * outside P6.
 *
 * What it owns: identifying the fugitive (decision 16, spec section 7): the alias, decoys
 * (/mob/living/basic/bounty_criminal/decoy's behaviour), traders' clues, confronting with the
 * printed warrant (/obj/item/paper/bounty_warrant), the posting's alert, the wanted board
 * (/obj/structure/bounty_wanted_board) and the walk out when the bounty ends.
 *
 * The shared vars are declared in bounty_types.dm and nowhere else; a var only P6 uses goes here
 * with an `outpost_` prefix. The procs below start as P0 stubs.
 */

// P0 placeholder values, P6's to change.
/obj/item/paper/bounty_warrant
	name = "warrant"

/obj/structure/bounty_wanted_board
	name = "wanted board"
	desc = "A locked board of wanted notices."
	icon = 'icons/obj/wallmounts.dmi'
	icon_state = "noticeboard"
	density = FALSE
	anchored = TRUE

/**
 * Sets a trader-outpost bounty up to blend in: the fugitive's alias, and BOUNTY_DECOY_COUNT decoys
 * who share some of its features.
 *
 * P0 stub: nothing happens.
 */
/datum/criminal_bounty/proc/setup_outpost_blend()
	return

/**
 * Raises the fugitive's alert for `reason` (a wrong warrant, a hit on a decoy). High enough, the
 * fugitive slips away and the bounty relists (P5's relist()).
 *
 * P0 stub: nothing happens.
 */
/datum/criminal_bounty/proc/raise_alert(reason)
	return
