/**
 * # Bounty lairs: the mafia club's people
 *
 * Owner: P12 mafia mobs. Do not edit this file outside P12.
 *
 * The goons, the lieutenants, the club's zone_mobs table, the don's mech (phase one) and the don on foot (phase
 * two), and the don's trophy. Spec section 14.4.
 */
