/**
 * # Bounty hunting: a posting
 *
 * Owner: P5 board. Do not edit this file outside P5.
 *
 * What it owns: /datum/criminal_bounty's life: hunting and abandoning, claimants, closing (with
 * notices to every hunter and cleanup of the criminal, its companions and its decoys), and
 * relisting a bounty at a new site (spec sections 1 and 6).
 *
 * The posting's vars are declared in bounty_types.dm and nowhere else; a var only P5 uses goes
 * here with a `board_` prefix. The procs below start as P0 stubs.
 */

/**
 * Closes the posting for `reason` (BOUNTY_CLOSE_*), won by `winner` when a ship turned it in: tells
 * every hunter, cleans up the criminal, its companions and decoys, and sends
 * COMSIG_BOUNTY_POSTING_CLOSED.
 *
 * P0 stub: only marks it closed.
 */
/datum/criminal_bounty/proc/close(reason, obj/structure/overmap/ship/winner)
	status = BOUNTY_POSTING_CLOSED

/**
 * Takes the bounty off its site and lists it again somewhere else after a while, for `reason`
 * (shown to hunters): the fugitive slipped away, or its body was lost.
 *
 * P0 stub: nothing happens.
 */
/datum/criminal_bounty/proc/relist(reason)
	return
