/**
 * # Bounty lairs: the framework
 *
 * Owner: P10 lairs. Do not edit this file outside P10.
 *
 * Kill-only postings, lair ruins spawned per posting (the drug run's spawn_lab_ruin pattern), gates that open when
 * a lair's gatekeepers die, and the lich kill bounty on GLOB.lich_lair. Spec section 14.1-14.3.
 */
