/**
 * # Bounty hunting: what criminals are doing when found
 *
 * Owner: P3 AI. Do not edit this file outside P3.
 *
 * What it owns: the idle activities (spec section 3): bar, chat, trade, explore, loot and camp
 * (BOUNTY_ACTIVITY_*), each with real objects, and the blended-in idle routine the fugitive and
 * its decoys share at a trader outpost.
 *
 * The shared vars are declared in bounty_types.dm and nowhere else; a var only P3 uses goes here
 * with an `ai_` prefix. The procs below start as P0 stubs.
 */

/**
 * Sets what they are doing until a hunter turns up: `kind` is a BOUNTY_ACTIVITY_*, `anchor` the
 * thing it happens at (a stool, a counter, a trader, a loot crate, the camp), or null.
 *
 * P0 stub: nothing happens.
 */
/mob/living/basic/bounty_criminal/proc/start_activity(kind, atom/anchor)
	return
