/**
 * # Outpost prison: bounty prisoners
 *
 * Owner: P7 prison (bounty hunting). Owns this file, voidcrew/_DEFINES/outpost_prison_bounty.dm, the
 * bounty badge in tgui/packages/tgui/interfaces/OutpostPrison.tsx, the bounty block in
 * OutpostManipulator.tsx and the tests in
 * voidcrew/modules/unit_tests/voidcrew_outpost_prison_bounty.dm. Do not edit this file outside P7.
 *
 * What it owns (spec section 8): the prisoner pool (GLOB.bounty_prisoner_pool) and the intake
 * picker; rebuilding a caught criminal as a prisoner from their record; their danger in the wing
 * by tier; what they earn the outpost; closing their record on every way out; keeping Kessler's
 * experiments off them; the warden roster badge, the examine line and the admin block.
 *
 * The prison calls in here from one-line hooks in its own files (P0), each a stub below that keeps
 * the prison exactly as it was: admit_next() takes a record from the pool; a prisoner's
 * Initialize(mapload, record) applies it; pay, blows, mood, threats, riots, tension, breakouts and
 * cuffing ask the helpers below; every way a prisoner leaves closes their record. Records, the
 * prisoner's `bounty_record` and the shared enums are declared elsewhere (bounty_types.dm,
 * outpost_prison_prisoner.dm, voidcrew/_DEFINES/bounties.dm); a var only P7 uses goes here with a
 * `prison_` prefix.
 *
 * The prisoner procs here are new procs, never overrides of the prisoner's own: this file is
 * included before outpost_prison_prisoner.dm, so an override here would run inside that file's
 * definition, or not at all.
 */

// ===== THE POOL =====

/**
 * A criminal caught alive joins the pool, up to BOUNTY_POOL_CAP (the oldest unreserved record is
 * dropped at the cap), reserved for the capturing crew's own running prison if it has one.
 * Returns TRUE if it was added.
 *
 * P0 stub: adds it to the list.
 */
/proc/bounty_pool_add(datum/bounty_record/record)
	if(!record)
		return FALSE
	GLOB.bounty_prisoner_pool |= record
	return TRUE

/**
 * The record `prison`'s next ordinary arrival is rebuilt from, taken out of the pool: first one
 * reserved for this prison, then the oldest one free to go anywhere. Null with nothing to take, and
 * the arrival is an ordinary prisoner.
 *
 * P0 stub: never takes one.
 */
/proc/bounty_pool_take(datum/outpost_prison/prison)
	return null

// ===== A PRISONER FROM A RECORD =====

/**
 * Before the prisoner's Initialize() calls ..(): the body their record says (gender, and health by
 * tier), so tg sizes max_stamina from the right maxHealth.
 *
 * P0 stub: nothing changes.
 */
/mob/living/basic/outpost_prisoner/proc/apply_bounty_body(datum/bounty_record/record)
	return

/**
 * At the end of the prisoner's Initialize(), before their look is built: who their record says
 * they are (name, "wanted for" crime, personality by archetype, arriving as hurt as they were
 * caught). Their look comes from build_look(), which dresses them in the record's face.
 *
 * P0 stub: nothing changes.
 */
/mob/living/basic/outpost_prisoner/proc/apply_bounty_record(datum/bounty_record/record)
	return

/**
 * `prisoner` is leaving the wing, or has died: closes their bounty record with `status`
 * (BOUNTY_RECORD_*). The first close decides the status; later calls for the same record change
 * nothing (a release is followed by forget(), for one). A closed record never returns to the pool.
 *
 * P0 stub: nothing happens.
 */
/proc/close_bounty_record(mob/living/basic/outpost_prisoner/prisoner, status)
	return

/**
 * Why Kessler's experiments refuse `prisoner`, or null: a bounty prisoner's identity would be
 * lost.
 *
 * P0 stub: never refuses.
 */
/proc/bounty_experiment_refusal(mob/living/basic/outpost_prisoner/prisoner)
	return null

// ===== PAY =====

/// What `prisoner` earns the treasury (stipend, pay rate and release bonus) as a multiple of an ordinary prisoner's. P0 stub: 1.
/datum/outpost_prison/proc/bounty_pay_mult(mob/living/basic/outpost_prisoner/prisoner)
	return 1

// ===== DANGER =====

/// Multiplier on their punches and shiv blows (update_melee() and strike()). P0 stub: 1.
/mob/living/basic/outpost_prisoner/proc/bounty_damage_mult()
	return 1

/// Multiplier on their mood losses (mood_scale()). P0 stub: 1.
/mob/living/basic/outpost_prisoner/proc/bounty_mood_scale()
	return 1

/// Mood points added to the line below which they square up to staff (threat_mood_for() and threat_mood_ceiling()). P0 stub: 0.
/mob/living/basic/outpost_prisoner/proc/bounty_threat_bonus()
	return 0

/// Mood points added to the line below which they join a riot (riot_join_bonus()). P0 stub: 0.
/mob/living/basic/outpost_prisoner/proc/bounty_riot_bonus()
	return 0

/// Multiplier on the damage their blows do to the wing's ways out (hit_exit()). P0 stub: 1.
/mob/living/basic/outpost_prisoner/proc/bounty_breakout_mult()
	return 1

/// Multiplier on how long cuffing them takes (cuff_time()). P0 stub: 1.
/mob/living/basic/outpost_prisoner/proc/bounty_cuff_mult()
	return 1

/// Tension the wing's bounty prisoners add, such as a Most Wanted ringleader (compute_tension()). P0 stub: 0.
/datum/outpost_prison/proc/bounty_tension()
	return 0

/// A few words each on how the bounty prisoners stir the yard up, for the restless log line (restless_causes()). P0 stub: none.
/datum/outpost_prison/proc/bounty_restless_causes()
	return list()

// ===== CONSOLES =====

/// The roster row's "bounty" entry for the warden console: the badge's tier and multiplier, or null for an ordinary prisoner. P0 stub: null.
/datum/outpost_prison/proc/bounty_roster_badge(mob/living/basic/outpost_prisoner/prisoner)
	return null

/// An examine sentence ("Wanted: Most Wanted. Brought in by the Meridian."), or null (examine_extra_lines()). P0 stub: null.
/datum/outpost_prison/proc/bounty_examine(mob/living/basic/outpost_prisoner/prisoner, mob/user)
	return null

/// The admin panel's "bounty" block in the extras (extras_admin_payload()). P0 stub: an empty list.
/datum/outpost_prison/proc/bounty_admin_payload()
	return list()

/// An admin action for bounty prisoners: a line for the admin log, or null when it isn't one (extras_admin_act()). P0 stub: null.
/datum/outpost_prison/proc/bounty_admin_act(action, list/params, mob/user)
	return null
