/**
 * Bounty lairs: P12 mafia mobs' tests, for voidcrew/modules/bounties/bounty_lair_mafia.dm.
 *
 * Owner: P12 mafia mobs. Do not edit this file outside that package. Fork defines are included after the
 * tests, so a test uses the literal value with a comment naming the define. Every test calls the mobs' procs
 * directly with them already in place; none waits on a timer or an AI walk.
 */

/// Shared helpers; not a test itself
/datum/unit_test/voidcrew_bounty_lair_mafia
	abstract_type = /datum/unit_test/voidcrew_bounty_lair_mafia
	/// Test hunters put on SSmobs' list of players, taken off again when the test ends
	var/list/fake_clients = list()

/datum/unit_test/voidcrew_bounty_lair_mafia/Destroy()
	for(var/mob/living/person as anything in fake_clients)
		var/turf/spot = get_turf(person)
		if(spot)
			SSmobs.clients_by_zlevel[spot.z] -= person
	fake_clients = null
	clear_room()
	return ..()

/// The floor `dx`, `dy` tiles from the test room's bottom-left corner (the room is 5x5)
/datum/unit_test/voidcrew_bounty_lair_mafia/proc/spot(dx, dy)
	return locate(run_loc_floor_bottom_left.x + dx, run_loc_floor_bottom_left.y + dy, run_loc_floor_bottom_left.z)

/// A hunter at `where`: a human with a mind, as a player would be. `as_client` puts them on SSmobs' list of players.
/datum/unit_test/voidcrew_bounty_lair_mafia/proc/hunter_at(turf/where, as_client = FALSE)
	var/mob/living/carbon/human/consistent/hunter = allocate(/mob/living/carbon/human/consistent, where)
	hunter.mind_initialize()
	if(as_client)
		SSmobs.clients_by_zlevel[where.z] += hunter
		fake_clients += hunter
	return hunter

/// Clears what the club leaves behind in the test room: shots in flight, corpses, wrecks, rings
/datum/unit_test/voidcrew_bounty_lair_mafia/proc/clear_room()
	for(var/turf/spot as anything in block(run_loc_floor_bottom_left, run_loc_floor_top_right))
		for(var/obj/projectile/stray in spot)
			qdel(stray)
		for(var/obj/structure/bounty_mafia_wreck/wreck in spot)
			qdel(wreck)
		for(var/obj/item/bounty_proof/proof in spot)
			qdel(proof)
		for(var/mob/living/carbon/human/corpse in spot)
			if(corpse.stat == DEAD && !(corpse in allocated))
				qdel(corpse)
		for(var/obj/item/stray_item in spot)
			if(!(stray_item in allocated))
				qdel(stray_item)

// ===== THE ROCKET VOLLEY: MARKERS FIRST, NEVER explosion() =====

/datum/unit_test/voidcrew_bounty_lair_mafia/rockets
	var/explosions = 0

/datum/unit_test/voidcrew_bounty_lair_mafia/rockets/proc/on_explosion(datum/source)
	SIGNAL_HANDLER
	explosions++

/datum/unit_test/voidcrew_bounty_lair_mafia/rockets/Run()
	var/mob/living/basic/bounty_lair_boss/mafia_mech/mech = allocate(/mob/living/basic/bounty_lair_boss/mafia_mech, spot(0, 2))
	var/mob/living/carbon/human/consistent/hunter = hunter_at(spot(4, 2))
	TEST_ASSERT(!ispath(mech.mech_rocket_type, /obj/projectile/bullet/rocket), "The mech fires tg's rocket, which calls explosion()")
	TEST_ASSERT(ispath(mech.mech_rocket_type, /obj/projectile/bullet/bounty_mafia_rocket), "The mech doesn't fire the club's rocket")
	RegisterSignal(SSdcs, COMSIG_GLOB_EXPLOSION, PROC_REF(on_explosion))

	// The lock-on: a marker under the hunter, the mech holding still, and nobody hurt yet
	var/serial = mech.mech_start_rockets(list(hunter))
	TEST_ASSERT(serial, "The volley didn't start")
	TEST_ASSERT_EQUAL(mech.mech_busy, "rockets", "The mech isn't locking on")
	TEST_ASSERT(HAS_TRAIT(mech, TRAIT_IMMOBILIZED), "The mech can walk during the lock-on")
	TEST_ASSERT_NOTNULL(locate(/obj/effect/temp_visual/bounty_mafia_mark) in get_turf(hunter), "No lock-on marker under the hunter")
	TEST_ASSERT_EQUAL(hunter.getBruteLoss(), 0, "The volley hurt someone before the lock-on was over")
	TEST_ASSERT(!mech.mech_start_rockets(list(hunter)), "A second volley started during the lock-on")

	// The launch: one rocket per marker, the markers gone
	var/list/rockets = mech.mech_fire_rockets(serial)
	TEST_ASSERT_EQUAL(length(rockets), 1, "Not one rocket per marker")
	TEST_ASSERT_NULL(mech.mech_busy, "The mech is still busy after the launch")
	TEST_ASSERT_NULL(locate(/obj/effect/temp_visual/bounty_mafia_mark) in get_turf(hunter), "The marker outlived the lock-on")
	var/obj/projectile/bullet/bounty_mafia_rocket/rocket = rockets[1]
	TEST_ASSERT(istype(rocket, /obj/projectile/bullet/bounty_mafia_rocket), "The launch fired something else")
	TEST_ASSERT(!istype(rocket, /obj/projectile/bullet/rocket), "The launch fired tg's rocket")
	TEST_ASSERT_EQUAL(rocket.rocket_target, get_turf(hunter), "The rocket isn't aimed at the marker")

	// It lands on the marker: 60 brute and a knockdown (BOUNTY_MECH_ROCKET_DAMAGE), once a volley
	var/turf/marker_turf = get_turf(hunter)
	var/list/volley = rocket.rocket_volley
	var/list/hit = rocket.rocket_detonate(marker_turf)
	TEST_ASSERT(hunter in hit, "The rocket missed the hunter standing on the marker")
	var/first = hunter.getBruteLoss()
	TEST_ASSERT_EQUAL(first, 60, "The rocket didn't do 60 brute to an unarmoured hunter") // BOUNTY_MECH_ROCKET_DAMAGE
	TEST_ASSERT(hunter.IsKnockdown(), "The rocket didn't knock the hunter down")
	TEST_ASSERT(QDELETED(rocket), "The rocket outlived its burst")
	var/obj/projectile/bullet/bounty_mafia_rocket/second = new(spot(1, 2))
	second.rocket_volley = volley
	second.rocket_detonate(marker_turf)
	TEST_ASSERT_EQUAL(hunter.getBruteLoss(), first, "A second rocket of one volley hit the same hunter")

	// A marker the hunter stepped off hurts nobody
	var/obj/projectile/bullet/bounty_mafia_rocket/empty = new(spot(1, 2))
	TEST_ASSERT(!length(empty.rocket_detonate(spot(2, 4))), "A rocket on an empty marker hit someone")

	// No real explosion: the floor is still a floor, and explosion() never went off
	TEST_ASSERT(isfloorturf(marker_turf), "The rocket changed the floor")
	TEST_ASSERT_EQUAL(explosions, 0, "A rocket called explosion()")
	UnregisterSignal(SSdcs, COMSIG_GLOB_EXPLOSION)

// ===== THE LMG: A RED CONE FIRST =====

/datum/unit_test/voidcrew_bounty_lair_mafia/lmg

/datum/unit_test/voidcrew_bounty_lair_mafia/lmg/Run()
	var/mob/living/basic/bounty_lair_boss/mafia_mech/mech = allocate(/mob/living/basic/bounty_lair_boss/mafia_mech, spot(0, 2))
	var/mob/living/carbon/human/consistent/hunter = hunter_at(spot(4, 2))

	var/serial = mech.mech_start_lmg(hunter)
	TEST_ASSERT(serial, "The machine gun didn't spin up")
	TEST_ASSERT_EQUAL(mech.mech_busy, "lmg_windup", "The machine gun didn't wind up first")
	TEST_ASSERT(HAS_TRAIT(mech, TRAIT_IMMOBILIZED), "The mech can walk during the spin-up")
	var/marked = 0
	for(var/dx in 1 to 4)
		if(locate(/obj/effect/temp_visual/bounty_mafia_mark) in spot(dx, 2))
			marked++
	TEST_ASSERT(marked >= 3, "The red cone doesn't cover the line to the hunter ([marked] of 4 tiles)")
	TEST_ASSERT_EQUAL(hunter.getBruteLoss(), 0, "The machine gun hurt someone during its spin-up")

	var/fire_serial = mech.mech_fire_lmg(serial)
	TEST_ASSERT(fire_serial, "The burst didn't start when the spin-up ended")
	TEST_ASSERT_EQUAL(mech.mech_busy, "lmg_fire", "The mech isn't firing")
	TEST_ASSERT_NULL(mech.mech_telegraphs, "The cone outlived the spin-up")
	TEST_ASSERT(!mech.mech_start_rockets(list(hunter)), "A volley started during the burst")

	// Cut short: nothing more fires
	mech.mech_interrupt()
	TEST_ASSERT_NULL(mech.mech_busy, "The mech is still busy after being cut short")
	TEST_ASSERT_NULL(mech.mech_lmg_round(fire_serial), "A round fired after the burst was cut short")
	clear_room()

	// Never at someone who is down
	mech.mech_next_ability_at = 0
	// Suffocation, not brute: brute lands on one random limb, which caps it
	hunter.adjustOxyLoss(150)
	TEST_ASSERT(hunter.stat != CONSCIOUS, "The hunter didn't go down")
	TEST_ASSERT(!mech.mech_start_lmg(hunter), "The machine gun spun up on a downed hunter")
	TEST_ASSERT(!mech.mech_start_rockets(list(hunter)), "The volley locked on to a downed hunter")

// ===== POSSE HEALTH =====

/datum/unit_test/voidcrew_bounty_lair_mafia/posse

/datum/unit_test/voidcrew_bounty_lair_mafia/posse/Run()
	var/mob/living/basic/bounty_lair_boss/mafia_mech/mech = allocate(/mob/living/basic/bounty_lair_boss/mafia_mech, spot(2, 2))
	TEST_ASSERT(!ispath(mech.type, /mob/living/basic/boss), "The mech is a megafauna boss")
	TEST_ASSERT_EQUAL(mech.maxHealth, 350, "The mech doesn't start at its one-hunter health") // BOUNTY_MECH_HEALTH_1
	TEST_ASSERT_EQUAL(mech.damage_coeff[BRUTE], 0.6, "The mech's brute armour is wrong") // BOUNTY_MECH_BRUTE_MOD
	TEST_ASSERT_EQUAL(mech.damage_coeff[BURN], 0.8, "The mech's burn armour is wrong") // BOUNTY_MECH_BURN_MOD
	TEST_ASSERT_EQUAL(mech.damage_coeff[STAMINA], 0, "The mech takes stamina damage")
	TEST_ASSERT(HAS_TRAIT(mech, "no_containment"), "The mech can be bagged") // TRAIT_NO_CONTAINMENT

	var/list/hunters = list()
	for(var/i in 1 to 5)
		hunters += hunter_at(spot(i - 1, 0))
	TEST_ASSERT(mech.mech_engage(hunters[1]), "The first hunter didn't join the posse")
	TEST_ASSERT_EQUAL(mech.maxHealth, 350, "One hunter changed the mech's health")
	mech.adjust_health(100)
	TEST_ASSERT_EQUAL(mech.health, 250, "The mech didn't take the damage")
	TEST_ASSERT(mech.mech_engage(hunters[2]), "The second hunter didn't join the posse")
	TEST_ASSERT_EQUAL(mech.maxHealth, 700, "Two hunters didn't raise the mech to 700") // BOUNTY_MECH_HEALTH_2
	TEST_ASSERT_EQUAL(mech.health, 600, "The mech's damage didn't carry over when its health rose")
	TEST_ASSERT(!mech.mech_engage(hunters[2]), "The same hunter joined twice")
	mech.mech_engage(hunters[3])
	TEST_ASSERT_EQUAL(mech.maxHealth, 1050, "Three hunters didn't raise the mech to 1050") // BOUNTY_MECH_HEALTH_3
	mech.mech_engage(hunters[4])
	TEST_ASSERT_EQUAL(mech.maxHealth, 1400, "Four hunters didn't raise the mech to 1400") // BOUNTY_MECH_HEALTH_4
	mech.mech_engage(hunters[5])
	TEST_ASSERT_EQUAL(mech.maxHealth, 1400, "A fifth hunter raised the mech past its 4+ health")

// ===== THE EMP STALL =====

/datum/unit_test/voidcrew_bounty_lair_mafia/emp

/datum/unit_test/voidcrew_bounty_lair_mafia/emp/Run()
	var/mob/living/basic/bounty_lair_boss/mafia_mech/mech = allocate(/mob/living/basic/bounty_lair_boss/mafia_mech, spot(0, 2))
	var/mob/living/carbon/human/consistent/hunter = hunter_at(spot(4, 2))
	var/serial = mech.mech_start_rockets(list(hunter))
	TEST_ASSERT(serial, "The volley didn't start")

	mech.emp_act(EMP_HEAVY)
	TEST_ASSERT(mech.stat != DEAD, "A heavy EMP killed the mech")
	TEST_ASSERT_EQUAL(mech.mech_busy, "stall", "The EMP didn't stall the mech")
	TEST_ASSERT(abs(mech.health - 332.5) < 0.5, "The EMP didn't take 5% of the mech's health ([mech.health])") // BOUNTY_MECH_EMP_DAMAGE_PERCENT
	TEST_ASSERT_NULL(mech.mech_telegraphs, "The lock-on markers outlived the stall")
	TEST_ASSERT(!length(mech.mech_fire_rockets(serial)), "The stalled volley still fired")

	// A second EMP straight after does nothing
	mech.emp_act(EMP_HEAVY)
	TEST_ASSERT(abs(mech.health - 332.5) < 0.5, "A second EMP straight after the stall hurt the mech ([mech.health])")

// ===== THE RESET =====

/datum/unit_test/voidcrew_bounty_lair_mafia/reset

/datum/unit_test/voidcrew_bounty_lair_mafia/reset/Run()
	var/mob/living/basic/bounty_lair_boss/mafia_mech/mech = allocate(/mob/living/basic/bounty_lair_boss/mafia_mech, spot(2, 2))
	TEST_ASSERT(!mech.mech_check_reset(), "A fresh mech reset")
	mech.mech_engage(hunter_at(spot(0, 0)))
	mech.mech_engage(hunter_at(spot(1, 0)))
	mech.mech_hostile = TRUE
	mech.adjust_health(200)
	TEST_ASSERT_EQUAL(mech.health, 500, "The mech's setup is wrong")

	mech.mech_last_hunter_at = world.time
	TEST_ASSERT(!mech.mech_check_reset(), "The mech reset with a hunter just seen")
	mech.mech_last_hunter_at = world.time - 610 // BOUNTY_MECH_RESET_AFTER, and a second
	TEST_ASSERT(mech.mech_check_reset(), "The mech didn't reset after 60 seconds with nobody about")
	TEST_ASSERT_EQUAL(mech.maxHealth, 350, "The reset didn't go back to the one-hunter health")
	TEST_ASSERT_EQUAL(mech.health, 350, "The reset didn't heal the mech to full")
	TEST_ASSERT(!length(mech.mech_engaged), "The reset kept the posse")
	TEST_ASSERT(!mech.mech_hostile, "The reset kept the mech hostile")

// ===== PHASE TWO: THE WRECK, THE DON, THE RING =====

/datum/unit_test/voidcrew_bounty_lair_mafia/phase_two
	var/list/ejected = list()

/datum/unit_test/voidcrew_bounty_lair_mafia/phase_two/proc/on_ejected(datum/source, mob/living/don)
	SIGNAL_HANDLER
	ejected += don

/datum/unit_test/voidcrew_bounty_lair_mafia/phase_two/Destroy()
	ejected = null
	return ..()

/datum/unit_test/voidcrew_bounty_lair_mafia/phase_two/Run()
	var/datum/criminal_bounty/posting = new
	allocated += posting
	posting.status = "closed" // BOUNTY_POSTING_CLOSED: a bare test posting, with nothing to close when it goes
	posting.record = new /datum/bounty_record
	posting.record.name = "Viktor Sokolov"
	var/mob/living/basic/bounty_lair_boss/mafia_mech/mech = allocate(/mob/living/basic/bounty_lair_boss/mafia_mech, spot(2, 2))
	mech.posting_ref = WEAKREF(posting)
	var/mob/living/carbon/human/consistent/hunter = hunter_at(spot(0, 2))
	var/turf/where = get_turf(mech)
	RegisterSignal(mech, "bounty_mafia_don_ejected", PROC_REF(on_ejected)) // COMSIG_BOUNTY_MAFIA_DON_EJECTED

	mech.death()
	TEST_ASSERT(QDELETED(mech), "The mech outlived its death")
	var/obj/structure/bounty_mafia_wreck/wreck = locate() in where
	TEST_ASSERT_NOTNULL(wreck, "The mech left no wreck")
	TEST_ASSERT(!istype(wreck, /obj/structure/mecha_wreckage), "The wreck can be salvaged")
	TEST_ASSERT(wreck.density, "The wreck is no cover")
	var/mob/living/basic/bounty_lair_boss/mafia_don/don = locate() in range(1, where)
	TEST_ASSERT_NOTNULL(don, "The don didn't climb out")
	allocated += don
	TEST_ASSERT(!ispath(don.type, /mob/living/basic/boss), "The don is a megafauna boss")
	TEST_ASSERT(don in ejected, "The mech didn't announce the don")
	TEST_ASSERT_EQUAL(don.posting_ref?.resolve(), posting, "The don didn't keep the mech's posting")
	TEST_ASSERT_EQUAL(don.name, "Viktor Sokolov", "The don isn't named for his posting")
	TEST_ASSERT_EQUAL(don.maxHealth, 150, "The don's health is wrong") // BOUNTY_DON_HEALTH
	TEST_ASSERT_EQUAL(don.don_busy, "stagger", "The don isn't dazed as he climbs out")
	TEST_ASSERT_EQUAL(don.don_wreck_ref?.resolve(), wreck, "The don doesn't know his wreck")

	// Kill-only: the cuffs are refused
	var/obj/item/restraints/handcuffs/cuffs = allocate(/obj/item/restraints/handcuffs, get_turf(hunter))
	TEST_ASSERT_EQUAL(don.item_interaction(hunter, cuffs), ITEM_INTERACT_BLOCKING, "The don could be cuffed")

	// His death drops the ring, with the posting and its record on it
	var/turf/don_spot = get_turf(don)
	don.death()
	TEST_ASSERT(QDELETED(don), "The don outlived his death")
	var/obj/item/bounty_proof/trophy/mafia_don/ring = locate() in don_spot
	TEST_ASSERT_NOTNULL(ring, "The don dropped no ring")
	TEST_ASSERT_EQUAL(ring.posting_ref?.resolve(), posting, "The ring doesn't carry the posting")
	TEST_ASSERT_EQUAL(ring.record, posting.record, "The ring doesn't carry the record")
	TEST_ASSERT_EQUAL(ring.icon_state, "signet_ring", "The ring doesn't look like a ring")

// ===== LIEUTENANTS =====

/datum/unit_test/voidcrew_bounty_lair_mafia/lieutenants
	var/deaths = 0

/datum/unit_test/voidcrew_bounty_lair_mafia/lieutenants/proc/on_death(datum/source)
	SIGNAL_HANDLER
	deaths++

/datum/unit_test/voidcrew_bounty_lair_mafia/lieutenants/Run()
	// Two plain gatekeepers in one room: one of each
	var/mob/living/basic/trooper/russian/mafia/lieutenant/first = allocate(/mob/living/basic/trooper/russian/mafia/lieutenant, spot(1, 1))
	var/mob/living/basic/trooper/russian/mafia/lieutenant/second = allocate(/mob/living/basic/trooper/russian/mafia/lieutenant, spot(3, 1))
	TEST_ASSERT_EQUAL(first.mafia_lieutenant_role, "tommy", "The first lieutenant isn't Tommy") // BOUNTY_LIEUTENANT_TOMMY
	TEST_ASSERT_EQUAL(second.mafia_lieutenant_role, "brute", "The second lieutenant isn't Brute") // BOUNTY_LIEUTENANT_BRUTE
	TEST_ASSERT_EQUAL(first.maxHealth, 220, "Tommy's health is wrong") // BOUNTY_LIEUTENANT_TOMMY_HEALTH
	TEST_ASSERT_EQUAL(second.maxHealth, 240, "Brute's health is wrong") // BOUNTY_LIEUTENANT_BRUTE_HEALTH
	TEST_ASSERT(istype(first.mafia_gun, /datum/bounty_mafia_gun/tommy), "Tommy has no Tommy gun")
	TEST_ASSERT_NULL(second.mafia_gun, "Brute has a gun")
	for(var/mob/living/basic/trooper/russian/mafia/lieutenant/lieutenant as anything in list(first, second))
		TEST_ASSERT_EQUAL(lieutenant.damage_coeff[BRUTE], 0.8, "[lieutenant] takes full brute") // BOUNTY_LIEUTENANT_DAMAGE_MOD
		TEST_ASSERT_EQUAL(lieutenant.damage_coeff[BURN], 0.8, "[lieutenant] takes full burn")
		RegisterSignal(lieutenant, COMSIG_LIVING_DEATH, PROC_REF(on_death))

	// Their deaths send the ordinary death signal (P10 opens the gate on it)
	first.death()
	second.death()
	TEST_ASSERT_EQUAL(deaths, 2, "A lieutenant's death didn't send COMSIG_LIVING_DEATH")
	TEST_ASSERT(QDELETED(first) && QDELETED(second), "A lieutenant outlived his death")

// ===== THE ROOM SPAWNER =====

/datum/unit_test/voidcrew_bounty_lair_mafia/zone_mobs

/datum/unit_test/voidcrew_bounty_lair_mafia/zone_mobs/Run()
	var/obj/effect/zone_mobs/mafia/probe = new()
	allocated += probe
	for(var/list/table in list(probe.mobs_green, probe.mobs_yellow, probe.mobs_red))
		TEST_ASSERT(length(table), "A mafia zone table is empty")
		for(var/entry in table)
			TEST_ASSERT(ispath(entry, /mob/living/basic/trooper/russian/mafia), "[entry] isn't a club goon")
			TEST_ASSERT(!ispath(entry, /mob/living/basic/trooper/russian/mafia/lieutenant), "[entry] is a lieutenant, which only the gate has")
			TEST_ASSERT(!ispath(entry, /mob/living/basic/boss), "[entry] is a megafauna")
	for(var/list/count_range in list(probe.count_green, probe.count_yellow, probe.count_red))
		TEST_ASSERT(count_range[1] >= 3 && count_range[2] <= 5, "A mafia marker spawns outside 3-5 goons")

	// P11's rooms get their own crews
	var/list/casino = bounty_mafia_room_crew("/area/ruin/space/has_grav/powered/mafia_club/casino")
	TEST_ASSERT_NOTNULL(casino, "The casino has no crew")
	TEST_ASSERT_EQUAL(casino[/mob/living/basic/trooper/russian/mafia/pistol], 2, "The casino's pistols are wrong")
	TEST_ASSERT_EQUAL(casino[/mob/living/basic/trooper/russian/mafia], 2, "The casino's knives are wrong")
	TEST_ASSERT_EQUAL(casino[/mob/living/basic/trooper/russian/mafia/smg], 1, "The casino's SMGs are wrong")
	var/list/office = bounty_mafia_room_crew("/area/ruin/space/has_grav/powered/mafia_club/back_office")
	TEST_ASSERT_EQUAL(length(office), 1, "The back office's crew is wrong")
	TEST_ASSERT_NULL(bounty_mafia_room_crew("/area/ruin/space/has_grav/powered/mafia_club/garage"), "The arena gets goons")
	TEST_ASSERT_NULL(bounty_mafia_room_crew(/area/misc/testroom), "A room outside the club gets a club crew")

	// Anywhere else, the zone table: 3-5 goons, all on its own floor
	probe.forceMove(spot(2, 2))
	probe.do_spawn(2) // ZONE_YELLOW
	var/count = 0
	var/area/room = get_area(probe)
	for(var/mob/living/basic/trooper/russian/mafia/goon in range(4, probe))
		allocated += goon
		count++
		TEST_ASSERT(!istype(goon, /mob/living/basic/trooper/russian/mafia/lieutenant), "The marker spawned a lieutenant")
		TEST_ASSERT_EQUAL(get_area(goon), room, "A goon spawned outside the marker's room")
	TEST_ASSERT(count >= 3 && count <= 5, "The marker spawned [count] goons, not 3-5")
	qdel(probe)

// ===== GOONS: THE SHOUT, THE DOORWAY, THE DOWNED, NO GUNS =====

/datum/unit_test/voidcrew_bounty_lair_mafia/goons

/datum/unit_test/voidcrew_bounty_lair_mafia/goons/Run()
	var/mob/living/basic/trooper/russian/mafia/pistol/gunman = allocate(/mob/living/basic/trooper/russian/mafia/pistol, spot(0, 0))
	TEST_ASSERT_EQUAL(gunman.maxHealth, 75, "The gunman's health is wrong") // BOUNTY_MOBSTER_PISTOL_HEALTH
	TEST_ASSERT(gunman.speed > 1.5, "The gunman outruns a player")
	var/mob/living/carbon/human/consistent/hunter = hunter_at(spot(4, 0), as_client = TRUE)
	TEST_ASSERT(!gunman.mafia_is_ready(), "The gunman is ready before seeing anyone")

	// He spots the hunter: the room is alerted, and nobody shoots for a second
	TEST_ASSERT_EQUAL(gunman.mafia_find_target(), hunter, "The gunman didn't spot the hunter")
	var/datum/bounty_mafia_room/room = gunman.mafia_room()
	TEST_ASSERT(room?.alerted, "Spotting a hunter didn't alert the room")
	TEST_ASSERT(gunman.mafia_ready_at >= world.time + 10, "The shout gives less than a second") // BOUNTY_MOBSTER_ALERT
	TEST_ASSERT(!gunman.mafia_attack(hunter), "The gunman shot before his shout was over")
	gunman.mafia_ready_at = world.time
	TEST_ASSERT(gunman.mafia_attack(hunter), "The gunman didn't shoot after his shout")
	TEST_ASSERT(!gunman.mafia_gun.ready(), "The pistol has no cooldown")
	clear_room()

	// Never the downed
	// Suffocation, not brute: brute lands on one random limb, which caps it
	hunter.adjustOxyLoss(150)
	TEST_ASSERT(hunter.stat != CONSCIOUS, "The hunter didn't go down")
	TEST_ASSERT(!gunman.mafia_target_ok(hunter), "A goon may go after a downed hunter")
	hunter.fully_heal(HEAL_ALL)
	TEST_ASSERT(gunman.mafia_target_ok(hunter), "The healed hunter isn't fair game again")

	// At most two of a room on one hunter in a doorway
	var/mob/living/basic/trooper/russian/mafia/pistol/second = allocate(/mob/living/basic/trooper/russian/mafia/pistol, spot(0, 1))
	var/mob/living/basic/trooper/russian/mafia/pistol/third = allocate(/mob/living/basic/trooper/russian/mafia/pistol, spot(0, 2))
	gunman.ai_controller.set_blackboard_key(BB_BASIC_MOB_CURRENT_TARGET, hunter)
	second.ai_controller.set_blackboard_key(BB_BASIC_MOB_CURRENT_TARGET, hunter)
	TEST_ASSERT(third.mafia_room_has_space(hunter), "The doorway cap applies to a hunter out in the open")
	var/obj/machinery/door/firedoor/door = allocate(/obj/machinery/door/firedoor, get_turf(hunter))
	TEST_ASSERT(third.mafia_in_doorway(hunter), "A hunter on a door tile isn't in a doorway")
	TEST_ASSERT(!third.mafia_room_has_space(hunter), "A third goon went after a hunter in a doorway")
	qdel(door)

	// They leave no gun behind: the corpse wears club clothes, and that's all
	for(var/goon_type in list(/mob/living/basic/trooper/russian/mafia, /mob/living/basic/trooper/russian/mafia/pistol, /mob/living/basic/trooper/russian/mafia/smg, /mob/living/basic/trooper/russian/mafia/lieutenant/tommy))
		var/turf/where = spot(2, 3)
		var/mob/living/basic/trooper/russian/mafia/goon = allocate(goon_type, where)
		goon.death()
		TEST_ASSERT(QDELETED(goon), "[goon_type] outlived its death")
		var/mob/living/carbon/human/corpse = locate() in where
		TEST_ASSERT_NOTNULL(corpse, "[goon_type] left no corpse")
		TEST_ASSERT_NOTNULL(corpse.w_uniform, "[goon_type]'s corpse isn't dressed")
		for(var/obj/item/gun/gun in where)
			TEST_FAIL("[goon_type] dropped [gun]")
		for(var/obj/item/gun/gun in corpse.get_all_contents())
			TEST_FAIL("[goon_type]'s corpse has [gun]")
		clear_room()
