/**
 * Bounty hunting: P4 bosses's tests, for voidcrew/modules/bounties/bounty_boss.dm and bounty_boss_kits.dm.
 *
 * Owner: P4 bosses. Do not edit this file outside that package. Fork defines are included after the
 * tests, so a test uses the literal value with a comment naming the define. Every test calls the
 * boss's procs directly with the mob already in place; none waits on a timer or an AI walk.
 */

/// Shared helpers; not a test itself
/datum/unit_test/voidcrew_bounty_boss
	abstract_type = /datum/unit_test/voidcrew_bounty_boss
	/// Turfs a test changed, put back to plain floor when it ends
	var/list/turf/changed_turfs = list()

/datum/unit_test/voidcrew_bounty_boss/Destroy()
	for(var/turf/changed as anything in changed_turfs)
		changed.ChangeTurf(/turf/open/floor/iron)
	changed_turfs = null
	return ..()

/// The floor `dx`, `dy` tiles from the test room's bottom-left corner (the room is 5x5)
/datum/unit_test/voidcrew_bounty_boss/proc/spot(dx, dy)
	return locate(run_loc_floor_bottom_left.x + dx, run_loc_floor_bottom_left.y + dy, run_loc_floor_bottom_left.z)

/// Changes `where` to `new_type`, to be put back when the test ends
/datum/unit_test/voidcrew_bounty_boss/proc/change_turf(turf/where, new_type)
	changed_turfs |= where
	return where.ChangeTurf(new_type)

/// A hunter at `where`: a human with a mind, as a player would be
/datum/unit_test/voidcrew_bounty_boss/proc/hunter_at(turf/where)
	var/mob/living/carbon/human/consistent/hunter = allocate(/mob/living/carbon/human/consistent, where)
	hunter.mind_initialize()
	return hunter

/// The ability of `ability_type` that `boss` has
/datum/unit_test/voidcrew_bounty_boss/proc/ability_of(mob/living/basic/bounty_criminal/boss/boss, ability_type)
	return locate(ability_type) in boss.boss_abilities

/// Ready for another ability straight away: no gap, no cooldowns
/datum/unit_test/voidcrew_bounty_boss/proc/ready(mob/living/basic/bounty_criminal/boss/boss)
	boss.boss_next_ability_at = 0
	for(var/datum/action/cooldown/ability as anything in boss.boss_abilities)
		ability.next_use_time = 0

/// Telegraph marks on the tiles around `center`
/datum/unit_test/voidcrew_bounty_boss/proc/marks_near(atom/center, radius = 1)
	. = 0
	for(var/turf/spot as anything in RANGE_TURFS(radius, center))
		for(var/obj/effect/temp_visual/bounty_boss_mark/mark in spot)
			.++

// ===== EACH KIT SPAWNS AND GOES CLEANLY =====

/datum/unit_test/voidcrew_bounty_boss/kits

/datum/unit_test/voidcrew_bounty_boss/kits/Run()
	var/list/kits = list(
		/mob/living/basic/bounty_criminal/boss/juggernaut = "juggernaut", // BOUNTY_KIT_JUGGERNAUT
		/mob/living/basic/bounty_criminal/boss/pyromaniac = "pyromaniac", // BOUNTY_KIT_PYROMANIAC
		/mob/living/basic/bounty_criminal/boss/demolitionist = "demolitionist", // BOUNTY_KIT_DEMOLITIONIST
		/mob/living/basic/bounty_criminal/boss/ghost = "ghost", // BOUNTY_KIT_GHOST
		/mob/living/basic/bounty_criminal/boss/heavy = "heavy", // BOUNTY_KIT_HEAVY
	)
	for(var/kit_type in kits)
		TEST_ASSERT(!ispath(kit_type, /mob/living/basic/boss), "[kit_type] is a megafauna boss, which outposts ban")
		var/mob/living/basic/bounty_criminal/boss/boss = allocate(kit_type)
		TEST_ASSERT_EQUAL(boss.boss_kit, kits[kit_type], "[kit_type] has the wrong kit")
		TEST_ASSERT_EQUAL(length(boss.boss_abilities), 2, "[kit_type] doesn't have its two abilities")
		TEST_ASSERT(istype(boss.ai_controller, /datum/ai_controller/basic_controller/bounty_boss), "[kit_type] doesn't have the boss AI")
		var/list/table = boss.boss_health_table()
		TEST_ASSERT_EQUAL(length(table), 4, "[kit_type] has no health for 1, 2, 3 and 4+ hunters")
		TEST_ASSERT_EQUAL(boss.maxHealth, table[1], "[kit_type] doesn't start at its one-hunter health")
		for(var/i in 2 to 4)
			TEST_ASSERT(table[i] > table[i - 1], "[kit_type]'s health doesn't grow with the posse")
		TEST_ASSERT(!(boss.status_flags & CANSTUN), "A fresh [kit_type] can be stunned")
		TEST_ASSERT(boss.mob_size <= MOB_SIZE_LARGE, "[kit_type] is bigger than large")
		TEST_ASSERT(ispath(boss.boss_kit_outfit(), /datum/outfit/bounty_boss), "[kit_type] has no boss outfit")
		TEST_ASSERT(boss.boss_kit_outfit() != /datum/outfit/bounty_boss, "[kit_type] wears the plain boss outfit")
		var/list/abilities = boss.boss_abilities.Copy()
		qdel(boss)
		TEST_ASSERT(QDELETED(boss), "[kit_type] didn't delete")
		for(var/datum/ability as anything in abilities)
			TEST_ASSERT(QDELETED(ability), "[kit_type]'s [ability.type] outlived it")

	// Fireproof, not laser-proof.
	var/mob/living/basic/bounty_criminal/boss/pyromaniac/pyro = allocate(/mob/living/basic/bounty_criminal/boss/pyromaniac)
	TEST_ASSERT(HAS_TRAIT(pyro, TRAIT_NOFIRE), "The Pyromaniac can be set alight")
	TEST_ASSERT(pyro.damage_coeff[BURN] >= 0.9, "The Pyromaniac shrugs off lasers") // BOUNTY_PYROMANIAC_BURN_MOD

// ===== WIND-UP BEFORE DAMAGE; RESTRAINED OR DOWNED, NOTHING =====

/datum/unit_test/voidcrew_bounty_boss/windup

/datum/unit_test/voidcrew_bounty_boss/windup/Run()
	var/mob/living/basic/bounty_criminal/boss/juggernaut/boss = allocate(/mob/living/basic/bounty_criminal/boss/juggernaut, spot(0, 0))
	var/mob/living/carbon/human/consistent/victim = hunter_at(spot(1, 0))
	var/datum/action/cooldown/mob_cooldown/bounty_boss/slam/slam = ability_of(boss, /datum/action/cooldown/mob_cooldown/bounty_boss/slam)
	TEST_ASSERT_NOTNULL(slam, "The Juggernaut has no slam")

	TEST_ASSERT(slam.Trigger(target = victim), "The slam didn't start")
	TEST_ASSERT_EQUAL(boss.boss_busy, "windup", "The slam didn't wind up first")
	TEST_ASSERT(HAS_TRAIT(boss, TRAIT_IMMOBILIZED), "The boss can move while winding up")
	TEST_ASSERT(length(slam.telegraphs), "The slam showed no telegraph")
	TEST_ASSERT(marks_near(boss) >= 4, "The slam didn't mark the floor around the boss")
	TEST_ASSERT_EQUAL(victim.getBruteLoss(), 0, "The slam hurt someone before its wind-up was over")
	TEST_ASSERT(slam.finish_windup(slam.pending_serial), "The slam didn't land when its wind-up ended")
	TEST_ASSERT(victim.getBruteLoss() > 0, "The slam hurt nobody next to the boss")
	TEST_ASSERT_NULL(boss.boss_busy, "The boss is still busy after the slam")
	TEST_ASSERT(!HAS_TRAIT(boss, TRAIT_IMMOBILIZED), "The boss is still stuck after the slam")
	TEST_ASSERT_EQUAL(marks_near(boss), 0, "The slam's telegraph outlived its wind-up")

	var/mob/living/carbon/human/consistent/second = hunter_at(spot(0, 1))

	// Restrained: it can't start one.
	ready(boss)
	boss.restraints = new /obj/item/restraints/handcuffs(boss)
	TEST_ASSERT(!boss.boss_can_act(), "A cuffed boss can act")
	TEST_ASSERT(!slam.IsAvailable(), "A cuffed boss's ability is available")
	TEST_ASSERT(!slam.Trigger(target = second), "A cuffed boss started an ability")
	TEST_ASSERT_NULL(boss.boss_busy, "A cuffed boss began a wind-up")
	qdel(boss.restraints)
	boss.restraints = null

	// Downed: it can't start one.
	boss.downed = TRUE
	TEST_ASSERT(!slam.IsAvailable(), "A downed boss's ability is available")
	TEST_ASSERT(!slam.Trigger(target = second), "A downed boss started an ability")
	boss.downed = FALSE

	// Cuffed during the wind-up: the telegraph goes and nothing lands.
	ready(boss)
	TEST_ASSERT(slam.Trigger(target = second), "The slam didn't start again")
	var/serial = slam.pending_serial
	SEND_SIGNAL(boss, "bounty_criminal_restrained", null) // COMSIG_BOUNTY_CRIMINAL_RESTRAINED
	TEST_ASSERT(!length(slam.telegraphs), "The telegraph stayed after the boss was cuffed")
	TEST_ASSERT_NULL(boss.boss_busy, "The boss kept winding up after it was cuffed")
	TEST_ASSERT(!slam.finish_windup(serial), "A cancelled wind-up still landed")
	TEST_ASSERT_EQUAL(second.getBruteLoss(), 0, "A cancelled slam hurt someone")

	// Downed during the wind-up, with no signal: the check when it ends still stops it.
	ready(boss)
	TEST_ASSERT(slam.Trigger(target = second), "The slam didn't start a third time")
	boss.downed = TRUE
	TEST_ASSERT(!slam.finish_windup(slam.pending_serial), "A downed boss's wind-up landed")
	TEST_ASSERT_EQUAL(second.getBruteLoss(), 0, "A downed boss's slam hurt someone")
	boss.downed = FALSE

// ===== TIRED BELOW 40% =====

/datum/unit_test/voidcrew_bounty_boss/tired

/datum/unit_test/voidcrew_bounty_boss/tired/Run()
	var/mob/living/basic/bounty_criminal/boss/heavy/heavy = allocate(/mob/living/basic/bounty_criminal/boss/heavy, spot(0, 0))
	TEST_ASSERT(!heavy.boss_tired, "A fresh boss is tired")
	TEST_ASSERT(!(heavy.status_flags & (CANSTUN | CANKNOCKDOWN)), "A fresh boss can be stunned or knocked down")
	// BOUNTY_HEAVY_STAMINA_FRESH 0.15 against BOUNTY_HEAVY_STAMINA 180, as max_stamina is 100
	TEST_ASSERT(abs(heavy.damage_coeff[STAMINA] - 0.15 * 100 / 180) < 0.001, "A fresh Heavy's stamina coefficient is [heavy.damage_coeff[STAMINA]]")
	var/fresh_speed = heavy.speed

	// Down to 38%, under BOUNTY_BOSS_TIRED_BELOW (40)
	heavy.adjustBruteLoss(heavy.maxHealth * 0.62, forced = TRUE)
	TEST_ASSERT(heavy.boss_tired, "A boss at [heavy.health]/[heavy.maxHealth] isn't tired")
	TEST_ASSERT(heavy.status_flags & CANSTUN, "A tired boss can't be stunned")
	TEST_ASSERT(heavy.status_flags & CANKNOCKDOWN, "A tired boss can't be knocked down")
	// BOUNTY_BOSS_STAMINA_TIRED 1 against BOUNTY_HEAVY_STAMINA 180
	TEST_ASSERT(abs(heavy.damage_coeff[STAMINA] - 100 / 180) < 0.001, "A tired Heavy's stamina coefficient is [heavy.damage_coeff[STAMINA]]")
	TEST_ASSERT(abs(heavy.speed - (fresh_speed + 0.3)) < 0.001, "A tired boss isn't slower") // BOUNTY_BOSS_TIRED_SLOWDOWN
	TEST_ASSERT_EQUAL(heavy.boss_cooldown_mult(), 1.5, "A tired boss's cooldowns don't stretch") // BOUNTY_BOSS_TIRED_COOLDOWN_MULT
	heavy.adjustStaminaLoss(200)
	TEST_ASSERT(heavy.has_status_effect(/datum/status_effect/incapacitating/stamcrit), "Stamina weapons don't put a tired boss down")
	TEST_ASSERT(!heavy.boss_can_act(), "A stamina-crit boss can still act")

	// Fresh, stamina weapons can't put it down.
	var/mob/living/basic/bounty_criminal/boss/juggernaut/fresh = allocate(/mob/living/basic/bounty_criminal/boss/juggernaut, spot(2, 0))
	fresh.adjustStaminaLoss(1000)
	TEST_ASSERT(!fresh.has_status_effect(/datum/status_effect/incapacitating/stamcrit), "Stamina weapons put a fresh boss down")

	// Healed back over the line, it is fresh again.
	var/mob/living/basic/bounty_criminal/boss/juggernaut/healed = allocate(/mob/living/basic/bounty_criminal/boss/juggernaut, spot(4, 0))
	healed.adjustBruteLoss(healed.maxHealth * 0.7, forced = TRUE)
	TEST_ASSERT(healed.boss_tired, "The boss didn't tire")
	healed.adjustBruteLoss(-healed.maxHealth, forced = TRUE)
	TEST_ASSERT(!healed.boss_tired, "A healed boss is still tired")
	TEST_ASSERT(!(healed.status_flags & CANSTUN), "A healed boss can still be stunned")

// ===== WHAT IT MAY BREAK =====

/datum/unit_test/voidcrew_bounty_boss/structures

/datum/unit_test/voidcrew_bounty_boss/structures/Run()
	var/mob/living/basic/bounty_criminal/boss/juggernaut/boss = allocate(/mob/living/basic/bounty_criminal/boss/juggernaut, spot(0, 0))
	var/turf/middle = spot(2, 2)
	change_turf(middle, /turf/closed/wall)
	TEST_ASSERT(boss.boss_may_break(middle), "The boss may not break a plain interior wall")

	// Its wall budget spent: no.
	boss.boss_walls_left = 0
	TEST_ASSERT(!boss.boss_may_break(middle), "The boss may break a wall with no budget left")
	boss.boss_walls_left = 2 // BOUNTY_BOSS_WALL_BUDGET

	// Off its site: no.
	boss.site_bounds = list(run_loc_floor_bottom_left.x, run_loc_floor_bottom_left.y, run_loc_floor_bottom_left.x + 1, run_loc_floor_bottom_left.y + 1, run_loc_floor_bottom_left.z)
	TEST_ASSERT(!boss.boss_may_break(middle), "The boss may break a wall off its site")
	TEST_ASSERT(!boss.boss_environment_allowed(middle), "The boss may damage things off its site")
	boss.site_bounds = null

	// Space on its far side: never.
	var/turf/beside = spot(3, 2)
	change_turf(beside, /turf/open/space/basic)
	TEST_ASSERT(!boss.boss_may_break(middle), "The boss may break a wall with space beside it")
	change_turf(beside, /turf/open/floor/iron)

	// Reinforced: no.
	change_turf(middle, /turf/closed/wall/r_wall)
	TEST_ASSERT(!boss.boss_may_break(middle), "The boss may break a reinforced wall")

	// It breaks a plain one to a girder and spends the budget.
	change_turf(middle, /turf/closed/wall)
	TEST_ASSERT(boss.boss_damage_structure(middle, null, list(4)), "The boss didn't break the wall") // BOUNTY_BOSS_ABILITY_STRUCTURE_CAP
	TEST_ASSERT(!isclosedturf(middle), "The wall is still standing")
	TEST_ASSERT_NOTNULL(locate(/obj/structure/girder) in middle, "The broken wall left no girder")
	TEST_ASSERT_EQUAL(boss.boss_walls_left, 1, "Breaking a wall didn't spend the budget")

	// No budget left, and the wall stands.
	change_turf(middle, /turf/closed/wall)
	boss.boss_walls_left = 0
	TEST_ASSERT(!boss.boss_damage_structure(middle, null, list(4)), "The boss broke a wall past its budget")
	TEST_ASSERT(isclosedturf(middle), "A wall past the budget fell")

	// One use of an ability breaks no more than its cap.
	var/obj/structure/table/table = allocate(/obj/structure/table, spot(0, 3))
	TEST_ASSERT(!boss.boss_damage_structure(table, null, list(0)), "An ability past its cap broke a table")
	TEST_ASSERT(!QDELETED(table), "A table past the cap broke")
	TEST_ASSERT(boss.boss_damage_structure(table, null, list(1)), "The boss didn't break the table")
	TEST_ASSERT(QDELETED(table), "The table survived being broken outright")

	// Never anything indestructible, and never machines that aren't doors.
	var/obj/structure/table/tough = allocate(/obj/structure/table, spot(1, 3))
	tough.resistance_flags |= INDESTRUCTIBLE
	TEST_ASSERT(!boss.boss_may_break(tough), "The boss may break an indestructible table")
	var/obj/machinery/light/lamp = allocate(/obj/machinery/light, spot(4, 4))
	TEST_ASSERT(!boss.boss_may_break(lamp), "The boss may break a light fixture")

	// Doors spend the same budget as walls.
	var/obj/machinery/door/airlock/door = allocate(/obj/machinery/door/airlock, spot(4, 2))
	boss.boss_walls_left = 0
	TEST_ASSERT(!boss.boss_may_break(door), "The boss may break a door with no budget left")
	boss.boss_walls_left = 1
	TEST_ASSERT(boss.boss_may_break(door), "The boss may not break an interior door")

// ===== NEVER THE SAME ABILITY TWICE IN A ROW =====

/datum/unit_test/voidcrew_bounty_boss/rotation

/datum/unit_test/voidcrew_bounty_boss/rotation/Run()
	// Two abilities both worth using: they alternate.
	var/mob/living/basic/bounty_criminal/boss/pyromaniac/pyro = allocate(/mob/living/basic/bounty_criminal/boss/pyromaniac, spot(0, 0))
	var/mob/living/carbon/human/consistent/near = hunter_at(spot(2, 0))
	var/last_type
	for(var/i in 1 to 20)
		var/datum/action/cooldown/mob_cooldown/bounty_boss/picked = pyro.boss_choose_ability(near)
		TEST_ASSERT_NOTNULL(picked, "The Pyromaniac picked nothing with both its abilities ready")
		TEST_ASSERT(picked.type != last_type, "The Pyromaniac picked [picked.type] twice in a row")
		last_type = picked.type
		pyro.boss_last_ability = picked.type

	// Starting an ability is what the rotation remembers.
	var/datum/action/cooldown/mob_cooldown/bounty_boss/flamer/flamer = ability_of(pyro, /datum/action/cooldown/mob_cooldown/bounty_boss/flamer)
	TEST_ASSERT(flamer.Trigger(target = near), "The flamer didn't start")
	TEST_ASSERT_EQUAL(pyro.boss_last_ability, flamer.type, "Starting the flamer wasn't remembered")
	pyro.boss_interrupt()
	ready(pyro)
	var/datum/action/cooldown/mob_cooldown/bounty_boss/next = pyro.boss_choose_ability(near)
	TEST_ASSERT(next && next.type != flamer.type, "The flamer came up again straight after the flamer")

	// The rotation as shipped (BOUNTY_BOSS_STRICT_ROTATION FALSE): the last ability repeats only when no other is off cooldown.
	TEST_ASSERT(!pyro.boss_strict_rotation, "The shipped rotation is strict")
	var/datum/action/cooldown/mob_cooldown/bounty_boss/molotov/molotov = ability_of(pyro, /datum/action/cooldown/mob_cooldown/bounty_boss/molotov)
	ready(pyro)
	pyro.boss_last_ability = flamer.type
	molotov.next_use_time = world.time + 100 SECONDS
	var/datum/action/cooldown/mob_cooldown/bounty_boss/again = pyro.boss_choose_ability(near)
	TEST_ASSERT(again && again.type == flamer.type, "The flamer didn't repeat with the molotov on cooldown")
	molotov.next_use_time = 0
	for(var/i in 1 to 10)
		var/datum/action/cooldown/mob_cooldown/bounty_boss/other = pyro.boss_choose_ability(near)
		TEST_ASSERT(other && other.type == molotov.type, "The flamer repeated while the molotov was off cooldown")

	// Only one ability worth using: it repeats; strictly, nothing (the hoarfrost rotation).
	var/mob/living/basic/bounty_criminal/boss/juggernaut/boss = allocate(/mob/living/basic/bounty_criminal/boss/juggernaut, spot(0, 3))
	var/mob/living/carbon/human/consistent/far = hunter_at(spot(3, 3))
	var/datum/action/cooldown/mob_cooldown/bounty_boss/first = boss.boss_choose_ability(far)
	TEST_ASSERT(istype(first, /datum/action/cooldown/mob_cooldown/bounty_boss/charge), "The Juggernaut didn't choose to charge someone three tiles off")
	boss.boss_last_ability = first.type
	TEST_ASSERT_NOTNULL(boss.boss_choose_ability(far), "The rotation won't reuse the only ability ready")
	boss.boss_strict_rotation = TRUE
	TEST_ASSERT_NULL(boss.boss_choose_ability(far), "The strict rotation chose the same ability twice in a row")

// ===== SUMMONED THINGS CLEAN UP =====

/datum/unit_test/voidcrew_bounty_boss/cleanup

/datum/unit_test/voidcrew_bounty_boss/cleanup/Run()
	// Telegraphs go with a cancelled wind-up.
	var/mob/living/basic/bounty_criminal/boss/juggernaut/jugg = allocate(/mob/living/basic/bounty_criminal/boss/juggernaut, spot(2, 2))
	var/mob/living/carbon/human/consistent/beside = hunter_at(spot(3, 2))
	var/datum/action/cooldown/mob_cooldown/bounty_boss/slam/slam = ability_of(jugg, /datum/action/cooldown/mob_cooldown/bounty_boss/slam)
	TEST_ASSERT(slam.Trigger(target = beside), "The slam didn't start")
	TEST_ASSERT(marks_near(jugg), "The slam left no marks")
	jugg.boss_interrupt()
	TEST_ASSERT_EQUAL(marks_near(jugg), 0, "The slam's marks outlived the interrupted wind-up")
	qdel(jugg)
	qdel(beside)

	// Barricades: one from the ability, folding away on its own; a global cap.
	TEST_ASSERT_EQUAL(length(GLOB.bounty_boss_barricades), 0, "Barricades were standing before the test")
	var/mob/living/basic/bounty_criminal/boss/heavy/heavy = allocate(/mob/living/basic/bounty_criminal/boss/heavy, spot(0, 0))
	var/mob/living/carbon/human/consistent/target = hunter_at(spot(4, 0))
	var/datum/action/cooldown/mob_cooldown/bounty_boss/barricade/barricade = ability_of(heavy, /datum/action/cooldown/mob_cooldown/bounty_boss/barricade)
	TEST_ASSERT(barricade.worth_using(target), "The Heavy won't put up a barricade")
	TEST_ASSERT(barricade.Trigger(target = target), "The barricade didn't start")
	TEST_ASSERT(barricade.finish_windup(barricade.pending_serial), "The barricade didn't go up")
	var/obj/structure/barricade/security/bounty_boss/barrier = locate() in spot(1, 0)
	TEST_ASSERT_NOTNULL(barrier, "No barricade in front of the Heavy")
	TEST_ASSERT(barrier in GLOB.bounty_boss_barricades, "The barricade isn't counted")
	barrier.fold_away()
	TEST_ASSERT(QDELETED(barrier), "The barricade didn't fold away")
	TEST_ASSERT_EQUAL(length(GLOB.bounty_boss_barricades), 0, "A folded barricade is still counted")

	var/list/made = list()
	for(var/i in 1 to 9)
		made += new /obj/structure/barricade/security/bounty_boss(spot(i % 5, 4))
	TEST_ASSERT_EQUAL(length(GLOB.bounty_boss_barricades), 8, "The barricade cap didn't hold") // BOUNTY_BOSS_BARRICADE_CAP
	for(var/obj/structure/barricade/security/bounty_boss/extra as anything in made)
		if(!QDELETED(extra))
			qdel(extra)
	TEST_ASSERT_EQUAL(length(GLOB.bounty_boss_barricades), 0, "Deleted barricades are still counted")

	// Barricades a boss keeps: a new one folds up its oldest.
	var/list/mine = list()
	for(var/i in 1 to 3)
		var/obj/structure/barricade/security/bounty_boss/one = new(spot(i, 3))
		mine += one
		barricade.barriers += WEAKREF(one)
	barricade.prune_barriers()
	TEST_ASSERT(QDELETED(mine[1]), "The Heavy's oldest barricade stayed past its limit") // BOUNTY_BOSS_BARRICADES_PER_BOSS
	TEST_ASSERT_EQUAL(length(barricade.barriers), 2, "The Heavy keeps the wrong number of barricades")
	for(var/obj/structure/barricade/security/bounty_boss/kept as anything in mine)
		if(!QDELETED(kept))
			qdel(kept)

	// Fire: it burns who it may, never the boss, and goes out.
	var/mob/living/basic/bounty_criminal/boss/pyromaniac/pyro = allocate(/mob/living/basic/bounty_criminal/boss/pyromaniac, spot(0, 2))
	var/mob/living/carbon/human/consistent/walker = hunter_at(spot(2, 2))
	var/obj/effect/bounty_boss_fire_pool/pool = new(spot(2, 2), list(spot(0, 2), spot(2, 2)), 4 SECONDS, pyro, 10)
	TEST_ASSERT(!QDELETED(pool), "The fire went out at once")
	TEST_ASSERT(pool in GLOB.bounty_boss_fire_pools, "The fire isn't counted")
	TEST_ASSERT(walker.getFireLoss() > 0, "The fire didn't burn someone standing in it")
	TEST_ASSERT(walker.has_status_effect(/datum/status_effect/bounty_boss_burning), "The fire didn't set someone alight")
	TEST_ASSERT_EQUAL(pyro.getFireLoss(), 0, "The Pyromaniac's own fire burned it")
	pool.burn_out()
	TEST_ASSERT(QDELETED(pool), "The fire didn't go out")
	TEST_ASSERT(!(pool in GLOB.bounty_boss_fire_pools), "A fire that went out is still counted")
	walker.remove_status_effect(/datum/status_effect/bounty_boss_burning)
	TEST_ASSERT(!walker.has_status_effect(/datum/status_effect/bounty_boss_burning), "The burning didn't end")

	// A grenade: nothing until its fuse runs out, never its thrower, then gone.
	var/mob/living/basic/bounty_criminal/boss/demolitionist/demo = allocate(/mob/living/basic/bounty_criminal/boss/demolitionist, spot(2, 4))
	var/mob/living/carbon/human/consistent/caught = hunter_at(spot(4, 4))
	var/obj/effect/bounty_boss_explosive/grenade = new(spot(3, 4), demo)
	TEST_ASSERT(grenade in GLOB.bounty_boss_explosives, "The grenade isn't counted")
	TEST_ASSERT_EQUAL(caught.getBruteLoss(), 0, "The grenade hurt someone before its fuse ran out")
	grenade.detonate()
	TEST_ASSERT(caught.getBruteLoss() > 0, "The grenade didn't hurt someone next to it")
	TEST_ASSERT_EQUAL(demo.getBruteLoss(), 0, "The grenade hurt the Demolitionist who threw it")
	TEST_ASSERT(QDELETED(grenade), "The grenade is still there after going off")
	TEST_ASSERT_EQUAL(length(GLOB.bounty_boss_explosives), 0, "A spent grenade is still counted")

// ===== HEALTH GROWS WITH THE POSSE =====

/datum/unit_test/voidcrew_bounty_boss/posse

/datum/unit_test/voidcrew_bounty_boss/posse/Run()
	var/mob/living/basic/bounty_criminal/boss/juggernaut/boss = allocate(/mob/living/basic/bounty_criminal/boss/juggernaut, spot(0, 0))
	var/mob/living/carbon/human/consistent/first = hunter_at(spot(4, 4))
	var/mob/living/carbon/human/consistent/second = hunter_at(spot(3, 4))
	var/mob/living/carbon/human/consistent/third = hunter_at(spot(2, 4))
	// BOUNTY_JUGGERNAUT_HEALTH_1 to _3: 300, 950, 1600
	TEST_ASSERT_EQUAL(boss.maxHealth, 300, "The Juggernaut doesn't start at its one-hunter health")
	TEST_ASSERT(boss.boss_engage(first), "The first hunter didn't join the posse")
	TEST_ASSERT_EQUAL(boss.maxHealth, 300, "One hunter raised the health")
	TEST_ASSERT(!boss.boss_engage(first), "The same hunter joined twice")
	TEST_ASSERT(boss.boss_engage(second), "The second hunter didn't join")
	TEST_ASSERT_EQUAL(boss.maxHealth, 950, "Two hunters didn't raise the health")
	TEST_ASSERT_EQUAL(boss.health, 950, "The raise didn't lift current health")
	boss.adjustBruteLoss(100, forced = TRUE)
	TEST_ASSERT(boss.boss_engage(third), "The third hunter didn't join")
	TEST_ASSERT_EQUAL(boss.maxHealth, 1600, "Three hunters didn't raise the health")
	TEST_ASSERT_EQUAL(boss.health, 1500, "The raise didn't keep the damage already done")

	// Someone with no mind isn't a hunter.
	var/mob/living/carbon/human/consistent/bystander = allocate(/mob/living/carbon/human/consistent, spot(1, 4))
	TEST_ASSERT(!boss.boss_engage(bystander), "A mindless bystander joined the posse")

	// Never lowered.
	boss.boss_engaged.Cut()
	boss.boss_engage(first)
	TEST_ASSERT_EQUAL(boss.maxHealth, 1600, "A smaller posse lowered the health")

	// Confronted: it turns on whoever confronted it, and everyone in sight joins.
	var/mob/living/basic/bounty_criminal/boss/juggernaut/other = allocate(/mob/living/basic/bounty_criminal/boss/juggernaut, spot(0, 2))
	other.on_confronted(first)
	TEST_ASSERT(other.boss_hostile, "A confronted boss didn't turn hostile")
	TEST_ASSERT(WEAKREF(first) in other.grudge, "A confronted boss has no grudge against who confronted it")
	TEST_ASSERT_EQUAL(other.ai_controller?.blackboard[BB_BASIC_MOB_CURRENT_TARGET], first, "A confronted boss isn't going after who confronted it")
	TEST_ASSERT(other.maxHealth >= 950, "The hunters in sight didn't join the confronted boss's posse")

// ===== THE JUGGERNAUT'S CHARGE =====

/datum/unit_test/voidcrew_bounty_boss/charge

/datum/unit_test/voidcrew_bounty_boss/charge/Run()
	var/mob/living/basic/bounty_criminal/boss/juggernaut/boss = allocate(/mob/living/basic/bounty_criminal/boss/juggernaut, spot(0, 0))
	var/obj/structure/table/table = allocate(/obj/structure/table, spot(1, 0))
	var/mob/living/carbon/human/consistent/victim = hunter_at(spot(3, 0))
	var/datum/action/cooldown/mob_cooldown/bounty_boss/charge/charge = ability_of(boss, /datum/action/cooldown/mob_cooldown/bounty_boss/charge)
	TEST_ASSERT(charge.worth_using(victim), "The Juggernaut won't charge someone three tiles off")
	TEST_ASSERT(charge.Trigger(target = victim), "The charge didn't start")
	TEST_ASSERT(length(charge.path) >= 3, "The charge's telegraph line is too short")
	TEST_ASSERT_EQUAL(victim.getBruteLoss(), 0, "The charge hit before its wind-up was over")
	TEST_ASSERT(charge.finish_windup(charge.pending_serial), "The charge didn't go when its wind-up ended")
	// Its first step runs at once; the rest are timed, so step it by hand.
	var/serial = boss.boss_busy_serial
	for(var/i in 1 to 8)
		if(boss.boss_busy != "charge")
			break
		charge.charge_step(serial)
	TEST_ASSERT(QDELETED(table), "The charge didn't smash the table in its way")
	TEST_ASSERT(victim.getBruteLoss() > 0, "The charge didn't hit its target")
	TEST_ASSERT_NULL(boss.boss_busy, "The boss is still charging")
	TEST_ASSERT_EQUAL(get_dist(boss, victim), 1, "The charge didn't end at its target")

// ===== THE GHOST =====

/datum/unit_test/voidcrew_bounty_boss/ghost

/datum/unit_test/voidcrew_bounty_boss/ghost/Run()
	var/mob/living/basic/bounty_criminal/boss/ghost/ghost = allocate(/mob/living/basic/bounty_criminal/boss/ghost, spot(0, 0))
	TEST_ASSERT(ghost.boss_cloak(), "The Ghost didn't cloak")
	ghost.apply_damage(5, BRUTE)
	TEST_ASSERT(!ghost.boss_cloaked, "A hit didn't break the Ghost's cloak")
	TEST_ASSERT(ghost.boss_cloak(), "The Ghost didn't cloak again")
	SEND_SIGNAL(ghost, COMSIG_MOB_FLASHED)
	TEST_ASSERT(!ghost.boss_cloaked, "A flash didn't break the Ghost's cloak")

	// Its cuts bleed, and a couple of them make it break off.
	var/mob/living/carbon/human/consistent/victim = hunter_at(spot(1, 0))
	ghost.boss_cut(victim)
	TEST_ASSERT(victim.has_status_effect(/datum/status_effect/bounty_boss_bleed), "The Ghost's cut didn't bleed")
	ghost.boss_cut(victim)
	TEST_ASSERT(ghost.boss_breakoff_until > world.time, "The Ghost didn't break off after two cuts") // BOUNTY_GHOST_CUTS_BEFORE_BREAKOFF
