/**
 * Bounty hunting: P8 admin's tests, for voidcrew/modules/bounties/bounty_admin.dm.
 *
 * Owner: P8 admin. Do not edit this file outside that package. P0 left a skeleton test here for the
 * package to replace with its own. Fork defines are included after the tests, so a test uses the
 * literal value with a comment naming the define.
 */
/datum/unit_test/voidcrew_bounty_admin_skeleton

/datum/unit_test/voidcrew_bounty_admin_skeleton/Run()
	TEST_ASSERT(ispath(/datum/criminal_bounty), "The posting type is missing")
