/**
 * Bounty hunting: P2 body's tests, for voidcrew/modules/bounties/bounty_criminal.dm and bounty_restraints.dm.
 *
 * Owner: P2 body. Do not edit this file outside that package. Fork defines are included after the
 * tests, so a test uses the literal value with a comment naming the define. Every test drives the
 * body's procs directly with the mob in place; none relies on the AI walking anywhere.
 */

/// Holds the helpers the body tests share
/datum/unit_test/voidcrew_bounty_criminal
	abstract_type = /datum/unit_test/voidcrew_bounty_criminal
	/// How many times each bounty signal was sent in the test
	var/list/signal_counts

/datum/unit_test/voidcrew_bounty_criminal/proc/on_downed(datum/source)
	SIGNAL_HANDLER
	LAZYINITLIST(signal_counts)
	signal_counts["downed"] += 1

/datum/unit_test/voidcrew_bounty_criminal/proc/on_recovered(datum/source)
	SIGNAL_HANDLER
	LAZYINITLIST(signal_counts)
	signal_counts["recovered"] += 1

/datum/unit_test/voidcrew_bounty_criminal/proc/on_restrained(datum/source, mob/user)
	SIGNAL_HANDLER
	LAZYINITLIST(signal_counts)
	signal_counts["restrained"] += 1

/datum/unit_test/voidcrew_bounty_criminal/proc/on_unrestrained(datum/source, mob/user)
	SIGNAL_HANDLER
	LAZYINITLIST(signal_counts)
	signal_counts["unrestrained"] += 1

/// How many times `signal_name` was counted
/datum/unit_test/voidcrew_bounty_criminal/proc/signal_count(signal_name)
	return LAZYACCESS(signal_counts, signal_name) || 0

/// Everything examining `criminal` shows `user`, as one text
/datum/unit_test/voidcrew_bounty_criminal/proc/examine_text(mob/living/basic/bounty_criminal/criminal, mob/user)
	return jointext(criminal.examine(user), "\n")

// ===== THE MERCY RULE =====

/datum/unit_test/voidcrew_bounty_criminal_mercy
	parent_type = /datum/unit_test/voidcrew_bounty_criminal

/datum/unit_test/voidcrew_bounty_criminal_mercy/Run()
	var/mob/living/basic/bounty_criminal/normal/criminal = allocate(__IMPLIED_TYPE__)
	// BOUNTY_NORMAL_HEALTH_WANTED 120; BOUNTY_DOWNED_BELOW 25: the line is 30
	TEST_ASSERT_EQUAL(criminal.maxHealth, 120, "A normal criminal has the wrong health")
	TEST_ASSERT(!criminal.is_downed(), "A fresh criminal is downed")
	criminal.adjustBruteLoss(500)
	TEST_ASSERT_EQUAL(criminal.stat, CONSCIOUS, "One big hit killed a criminal on its feet")
	TEST_ASSERT_EQUAL(criminal.health, 29, "A big hit on a criminal on its feet did not stop 1 under the downed line")
	TEST_ASSERT(criminal.is_downed(), "A criminal at the downed line is not downed")
	TEST_ASSERT_EQUAL(criminal.capture_state(), "downed", "A downed criminal's capture state is wrong") // BOUNTY_STATE_DOWNED
	// Down, the next hit can kill: that is a choice.
	criminal.adjustBruteLoss(500)
	TEST_ASSERT_EQUAL(criminal.stat, DEAD, "A hit on a downed criminal could not kill it")
	TEST_ASSERT_EQUAL(criminal.capture_state(), "dead", "A dead criminal's capture state is wrong") // BOUNTY_STATE_DEAD
	TEST_ASSERT(!QDELETED(criminal), "A dead criminal's body was deleted")

	// Stamina crit counts as standing for the mercy rule.
	var/mob/living/basic/bounty_criminal/meek/runner = allocate(__IMPLIED_TYPE__)
	runner.adjustStaminaLoss(200)
	TEST_ASSERT(runner.has_status_effect(/datum/status_effect/incapacitating/stamcrit), "A meek criminal did not stamina crit")
	runner.adjustBruteLoss(500)
	// BOUNTY_MEEK_HEALTH 80: the line is 20
	TEST_ASSERT_EQUAL(runner.stat, CONSCIOUS, "A big hit killed a criminal in stamina crit")
	TEST_ASSERT_EQUAL(runner.health, 19, "A big hit on a criminal in stamina crit did not stop 1 under the downed line")

	// Small hits add up to the same line and no further.
	var/mob/living/basic/bounty_criminal/normal/chipped = allocate(__IMPLIED_TYPE__)
	for(var/i in 1 to 20)
		chipped.adjustBruteLoss(7)
		if(chipped.is_downed())
			break
	TEST_ASSERT(chipped.is_downed(), "Small hits never downed a criminal")
	TEST_ASSERT(chipped.health > 0 && chipped.health <= 30, "Small hits left a downed criminal at [chipped.health]")

// ===== DOWNED AND GETTING UP =====

/datum/unit_test/voidcrew_bounty_criminal_recovery
	parent_type = /datum/unit_test/voidcrew_bounty_criminal

/datum/unit_test/voidcrew_bounty_criminal_recovery/Run()
	var/mob/living/basic/bounty_criminal/normal/criminal = allocate(__IMPLIED_TYPE__)
	RegisterSignal(criminal, "bounty_criminal_downed", TYPE_PROC_REF(/datum/unit_test/voidcrew_bounty_criminal, on_downed)) // COMSIG_BOUNTY_CRIMINAL_DOWNED
	RegisterSignal(criminal, "bounty_criminal_recovered", TYPE_PROC_REF(/datum/unit_test/voidcrew_bounty_criminal, on_recovered)) // COMSIG_BOUNTY_CRIMINAL_RECOVERED
	var/mob/living/carbon/human/consistent/hunter = allocate(__IMPLIED_TYPE__, get_step(run_loc_floor_bottom_left, EAST))

	criminal.adjustBruteLoss(500)
	TEST_ASSERT_EQUAL(signal_count("downed"), 1, "Going down did not send the downed signal once")
	TEST_ASSERT(HAS_TRAIT(criminal, TRAIT_FLOORED), "A downed criminal is not on the floor")
	TEST_ASSERT(HAS_TRAIT(criminal, TRAIT_INCAPACITATED), "A downed criminal is not incapacitated")
	TEST_ASSERT(HAS_TRAIT(criminal, "bounty_held"), "A downed criminal's AI may still plan") // TRAIT_BOUNTY_HELD
	TEST_ASSERT(HAS_TRAIT(criminal, TRAIT_AI_PAUSED), "A downed criminal's AI is not paused")
	TEST_ASSERT(!criminal.may_attack(hunter), "A downed criminal may still attack")
	TEST_ASSERT_NOTNULL(criminal.body_recovery_timer, "A downed criminal has no recovery clock")

	// Healing raises its health, not its state.
	criminal.adjustBruteLoss(-500)
	TEST_ASSERT_EQUAL(criminal.health, 120, "A downed criminal could not be healed")
	TEST_ASSERT(criminal.is_downed(), "Healing stood a downed criminal up")

	// A stamina hit starts the clock over.
	var/first_clock = criminal.body_recovery_timer
	criminal.adjustStaminaLoss(10)
	TEST_ASSERT(criminal.body_recovery_timer && criminal.body_recovery_timer != first_clock, "A stamina hit did not restart a downed criminal's recovery")

	// Cuffed, it stays down when its time comes, and gets up once the cuffs are off.
	TEST_ASSERT(criminal.body_apply_cuffs(allocate(/obj/item/restraints/handcuffs)), "A downed criminal could not be cuffed")
	criminal.body_stir()
	TEST_ASSERT(criminal.is_downed(), "A cuffed, downed criminal started getting up")
	TEST_ASSERT(!criminal.body_stirring, "A cuffed, downed criminal is stirring")
	TEST_ASSERT(!criminal.body_stand_up(), "A cuffed, downed criminal got up")
	TEST_ASSERT(criminal.body_recovery_due, "A cuffed criminal's recovery did not wait for the cuffs")
	TEST_ASSERT_EQUAL(criminal.capture_state(), "downed", "A cuffed, downed criminal is not downed") // BOUNTY_STATE_DOWNED
	criminal.body_remove_cuffs()
	TEST_ASSERT(criminal.body_stirring, "A downed criminal whose time had come did not stir once uncuffed")
	TEST_ASSERT(criminal.body_stand_up(), "A stirring criminal could not get up")
	TEST_ASSERT(!criminal.is_downed(), "A criminal that got up is still downed")
	TEST_ASSERT_EQUAL(signal_count("recovered"), 1, "Getting up did not send the recovered signal once")
	TEST_ASSERT_EQUAL(criminal.health, 120, "A criminal healed while down did not get up with its health")
	TEST_ASSERT(!HAS_TRAIT(criminal, TRAIT_FLOORED), "A criminal that got up is still on the floor")
	TEST_ASSERT(!HAS_TRAIT(criminal, "bounty_held"), "A criminal that got up is still held") // TRAIT_BOUNTY_HELD
	TEST_ASSERT(!HAS_TRAIT(criminal, TRAIT_AI_PAUSED), "A criminal that got up still has its AI paused")
	TEST_ASSERT(criminal.may_attack(hunter), "A criminal that got up may not fight")

	// Left alone, it gets up at the recovery line.
	var/mob/living/basic/bounty_criminal/normal/other = allocate(__IMPLIED_TYPE__)
	other.adjustBruteLoss(500)
	other.body_stir()
	TEST_ASSERT(other.body_stirring, "A downed criminal did not stir when its time came")
	TEST_ASSERT(other.body_stand_up(), "A downed criminal did not get up")
	// BOUNTY_RECOVER_TO 35: 42 of 120
	TEST_ASSERT_EQUAL(other.health, 42, "A criminal got up with the wrong health")

	// Only mini-bosses rally: stamina does nothing to one that just got up, until the rally ends.
	TEST_ASSERT(!other.body_is_rallying(), "A normal criminal rallies")
	var/mob/living/basic/bounty_criminal/boss/juggernaut/brute = allocate(__IMPLIED_TYPE__)
	brute.adjustBruteLoss(brute.maxHealth * 2)
	TEST_ASSERT(brute.is_downed(), "A mini-boss was not downed")
	TEST_ASSERT(brute.body_stand_up(), "A downed mini-boss did not get up")
	TEST_ASSERT(brute.body_is_rallying(), "A mini-boss that got up is not rallying")
	TEST_ASSERT_NOTNULL(brute.body_rally_timer, "A rallying mini-boss has no end to its rally")
	var/stamina_before = brute.getStaminaLoss()
	brute.adjustStaminaLoss(50)
	TEST_ASSERT_EQUAL(brute.getStaminaLoss(), stamina_before, "A rallying mini-boss took stamina damage")
	brute.body_end_rally()
	TEST_ASSERT(!brute.body_is_rallying(), "A mini-boss's rally did not end")

	// BOUNTY_RECOVER_TIME_MEEK, _NORMAL, _BOSS (60 SECONDS, 75 SECONDS, 45 SECONDS)
	var/mob/living/basic/bounty_criminal/meek/runner = allocate(__IMPLIED_TYPE__)
	TEST_ASSERT_EQUAL(runner.body_recovery_time(), 600, "A meek criminal's recovery time is wrong")
	TEST_ASSERT_EQUAL(other.body_recovery_time(), 750, "A normal criminal's recovery time is wrong")
	TEST_ASSERT_EQUAL(brute.body_recovery_time(), 450, "A mini-boss's recovery time is wrong")

// ===== WORST STATE AND THE STATE ORDER =====

/datum/unit_test/voidcrew_bounty_criminal_states
	parent_type = /datum/unit_test/voidcrew_bounty_criminal

/datum/unit_test/voidcrew_bounty_criminal_states/Run()
	var/mob/living/basic/bounty_criminal/normal/criminal = allocate(__IMPLIED_TYPE__)
	TEST_ASSERT_EQUAL(criminal.capture_state(), "free", "A fresh criminal is not free") // BOUNTY_STATE_FREE
	TEST_ASSERT_EQUAL(criminal.worst_state, "free", "A fresh criminal's worst state is not free")

	// Knocked down is stunned; the worst state holds after it stands.
	criminal.Knockdown(5 SECONDS)
	TEST_ASSERT_EQUAL(criminal.capture_state(), "stunned", "A knocked-down criminal is not stunned") // BOUNTY_STATE_STUNNED
	TEST_ASSERT_EQUAL(criminal.worst_state, "stunned", "Being stunned did not reach the worst state")
	criminal.SetKnockdown(0)
	TEST_ASSERT_EQUAL(criminal.capture_state(), "free", "A criminal back on its feet is not free")
	TEST_ASSERT_EQUAL(criminal.worst_state, "stunned", "The worst state got better")

	// Stamina crit and surrender are stunned too.
	criminal.adjustStaminaLoss(300)
	TEST_ASSERT_EQUAL(criminal.capture_state(), "stunned", "A criminal in stamina crit is not stunned")
	criminal.setStaminaLoss(0)
	TEST_ASSERT_EQUAL(criminal.capture_state(), "free", "A criminal out of stamina crit is not free")
	ADD_TRAIT(criminal, "bounty_surrendered", "bounty") // TRAIT_BOUNTY_SURRENDERED, BOUNTY_TRAIT
	TEST_ASSERT_EQUAL(criminal.capture_state(), "stunned", "A surrendered criminal is not stunned")
	TEST_ASSERT(!criminal.may_attack(allocate(/mob/living/carbon/human/consistent)), "A surrendered criminal may still attack")

	// Restrained comes before stunned.
	TEST_ASSERT(criminal.body_apply_cuffs(allocate(/obj/item/restraints/handcuffs)), "A surrendered criminal could not be cuffed")
	TEST_ASSERT_EQUAL(criminal.capture_state(), "restrained", "A cuffed, surrendered criminal is not restrained") // BOUNTY_STATE_RESTRAINED
	REMOVE_TRAIT(criminal, "bounty_surrendered", "bounty")
	TEST_ASSERT_EQUAL(criminal.capture_state(), "restrained", "A cuffed criminal is not restrained")

	// Downed comes before restrained, and once downed the worst state never goes back up.
	criminal.adjustBruteLoss(500)
	TEST_ASSERT_EQUAL(criminal.capture_state(), "downed", "A cuffed, downed criminal is not downed")
	TEST_ASSERT_EQUAL(criminal.worst_state, "downed", "Being downed did not reach the worst state")
	criminal.body_remove_cuffs()
	criminal.body_stand_up()
	TEST_ASSERT(!criminal.is_downed(), "The criminal did not get up")
	TEST_ASSERT_EQUAL(criminal.capture_state(), "free", "A criminal that got up is not free")
	TEST_ASSERT_EQUAL(criminal.worst_state, "downed", "The worst state got better after getting up")
	criminal.Knockdown(5 SECONDS)
	TEST_ASSERT(criminal.body_apply_cuffs(allocate(/obj/item/restraints/handcuffs)), "The criminal could not be cuffed again")
	TEST_ASSERT_EQUAL(criminal.worst_state, "downed", "Cuffing after a down improved the worst state")

	// Dead comes before everything, and the cuffs drop.
	criminal.death()
	TEST_ASSERT_EQUAL(criminal.capture_state(), "dead", "A dead criminal is not dead")
	TEST_ASSERT_EQUAL(criminal.worst_state, "dead", "Dying did not reach the worst state")
	TEST_ASSERT(!criminal.is_restrained(), "A dead criminal kept its cuffs")
	TEST_ASSERT_NOTNULL(locate(/obj/item/restraints/handcuffs) in criminal.loc, "A dead criminal's cuffs did not drop")
	TEST_ASSERT(!criminal.is_downed(), "A dead criminal counts as downed")

// ===== RESTRAINTS =====

/datum/unit_test/voidcrew_bounty_criminal_cuffs
	parent_type = /datum/unit_test/voidcrew_bounty_criminal

/datum/unit_test/voidcrew_bounty_criminal_cuffs/Run()
	var/mob/living/carbon/human/consistent/hunter = allocate(__IMPLIED_TYPE__, get_step(run_loc_floor_bottom_left, EAST))
	for(var/cuff_type in list(/obj/item/restraints/handcuffs, /obj/item/restraints/handcuffs/cable, /obj/item/restraints/handcuffs/cable/zipties))
		signal_counts = null
		var/mob/living/basic/bounty_criminal/normal/criminal = allocate(__IMPLIED_TYPE__)
		RegisterSignal(criminal, "bounty_criminal_restrained", TYPE_PROC_REF(/datum/unit_test/voidcrew_bounty_criminal, on_restrained)) // COMSIG_BOUNTY_CRIMINAL_RESTRAINED
		RegisterSignal(criminal, "bounty_criminal_unrestrained", TYPE_PROC_REF(/datum/unit_test/voidcrew_bounty_criminal, on_unrestrained)) // COMSIG_BOUNTY_CRIMINAL_UNRESTRAINED
		var/obj/item/restraints/handcuffs/cuffs = allocate(cuff_type)

		// On its feet and free: refused, and it holds a grudge against whoever tried.
		TEST_ASSERT_EQUAL(criminal.body_cuff_refusal(hunter, cuffs), "put [criminal.p_them()] down first", "[cuff_type] could go on a criminal standing free")
		TEST_ASSERT_EQUAL(criminal.item_interaction(hunter, cuffs), ITEM_INTERACT_BLOCKING, "Using [cuff_type] on a criminal standing free was not refused")
		TEST_ASSERT(criminal.body_has_grudge(hunter), "Reaching for a free criminal's wrists did not put the hunter on its grudge list")
		TEST_ASSERT(!criminal.is_restrained(), "A refused cuffing restrained the criminal")

		// Knocked down: they go on, and hold it.
		criminal.Knockdown(5 SECONDS)
		TEST_ASSERT_NULL(criminal.body_cuff_refusal(hunter, cuffs), "[cuff_type] could not go on a knocked-down criminal")
		TEST_ASSERT(criminal.body_apply_cuffs(cuffs), "[cuff_type] did not go on")
		TEST_ASSERT(criminal.is_restrained(), "[cuff_type] went on but the criminal is not restrained")
		TEST_ASSERT_EQUAL(criminal.restraints.loc, criminal, "[cuff_type] are not in the criminal's contents")
		if(ispath(cuff_type, /obj/item/restraints/handcuffs/cable/zipties))
			TEST_ASSERT(istype(criminal.restraints, /obj/item/restraints/handcuffs/cable/zipties/used), "Zipties went on as [criminal.restraints.type], not a used pair")
		TEST_ASSERT_EQUAL(signal_count("restrained"), 1, "Cuffing with [cuff_type] did not send the restrained signal once")
		TEST_ASSERT(HAS_TRAIT(criminal, TRAIT_IMMOBILIZED), "A restrained criminal can move")
		TEST_ASSERT(HAS_TRAIT(criminal, "bounty_held"), "A restrained criminal's AI may still plan") // TRAIT_BOUNTY_HELD
		TEST_ASSERT(HAS_TRAIT(criminal, TRAIT_AI_PAUSED), "A restrained criminal's AI is not paused")
		criminal.SetKnockdown(0)
		TEST_ASSERT_EQUAL(criminal.capture_state(), "restrained", "A criminal in [cuff_type] is not restrained") // BOUNTY_STATE_RESTRAINED
		TEST_ASSERT(!criminal.may_attack(hunter), "A restrained criminal may still attack")
		TEST_ASSERT(!criminal.early_melee_attack(hunter), "A restrained criminal threw a punch")
		TEST_ASSERT_EQUAL(criminal.body_cuff_refusal(hunter, allocate(/obj/item/restraints/handcuffs)), "already cuffed", "A restrained criminal could be cuffed twice")
		TEST_ASSERT(findtext(examine_text(criminal, hunter), "restrained with"), "Examining a restrained criminal does not say so")

		// Off again: they drop, and it is free.
		var/obj/item/restraints/handcuffs/dropped = criminal.body_remove_cuffs()
		TEST_ASSERT(!criminal.is_restrained(), "Taking [cuff_type] off left the criminal restrained")
		TEST_ASSERT_EQUAL(dropped?.loc, criminal.loc, "[cuff_type] did not drop where the criminal is")
		TEST_ASSERT(!HAS_TRAIT(criminal, TRAIT_IMMOBILIZED), "A criminal out of [cuff_type] still can't move")
		TEST_ASSERT(!HAS_TRAIT(criminal, "bounty_held"), "A criminal out of [cuff_type] is still held")
		TEST_ASSERT_EQUAL(signal_count("unrestrained"), 1, "Taking [cuff_type] off did not send the unrestrained signal once")
		TEST_ASSERT_EQUAL(criminal.capture_state(), "free", "A criminal out of [cuff_type] is not free")

	// Cuffs taken out of it some other way still free it.
	var/mob/living/basic/bounty_criminal/normal/criminal = allocate(__IMPLIED_TYPE__)
	criminal.Knockdown(5 SECONDS)
	TEST_ASSERT(criminal.body_apply_cuffs(allocate(/obj/item/restraints/handcuffs)), "The criminal could not be cuffed")
	criminal.restraints.forceMove(run_loc_floor_bottom_left)
	TEST_ASSERT_NULL(criminal.restraints, "Cuffs moved out of a criminal are still its restraints")
	TEST_ASSERT(!HAS_TRAIT(criminal, TRAIT_IMMOBILIZED), "A criminal whose cuffs were taken still can't move")

	// Used zipties are no use; a dead criminal takes no cuffs.
	TEST_ASSERT_EQUAL(criminal.body_cuff_refusal(hunter, allocate(/obj/item/restraints/handcuffs/cable/zipties/used)), "used up", "Used zipties could go on")
	criminal.death()
	TEST_ASSERT_EQUAL(criminal.body_cuff_refusal(hunter, allocate(/obj/item/restraints/handcuffs)), "can't cuff [criminal.p_them()]", "A dead criminal could be cuffed")

	// A surrendered one can be cuffed on its feet.
	var/mob/living/basic/bounty_criminal/normal/quitter = allocate(__IMPLIED_TYPE__)
	ADD_TRAIT(quitter, "bounty_surrendered", "bounty") // TRAIT_BOUNTY_SURRENDERED, BOUNTY_TRAIT
	TEST_ASSERT_NULL(quitter.body_cuff_refusal(hunter, allocate(/obj/item/restraints/handcuffs)), "A surrendered criminal could not be cuffed")

// ===== SLIPPING =====

/datum/unit_test/voidcrew_bounty_criminal_slipping
	parent_type = /datum/unit_test/voidcrew_bounty_criminal

/datum/unit_test/voidcrew_bounty_criminal_slipping/Run()
	// Cable restraints slip (BOUNTY_CABLE_SLIP 3 MINUTES), with a struggle first.
	var/mob/living/basic/bounty_criminal/normal/criminal = allocate(__IMPLIED_TYPE__)
	criminal.Knockdown(5 SECONDS)
	TEST_ASSERT(criminal.body_apply_cuffs(allocate(/obj/item/restraints/handcuffs/cable)), "Cable restraints did not go on")
	TEST_ASSERT_EQUAL(criminal.body_slip_time(), 1800, "Cable restraints slip at the wrong time")
	TEST_ASSERT_NOTNULL(criminal.body_slip_timer, "Cable restraints have no slip clock")
	TEST_ASSERT_NOTNULL(criminal.body_slip_warn_timer, "Cable restraints have no struggle before they slip")
	criminal.body_slip_warning()
	TEST_ASSERT(criminal.is_restrained(), "The struggle took the cable restraints off")
	TEST_ASSERT(criminal.body_slip_cuffs(), "The criminal did not slip its cable restraints")
	TEST_ASSERT(!criminal.is_restrained(), "A criminal that slipped its restraints is still restrained")
	TEST_ASSERT_NOTNULL(locate(/obj/item/restraints/handcuffs/cable) in criminal.loc, "Slipped cable restraints did not drop")
	TEST_ASSERT_NULL(criminal.body_slip_timer, "A slip clock is left after slipping")

	// Zipties hold longer (BOUNTY_ZIPTIE_SLIP 5 MINUTES); handcuffs never slip.
	var/mob/living/basic/bounty_criminal/normal/tied = allocate(__IMPLIED_TYPE__)
	tied.Knockdown(5 SECONDS)
	TEST_ASSERT(tied.body_apply_cuffs(allocate(/obj/item/restraints/handcuffs/cable/zipties)), "Zipties did not go on")
	TEST_ASSERT_EQUAL(tied.body_slip_time(), 3000, "Zipties slip at the wrong time")
	var/mob/living/basic/bounty_criminal/normal/cuffed = allocate(__IMPLIED_TYPE__)
	cuffed.Knockdown(5 SECONDS)
	TEST_ASSERT(cuffed.body_apply_cuffs(allocate(/obj/item/restraints/handcuffs)), "Handcuffs did not go on")
	TEST_ASSERT_EQUAL(cuffed.body_slip_time(), 0, "Handcuffs slip")
	TEST_ASSERT_NULL(cuffed.body_slip_timer, "Handcuffs have a slip clock")

	// A mini-boss snaps cable in half the time (BOUNTY_BOSS_SLIP_MULT 0.5), and the cable is gone.
	var/mob/living/basic/bounty_criminal/boss/juggernaut/brute = allocate(__IMPLIED_TYPE__)
	TEST_ASSERT(brute.body_apply_cuffs(allocate(/obj/item/restraints/handcuffs/cable)), "Cable restraints did not go on a mini-boss")
	TEST_ASSERT_EQUAL(brute.body_slip_time(), 900, "A mini-boss slips cable at the wrong time")
	var/obj/item/restraints/handcuffs/cable/snapped = brute.restraints
	TEST_ASSERT(brute.body_slip_cuffs(), "A mini-boss did not snap its cable restraints")
	TEST_ASSERT(!brute.is_restrained(), "A mini-boss that snapped its restraints is still restrained")
	TEST_ASSERT(QDELETED(snapped), "Snapped cable restraints dropped whole")

// ===== DRAGGING =====

/datum/unit_test/voidcrew_bounty_criminal_drag
	parent_type = /datum/unit_test/voidcrew_bounty_criminal

/datum/unit_test/voidcrew_bounty_criminal_drag/Run()
	var/mob/living/carbon/human/consistent/hunter = allocate(__IMPLIED_TYPE__, get_step(run_loc_floor_bottom_left, EAST))
	var/mob/living/basic/bounty_criminal/normal/criminal = allocate(__IMPLIED_TYPE__)

	// Free and on its feet, it pulls away.
	hunter.start_pulling(criminal)
	TEST_ASSERT_NULL(hunter.pulling, "A free criminal on its feet could be pulled")

	// In stamina crit it can be dragged, and it shakes the hand off once it is up.
	criminal.adjustStaminaLoss(300)
	hunter.start_pulling(criminal)
	TEST_ASSERT_EQUAL(hunter.pulling, criminal, "A criminal in stamina crit could not be pulled")
	criminal.setStaminaLoss(0)
	TEST_ASSERT_NULL(hunter.pulling, "A criminal back on its feet is still being pulled")

	// Restrained, it can be dragged on its feet.
	criminal.Knockdown(5 SECONDS)
	TEST_ASSERT(criminal.body_apply_cuffs(allocate(/obj/item/restraints/handcuffs)), "The criminal could not be cuffed")
	criminal.SetKnockdown(0)
	hunter.start_pulling(criminal)
	TEST_ASSERT_EQUAL(hunter.pulling, criminal, "A restrained criminal could not be pulled")
	hunter.stop_pulling()
	criminal.body_remove_cuffs()

	// Blending in, a stunned one still shakes off any hand; a downed one does not (AR-C7).
	criminal.blended = TRUE
	criminal.Knockdown(5 SECONDS)
	hunter.start_pulling(criminal)
	TEST_ASSERT_NULL(hunter.pulling, "A stunned criminal blending in could be pulled")
	criminal.SetKnockdown(0)
	criminal.adjustBruteLoss(500)
	TEST_ASSERT(criminal.is_downed(), "The criminal was not downed")
	hunter.start_pulling(criminal)
	TEST_ASSERT_EQUAL(hunter.pulling, criminal, "A downed criminal blending in could not be pulled")
	hunter.stop_pulling()

	// Dead, it can be dragged.
	criminal.blended = FALSE
	criminal.death()
	hunter.start_pulling(criminal)
	TEST_ASSERT_EQUAL(hunter.pulling, criminal, "A dead criminal could not be pulled")
	hunter.stop_pulling()

// ===== DEATH =====

/datum/unit_test/voidcrew_bounty_criminal_death
	parent_type = /datum/unit_test/voidcrew_bounty_criminal

/datum/unit_test/voidcrew_bounty_criminal_death/Run()
	// No revive, not even an admin's.
	var/mob/living/basic/bounty_criminal/normal/criminal = allocate(__IMPLIED_TYPE__)
	criminal.death()
	TEST_ASSERT(!criminal.can_be_revived(), "A dead criminal can be revived")
	criminal.revive(ADMIN_HEAL_ALL)
	TEST_ASSERT_EQUAL(criminal.stat, DEAD, "A dead criminal came back")

	// Its body is the proof: a death that leaves the body drops none; a gib drops it.
	var/datum/criminal_bounty/posting = new
	var/mob/living/basic/bounty_criminal/normal/gibbed = allocate(__IMPLIED_TYPE__)
	gibbed.posting_ref = WEAKREF(posting)
	gibbed.death()
	TEST_ASSERT(!gibbed.body_proof_dropped, "A dead criminal whose body stays left proof")
	gibbed.gib()
	TEST_ASSERT(QDELETED(gibbed), "The gibbed criminal was not deleted")
	TEST_ASSERT(gibbed.body_proof_dropped, "A gibbed criminal left no proof")

	// A live one gibbed dies first, and leaves proof.
	var/mob/living/basic/bounty_criminal/normal/blown_up = allocate(__IMPLIED_TYPE__)
	blown_up.posting_ref = WEAKREF(posting)
	blown_up.gib()
	TEST_ASSERT(blown_up.body_proof_dropped, "A criminal gibbed alive left no proof")

	// Deleted any other way, it asks for proof too; P5's bounty_drop_proof() decides.
	var/mob/living/basic/bounty_criminal/normal/vanished = allocate(__IMPLIED_TYPE__)
	vanished.posting_ref = WEAKREF(posting)
	qdel(vanished)
	TEST_ASSERT(vanished.body_proof_dropped, "A criminal deleted with its posting open did not ask for proof")

	// Removed on purpose, by P5's mark (the pad, closing, relisting, its site unloading) or ours: no proof.
	var/mob/living/basic/bounty_criminal/normal/beamed = allocate(__IMPLIED_TYPE__)
	beamed.posting_ref = WEAKREF(posting)
	ADD_TRAIT(beamed, "bounty_removed", "bounty") // TRAIT_BOUNTY_REMOVED, BOUNTY_TRAIT
	qdel(beamed)
	TEST_ASSERT(!beamed.body_proof_dropped, "A criminal the pad removed left proof")
	var/mob/living/basic/bounty_criminal/normal/unloaded = allocate(__IMPLIED_TYPE__)
	unloaded.posting_ref = WEAKREF(posting)
	unloaded.body_mark_removed()
	qdel(unloaded)
	TEST_ASSERT(!unloaded.body_proof_dropped, "A criminal removed on purpose left proof")

	// A closed posting takes no proof.
	posting.status = "closed" // BOUNTY_POSTING_CLOSED
	var/mob/living/basic/bounty_criminal/normal/late = allocate(__IMPLIED_TYPE__)
	late.posting_ref = WEAKREF(posting)
	late.gib()
	TEST_ASSERT(!late.body_proof_dropped, "A criminal gibbed after its posting closed left proof")
	qdel(posting)

// ===== THE AUTOMATED DAMAGE FLOOR =====

/datum/unit_test/voidcrew_bounty_criminal_automated
	parent_type = /datum/unit_test/voidcrew_bounty_criminal

/datum/unit_test/voidcrew_bounty_criminal_automated/Run()
	var/mob/living/basic/bounty_criminal/normal/criminal = allocate(__IMPLIED_TYPE__)
	var/turf/here = get_turf(criminal)
	criminal.site_bounds = list(here.x - 2, here.y - 2, here.x + 2, here.y + 2, here.z)
	var/datum/component/bounty_body/ledger = criminal.GetComponent(/datum/component/bounty_body)
	TEST_ASSERT_NOTNULL(ledger, "A criminal has no damage ledger")

	// Nobody's mind behind it: it stops at the floor, on its feet (BOUNTY_AUTOMATED_FLOOR 40: 48 of 120).
	criminal.adjustBruteLoss(500)
	TEST_ASSERT_EQUAL(criminal.health, 48, "Automated damage took a criminal on its site past the floor")
	TEST_ASSERT(!criminal.is_downed(), "Automated damage downed a criminal on its site")

	// A player's hit: only the mercy rule.
	var/mob/living/carbon/human/consistent/hunter = allocate(__IMPLIED_TYPE__, get_step(here, EAST))
	hunter.mind_initialize()
	ledger.note_attacker(hunter)
	TEST_ASSERT(ledger.player_hit_now(), "A hunter with a mind did not count as a player")
	TEST_ASSERT(criminal.body_has_grudge(hunter), "An attacker did not go on the grudge list")
	criminal.adjustBruteLoss(500)
	TEST_ASSERT_EQUAL(criminal.health, 29, "A player's hit on a criminal on its site did not stop at the downed line")
	TEST_ASSERT(criminal.is_downed(), "A player's hit did not down the criminal")

	// Down on its site, nothing automated finishes it off.
	ledger.player_hit_at = -1
	criminal.adjustBruteLoss(500)
	TEST_ASSERT_EQUAL(criminal.stat, CONSCIOUS, "Automated damage killed a downed criminal on its site")

	// Its own side's blows miss it while it is down.
	var/mob/living/basic/bounty_criminal/normal/downed_off_site = allocate(__IMPLIED_TYPE__)
	downed_off_site.adjustBruteLoss(500)
	var/datum/component/bounty_body/other_ledger = downed_off_site.GetComponent(/datum/component/bounty_body)
	other_ledger.note_attacker(allocate(/mob/living/basic/bounty_companion))
	downed_off_site.adjustBruteLoss(10)
	TEST_ASSERT_EQUAL(downed_off_site.health, 29, "A companion's blow hurt a downed criminal")

	// Off its site, automated damage gets the mercy rule only.
	var/mob/living/basic/bounty_criminal/normal/stray = allocate(__IMPLIED_TYPE__)
	stray.site_bounds = list(here.x + 3, here.y + 3, here.x + 4, here.y + 4, here.z)
	stray.adjustBruteLoss(500)
	TEST_ASSERT_EQUAL(stray.health, 29, "Automated damage off its site did not stop at the downed line")

// ===== THE LEASH AND WHO IT FIGHTS =====

/datum/unit_test/voidcrew_bounty_criminal_leash
	parent_type = /datum/unit_test/voidcrew_bounty_criminal

/datum/unit_test/voidcrew_bounty_criminal_leash/Run()
	var/mob/living/basic/bounty_criminal/normal/criminal = allocate(__IMPLIED_TYPE__)
	var/turf/here = get_turf(criminal)
	var/turf/east = get_step(here, EAST)
	var/turf/north = get_step(here, NORTH)
	TEST_ASSERT(criminal.leash_ok(north), "A criminal with no site may not go somewhere")
	TEST_ASSERT(!criminal.leash_ok(null), "A criminal may go nowhere")

	// Leashed to its tile and the one east.
	criminal.site_bounds = list(here.x, here.y, here.x + 1, here.y, here.z)
	TEST_ASSERT(criminal.leash_ok(east), "A tile on the site is off the leash")
	TEST_ASSERT(!criminal.leash_ok(north), "A tile off the site is on the leash")
	criminal.Move(north, NORTH)
	TEST_ASSERT_EQUAL(criminal.loc, here, "A criminal walked off its site")
	criminal.Move(east, EAST)
	TEST_ASSERT_EQUAL(criminal.loc, east, "A criminal could not walk on its site")
	criminal.Move(here, WEST)
	TEST_ASSERT_EQUAL(criminal.loc, here, "A criminal could not walk back")

	// On its site it may fight anyone on their feet, and never someone down.
	var/mob/living/carbon/human/consistent/hunter = allocate(__IMPLIED_TYPE__, north)
	TEST_ASSERT(criminal.may_attack(hunter), "A criminal on its site may not fight a hunter")
	var/mob/living/basic/bounty_criminal/normal/friend = allocate(__IMPLIED_TYPE__, east)
	TEST_ASSERT(!criminal.may_attack(friend), "A criminal may fight another criminal")
	TEST_ASSERT(!criminal.may_attack(criminal), "A criminal may fight itself")
	var/obj/structure/table/table = allocate(__IMPLIED_TYPE__, east)
	TEST_ASSERT(criminal.may_attack(table), "A criminal on its site may not break a table on its site")
	hunter.Unconscious(10 SECONDS)
	TEST_ASSERT(!criminal.may_attack(hunter), "A criminal may attack a hunter who is down")
	hunter.SetUnconscious(0)

	// Off its site, only its grudge list, and no structures.
	criminal.site_bounds = list(here.x + 3, here.y + 3, here.x + 4, here.y + 4, here.z)
	TEST_ASSERT(!criminal.may_attack(hunter), "A criminal off its site may fight a stranger")
	TEST_ASSERT(!criminal.may_attack(table), "A criminal off its site may break things")
	criminal.body_add_grudge(hunter)
	TEST_ASSERT(criminal.may_attack(hunter), "A criminal off its site may not fight someone it holds a grudge against")

	// Off its site, it walks anywhere (back toward its site, say); dragged, it goes anywhere.
	hunter.forceMove(get_step(north, NORTH))
	criminal.Move(north, NORTH)
	TEST_ASSERT_EQUAL(criminal.loc, north, "A criminal already off its site could not move")
	criminal.site_bounds = list(here.x, here.y, here.x, here.y, here.z)
	criminal.forceMove(here)
	criminal.Knockdown(5 SECONDS)
	var/mob/living/carbon/human/consistent/dragger = allocate(__IMPLIED_TYPE__, east)
	dragger.start_pulling(criminal)
	TEST_ASSERT_EQUAL(dragger.pulling, criminal, "A knocked-down criminal could not be pulled")
	TEST_ASSERT(criminal.body_move_allowed(north), "A dragged criminal was held to its leash")

	// No environment damage off its site, or near a dock strip.
	TEST_ASSERT(!criminal.environment_damage_allowed(north), "Environment damage allowed off its site")
	criminal.body_dock_top_y = here.y
	TEST_ASSERT(!criminal.environment_damage_allowed(here), "Environment damage allowed beside the dock strip")

	// Teleports, polymorph and type changes are refused.
	var/mob/living/basic/bounty_criminal/meek/runner = allocate(__IMPLIED_TYPE__)
	TEST_ASSERT(!do_teleport(runner, east, no_effects = TRUE, forced = TRUE), "A criminal was teleported")
	TEST_ASSERT_EQUAL(runner.loc, here, "A criminal moved when teleported")
	TEST_ASSERT(SEND_SIGNAL(runner, COMSIG_LIVING_PRE_WABBAJACKED, null) & STOP_WABBAJACK, "A criminal could be polymorphed")
	TEST_ASSERT(SEND_SIGNAL(runner, COMSIG_PRE_MOB_CHANGED_TYPE) & COMPONENT_BLOCK_MOB_CHANGE, "A criminal could change type")
	TEST_ASSERT_EQUAL(runner.sentience_type, 0, "A criminal can be given sentience") // BOUNTY_CRIMINAL_NO_SENTIENCE

	// A sprinting meek criminal ducks shots, but not straight after one got through (BOUNTY_MEEK_DODGE 50).
	TEST_ASSERT_EQUAL(runner.body_dodge_chance(), 0, "A meek criminal ducks shots when not sprinting")
	ADD_TRAIT(runner, "bounty_sprinting", "bounty") // TRAIT_BOUNTY_SPRINTING, BOUNTY_TRAIT
	TEST_ASSERT_EQUAL(runner.body_dodge_chance(), 50, "A sprinting meek criminal does not duck shots")
	runner.body_last_shot_at = world.time
	TEST_ASSERT_EQUAL(runner.body_dodge_chance(), 0, "A meek criminal ducks the shot after one hit it")
	runner.body_last_shot_at = -1
	runner.Knockdown(5 SECONDS)
	TEST_ASSERT_EQUAL(runner.body_dodge_chance(), 0, "A knocked-down meek criminal ducks shots")
	ADD_TRAIT(friend, "bounty_sprinting", "bounty")
	TEST_ASSERT_EQUAL(friend.body_dodge_chance(), 0, "A normal criminal ducks shots")

// ===== TURRETS =====

/datum/unit_test/voidcrew_bounty_criminal_turrets
	parent_type = /datum/unit_test/voidcrew_bounty_criminal

/datum/unit_test/voidcrew_bounty_criminal_turrets/Run()
	// Even with an AI that hunts people, turrets leave criminals, decoys and companions to the hunters.
	var/mob/living/basic/bounty_criminal/normal/criminal = allocate(__IMPLIED_TYPE__)
	new /datum/ai_controller/basic_controller/simple/simple_hostile(criminal)
	TEST_ASSERT(istype(criminal.ai_controller, /datum/ai_controller/basic_controller/simple/simple_hostile), "The criminal did not take the hostile AI")
	TEST_ASSERT(!is_hostile_creature(criminal), "Turrets would shoot a bounty criminal")
	TEST_ASSERT(!is_hostile_creature(allocate(/mob/living/basic/bounty_criminal/decoy)), "Turrets would shoot a decoy")
	TEST_ASSERT(!is_hostile_creature(allocate(/mob/living/basic/bounty_companion)), "Turrets would shoot a companion")

// ===== SPAWNING, EXAMINE AND MAKING THEM WITH NO ARGUMENTS =====

/datum/unit_test/voidcrew_bounty_criminal_spawn
	parent_type = /datum/unit_test/voidcrew_bounty_criminal

/datum/unit_test/voidcrew_bounty_criminal_spawn/Run()
	var/mob/living/carbon/human/consistent/hunter = allocate(__IMPLIED_TYPE__, get_step(run_loc_floor_bottom_left, EAST))

	// Every criminal type comes up and goes away with no arguments, and its body procs don't runtime.
	for(var/criminal_type in typesof(/mob/living/basic/bounty_criminal))
		var/mob/living/basic/bounty_criminal/criminal = allocate(criminal_type)
		TEST_ASSERT(!QDELETED(criminal), "[criminal_type] was deleted as it was made")
		TEST_ASSERT_EQUAL(criminal.capture_state(), "free", "A fresh [criminal_type] is not free")
		TEST_ASSERT_EQUAL(criminal.max_stamina, 100, "[criminal_type] has the wrong stamina pool") // BOUNTY_CRIMINAL_MAX_STAMINA
		TEST_ASSERT(!criminal.may_attack(null), "[criminal_type] may attack nothing")
		TEST_ASSERT(criminal.leash_ok(get_turf(criminal)), "[criminal_type] with no site is off its leash where it stands")
		TEST_ASSERT(length(criminal.examine(hunter)), "Examining [criminal_type] shows nothing")
		TEST_ASSERT(!criminal.body_leaves_proof(), "[criminal_type] with no posting would leave proof")

	// With no record: a normal criminal.
	var/list/spawned = list()
	var/mob/living/basic/bounty_criminal/plain = spawn_bounty_criminal(null, run_loc_floor_bottom_left, null)
	spawned += plain
	TEST_ASSERT(istype(plain, /mob/living/basic/bounty_criminal/normal), "A criminal with no record is [plain?.type]")
	TEST_ASSERT_NULL(spawn_bounty_criminal(null, null, null), "A criminal spawned nowhere")

	// Meek: its name, its health, and the planet-sweep protection while wanted.
	var/datum/bounty_record/meek_record = new
	meek_record.archetype = "meek" // BOUNTY_ARCHETYPE_MEEK
	meek_record.name = "Tess Harlow"
	meek_record.gender = FEMALE
	var/datum/criminal_bounty/posting = new
	var/mob/living/basic/bounty_criminal/meek/runner = spawn_bounty_criminal(meek_record, run_loc_floor_bottom_left, posting)
	spawned += runner
	TEST_ASSERT(istype(runner), "A meek record spawned [runner?.type]")
	TEST_ASSERT_EQUAL(runner.record, meek_record, "A spawned criminal lost its record")
	TEST_ASSERT_EQUAL(runner.posting(), posting, "A spawned criminal lost its posting")
	TEST_ASSERT_EQUAL(runner.real_name, "Tess Harlow", "A spawned criminal lost its name")
	TEST_ASSERT_EQUAL(runner.gender, FEMALE, "A spawned criminal lost its gender")
	TEST_ASSERT_EQUAL(runner.maxHealth, 80, "A meek criminal has the wrong health") // BOUNTY_MEEK_HEALTH
	TEST_ASSERT(HAS_TRAIT(runner, "mission_field_mob"), "A wanted criminal is not kept from the planet sweep") // TRAIT_MISSION_FIELD_MOB
	// BOUNTY_MEEK_STAMINA 90 on a pool of 100: three 30-point disabler shots
	runner.adjustStaminaLoss(30)
	runner.adjustStaminaLoss(30)
	TEST_ASSERT(!runner.has_status_effect(/datum/status_effect/incapacitating/stamcrit), "Two disabler shots stamina-crit a meek criminal")
	runner.adjustStaminaLoss(30)
	TEST_ASSERT(runner.has_status_effect(/datum/status_effect/incapacitating/stamcrit), "Three disabler shots did not stamina-crit a meek criminal")

	// Normal: health by tier and style (BOUNTY_NORMAL_HEALTH_PETTY 90 x BOUNTY_STYLE_HEALTH_BRAWLER 1.2), pace by style.
	var/datum/bounty_record/brawler_record = new
	brawler_record.archetype = "normal" // BOUNTY_ARCHETYPE_NORMAL
	brawler_record.tier = 1 // BOUNTY_TIER_PETTY
	brawler_record.style = "brawler" // BOUNTY_STYLE_BRAWLER
	var/mob/living/basic/bounty_criminal/normal/brawler = spawn_bounty_criminal(brawler_record, run_loc_floor_bottom_left, null)
	spawned += brawler
	TEST_ASSERT_EQUAL(brawler.maxHealth, 108, "A petty brawler has the wrong health")
	TEST_ASSERT_EQUAL(brawler.health, 108, "A petty brawler did not start at full health")
	TEST_ASSERT_EQUAL(brawler.speed, 1.6, "A brawler has the wrong pace") // BOUNTY_BODY_NORMAL_SPEED_MELEE
	TEST_ASSERT(!HAS_TRAIT(brawler, "mission_field_mob"), "A criminal with no posting is kept from the planet sweep")
	var/datum/bounty_record/gunman_record = new
	gunman_record.archetype = "normal"
	gunman_record.tier = 3 // BOUNTY_TIER_MOST_WANTED
	gunman_record.style = "pistol" // BOUNTY_STYLE_PISTOL
	var/mob/living/basic/bounty_criminal/normal/gunman = spawn_bounty_criminal(gunman_record, run_loc_floor_bottom_left, null)
	spawned += gunman
	// BOUNTY_NORMAL_HEALTH_MOST 150 x BOUNTY_STYLE_HEALTH_PISTOL 0.9
	TEST_ASSERT_EQUAL(gunman.maxHealth, 135, "A Most Wanted gunman has the wrong health")
	TEST_ASSERT_EQUAL(gunman.speed, 1.8, "A gunman has the wrong pace") // BOUNTY_BODY_NORMAL_SPEED_RANGED

	// Mini-bosses by kit; never at a trader outpost, where a normal criminal stands in.
	var/datum/bounty_record/boss_record = new
	boss_record.archetype = "boss" // BOUNTY_ARCHETYPE_BOSS
	boss_record.kit = "ghost" // BOUNTY_KIT_GHOST
	TEST_ASSERT_EQUAL(bounty_criminal_type(boss_record, null), /mob/living/basic/bounty_criminal/boss/ghost, "A ghost record is the wrong type")
	var/datum/criminal_bounty/outpost_posting = new
	outpost_posting.placement_kind = "trader_outpost" // BOUNTY_PLACEMENT_TRADER_OUTPOST
	TEST_ASSERT_EQUAL(bounty_criminal_type(boss_record, outpost_posting), /mob/living/basic/bounty_criminal/normal, "A mini-boss was placed at a trader outpost")

	// Examine: how hurt, and the downed hint; blending in, one layout only.
	var/mob/living/basic/bounty_criminal/normal/examined = allocate(__IMPLIED_TYPE__)
	TEST_ASSERT(findtext(examine_text(examined, hunter), "unhurt"), "Examining an unhurt criminal does not say so")
	examined.adjustBruteLoss(500)
	TEST_ASSERT(findtext(examine_text(examined, hunter), "will get back up"), "Examining a downed criminal does not say it will get up")
	examined.blended = TRUE
	TEST_ASSERT(!findtext(examine_text(examined, hunter), "will get back up"), "Examining a criminal blending in shows more than a decoy's layout")

	for(var/mob/living/basic/bounty_criminal/criminal as anything in spawned)
		qdel(criminal)
	qdel(posting)
	qdel(outpost_posting)
