/**
 * Bounty hunting: P5 board's tests, for voidcrew/modules/bounties/bounty_board.dm, bounty_posting.dm, bounty_placement.dm and bounty_turn_in.dm.
 *
 * Owner: P5 board. Do not edit this file outside that package. Fork defines are included after the
 * tests, so a test uses the literal value with a comment naming the define.
 *
 * The tests drive the board's procs directly: postings are made by hand where a site doesn't
 * matter, criminals come from spawn_bounty_criminal() and are adopted by hand, and a capture state
 * is passed to board_claim() rather than reached through a fight. The board's own clock is stopped
 * for every test here, and every posting is closed before and after.
 */

// ===== FIXTURES =====

/// Stops the board's clock and closes every posting, so a test starts on an empty board
/datum/unit_test/proc/board_test_begin()
	SScriminal_bounties.can_fire = FALSE
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties.Copy())
		posting.close("admin") // BOUNTY_CLOSE_ADMIN

/// Closes whatever the test left on the board and starts the clock again
/datum/unit_test/proc/board_test_end()
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties.Copy())
		posting.close("admin") // BOUNTY_CLOSE_ADMIN
	SScriminal_bounties.can_fire = TRUE

/**
 * A posting made by hand, with no site: a public bounty (or an offer to `offered`) of `tier`,
 * worth `value` credits and `vouchers` vouchers at full pay, in green space.
 */
/datum/unit_test/proc/board_test_posting(tier = 2, obj/structure/overmap/ship/offered = null, value = 1000, vouchers = 1, archetype = "meek")
	var/datum/bounty_record/record = generate_bounty_record(tier, archetype, "planet") // BOUNTY_PLACEMENT_PLANET
	record.tier = tier
	record.archetype = archetype
	record.base_value = value
	var/datum/criminal_bounty/posting = new
	posting.record = record
	posting.placement_kind = "planet" // BOUNTY_PLACEMENT_PLANET
	posting.value = value
	posting.board_vouchers = vouchers
	posting.board_zone = 1 // ZONE_GREEN
	posting.expires_at = world.time + 45 MINUTES
	posting.private_to = offered ? WEAKREF(offered) : null
	posting.board_gps_tag = "WANTED-[record.id]"
	GLOB.criminal_bounties += posting
	return posting

/// The posting's criminal, spawned at `spot` and adopted by hand, its AI off so it stays where a test puts it
/datum/unit_test/proc/board_test_criminal(datum/criminal_bounty/posting, turf/spot)
	var/mob/living/basic/bounty_criminal/criminal = spawn_bounty_criminal(posting.record, spot, posting)
	if(!criminal)
		return null
	posting.board_adopt_criminal(criminal, null, "explore", null) // BOUNTY_ACTIVITY_EXPLORE
	criminal.ai_controller?.set_ai_status(AI_STATUS_OFF)
	return criminal

/// A bare ship record with an account holding `balance`
/datum/unit_test/proc/board_test_ship(balance = 0)
	var/obj/structure/overmap/ship/ship = allocate(/obj/structure/overmap/ship)
	ship.ship_account = allocate(/datum/bank_account/ship, "Bounty Test [REF(ship)]", null, 1, FALSE)
	ship.ship_account.account_balance = balance
	return ship

/// Trade vouchers lying on `spot`
/datum/unit_test/proc/board_test_vouchers(turf/spot)
	var/count = 0
	for(var/obj/item/stack/trade_voucher/voucher in spot)
		count += voucher.amount
	return count

/// The board's tests: its clock stopped and the board emptied around each one
/datum/unit_test/voidcrew_bounty_board
	abstract_type = /datum/unit_test/voidcrew_bounty_board

/datum/unit_test/voidcrew_bounty_board/New()
	. = ..()
	board_test_begin()

/datum/unit_test/voidcrew_bounty_board/Destroy()
	board_test_end()
	return ..()

// ===== POSTING AND VALUE =====

/// The value is fixed at posting from the site's zone (AR-A9): the mission multipliers on credits, and red adds a voucher (12.1)
/datum/unit_test/voidcrew_bounty_board/value

/datum/unit_test/voidcrew_bounty_board/value/Run()
	// BOUNTY_ZONE_MULT_GREEN / _YELLOW / _RED: 1 / 1.7 / 2.6
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_value_for(1000, 1), 1000, "A green bounty is not worth its base")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_value_for(1000, 2), 1700, "A yellow bounty is not worth 1.7 times its base")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_value_for(1000, 3), 2600, "A red bounty is not worth 2.6 times its base")
	// BOUNTY_VOUCHERS_PETTY / _WANTED / _MOST_WANTED: 0 / 1 / 1, and red adds one to a tier that pays them
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_vouchers_for(1, 3), 0, "A red petty bounty pays a voucher")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_vouchers_for(2, 1), 1, "A green wanted bounty doesn't pay one voucher")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_vouchers_for(2, 3), 2, "A red wanted bounty doesn't pay two vouchers")
	// BOUNTY_VOUCHERS_MOST_WANTED 2 (12.3 C11)
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_vouchers_for(3, 2), 2, "A yellow most wanted bounty doesn't pay two vouchers")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_vouchers_for(3, 3), 3, "A red most wanted bounty doesn't pay three vouchers")

	// Base bands by tier (BOUNTY_PAY_*: 1100-1500, 1200-1600, 3000-3800)
	for(var/i in 1 to 20)
		var/petty = SScriminal_bounties.board_roll_base_value(1)
		var/wanted = SScriminal_bounties.board_roll_base_value(2)
		var/most_wanted = SScriminal_bounties.board_roll_base_value(3)
		TEST_ASSERT(petty >= 1100 && petty <= 1500, "A petty bounty rolled [petty]")
		TEST_ASSERT(wanted >= 1200 && wanted <= 1600, "A wanted bounty rolled [wanted]")
		TEST_ASSERT(most_wanted >= 3000 && most_wanted <= 3800, "A most wanted bounty rolled [most_wanted]")

	// Where each tier may go (AR-C9, D-A8, spec 6)
	TEST_ASSERT(!SScriminal_bounties.board_kind_allowed("trader_outpost", 3, "boss"), "A most wanted bounty may go to a trader outpost")
	TEST_ASSERT(!SScriminal_bounties.board_kind_allowed("npc_ship", 1, "normal"), "A petty bounty may go aboard a pirate ship")
	TEST_ASSERT(!SScriminal_bounties.board_kind_allowed("npc_ship", 2, "meek"), "A meek criminal may go aboard a pirate ship")
	TEST_ASSERT(SScriminal_bounties.board_kind_allowed("npc_ship", 2, "normal"), "A normal wanted criminal may not go aboard a pirate ship")
	TEST_ASSERT_NULL(post_criminal_bounty(3, "trader_outpost"), "A most wanted bounty was posted at a trader outpost")
	for(var/i in 1 to 20)
		TEST_ASSERT_EQUAL(SScriminal_bounties.board_roll_archetype(3, "planet"), "boss", "A most wanted criminal is not a mini-boss")
		TEST_ASSERT_EQUAL(SScriminal_bounties.board_roll_archetype(2, "npc_ship"), "normal", "A pirate ship criminal is not normal")
		TEST_ASSERT(SScriminal_bounties.board_roll_public_tier() in list(2, 3), "A public bounty rolled a tier other than wanted or most wanted")

	// Posted at a real site: the value comes from that site's zone, and the ruin is held on the chart
	var/obj/structure/overmap/space_ruin/ruin = allocate(/obj/structure/overmap/space_ruin, outpost_lead_overmap_turf(40, 40))
	var/claims_before = ruin.mission_claims
	var/datum/criminal_bounty/posting = post_criminal_bounty(2, "ruin", ruin)
	TEST_ASSERT_NOTNULL(posting, "No bounty was posted at a plain ruin")
	TEST_ASSERT(posting in GLOB.criminal_bounties, "The posting is not on the board")
	TEST_ASSERT_EQUAL(posting.site(), ruin, "The posting is not at its ruin")
	TEST_ASSERT_EQUAL(posting.placement_kind, "ruin", "The posting's kind is not a ruin")
	TEST_ASSERT_NULL(posting.private_to, "A public posting is private")
	var/zone = SScriminal_bounties.board_site_zone(ruin)
	TEST_ASSERT_EQUAL(posting.board_zone, zone, "The posting's zone is not its site's")
	TEST_ASSERT_EQUAL(posting.value, SScriminal_bounties.board_value_for(posting.record.base_value, zone), "The value is not the base times the site's zone multiplier")
	TEST_ASSERT_EQUAL(posting.board_vouchers, SScriminal_bounties.board_vouchers_for(2, zone), "The vouchers don't match the tier and zone")
	TEST_ASSERT_EQUAL(ruin.mission_claims, claims_before + 1, "The posting doesn't hold its ruin on the chart")
	TEST_ASSERT(posting.expires_at >= world.time + 44 MINUTES, "A public bounty is not up for 45 minutes") // BOUNTY_PUBLIC_EXPIRY
	posting.close("admin")
	TEST_ASSERT_EQUAL(ruin.mission_claims, claims_before, "Closing the posting didn't let its ruin go")
	TEST_ASSERT(!(posting in GLOB.criminal_bounties), "A closed posting stayed on the board")

// ===== CAP AND GAP =====

/// 1 + active ships / 4 public bounties, at most 4, one per 10 minutes (12.1)
/datum/unit_test/voidcrew_bounty_board/cap_gap

/datum/unit_test/voidcrew_bounty_board/cap_gap/Run()
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_public_cap(0), 1, "An empty server's cap is not 1")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_public_cap(3), 1, "Three ships' cap is not 1")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_public_cap(4), 2, "Four ships' cap is not 2")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_public_cap(8), 3, "Eight ships' cap is not 3")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_public_cap(40), 4, "The cap goes over 4") // BOUNTY_MAX_PUBLIC

	// Inside the gap, nothing goes up
	SScriminal_bounties.board_next_public_post = world.time + 5 MINUTES
	TEST_ASSERT_NULL(SScriminal_bounties.board_post_public_if_due(), "A public bounty went up inside the gap")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_public_count(), 0, "Something was posted inside the gap")

	// Past it, one goes up, and the next waits a whole gap; with no site anywhere, it tries again in a minute
	SScriminal_bounties.board_next_public_post = 0
	var/datum/criminal_bounty/posted = SScriminal_bounties.board_post_public_if_due()
	if(posted)
		TEST_ASSERT_NULL(posted.private_to, "The board posted a private bounty on its own clock")
		TEST_ASSERT(posted.record.tier in list(2, 3), "The board posted a petty public bounty")
		TEST_ASSERT_EQUAL(SScriminal_bounties.board_next_public_post, world.time + 10 MINUTES, "The next public bounty doesn't wait the gap") // BOUNTY_PUBLIC_POST_GAP
		posted.close("admin")
	else
		TEST_ASSERT_EQUAL(SScriminal_bounties.board_next_public_post, world.time + 1 MINUTES, "A failed posting doesn't retry in a minute") // BOUNTY_PUBLIC_POST_RETRY

	// At the cap, nothing goes up however long the gap has run
	var/cap = SScriminal_bounties.board_public_cap()
	for(var/i in 1 to cap)
		board_test_posting()
	SScriminal_bounties.board_next_public_post = 0
	TEST_ASSERT_NULL(SScriminal_bounties.board_post_public_if_due(), "A public bounty went up over the cap")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_public_count(), cap, "The board went over its cap")

	// Private offers don't count toward it, and a ship gets two at most (BOUNTY_PRIVATE_MAX)
	var/obj/structure/overmap/ship/ship = board_test_ship()
	board_test_posting(1, ship)
	board_test_posting(1, ship)
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_public_count(), cap, "Private offers count toward the public cap")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_private_count(ship), 2, "The ship doesn't hold its two offers")
	TEST_ASSERT(!length(SScriminal_bounties.board_offer_private(ship)), "A ship with two offers was offered a third")

	// A dropped offer is not replaced at once (BOUNTY_PRIVATE_GAP)
	var/datum/criminal_bounty/offer = null
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(posting.private_to)
			offer = posting
			break
	TEST_ASSERT_EQUAL(offer.hunt(ship), TRUE, "The ship could not take its offer")
	TEST_ASSERT_EQUAL(offer.abandon(ship), TRUE, "The ship could not drop its offer")
	TEST_ASSERT(QDELETED(offer), "A dropped offer stayed on the board")
	TEST_ASSERT(SScriminal_bounties.board_private_next[WEAKREF(ship)] > world.time, "A dropped offer doesn't hold back the next")
	TEST_ASSERT(!length(SScriminal_bounties.board_offer_private(ship)), "A dropped offer was replaced at once")
	SScriminal_bounties.board_private_next -= WEAKREF(ship)

// ===== THE CLOCK =====

/// 45 minutes, held while a ship hunts it, for up to 30 minutes a hunt (12.1)
/datum/unit_test/voidcrew_bounty_board/expiry

/datum/unit_test/voidcrew_bounty_board/expiry/Run()
	var/obj/structure/overmap/ship/ship = board_test_ship()
	var/datum/criminal_bounty/posting = board_test_posting()
	posting.expires_at = world.time + 100
	posting.board_process(50)
	TEST_ASSERT_EQUAL(posting.expires_at, world.time + 100, "The clock was held with nobody hunting")

	TEST_ASSERT_EQUAL(posting.hunt(ship), TRUE, "The ship could not hunt the bounty")
	TEST_ASSERT(posting.board_clock_held(), "A fresh hunt doesn't hold the clock")
	posting.board_process(50)
	TEST_ASSERT_EQUAL(posting.expires_at, world.time + 150, "A hunt didn't hold the clock")

	// A hunt holds it for BOUNTY_HUNT_PAUSE_LIMIT (30 minutes), no longer
	var/datum/weakref/ship_ref = WEAKREF(ship)
	posting.board_hunt_started[ship_ref] = world.time - 31 MINUTES
	TEST_ASSERT(!posting.board_clock_held(), "A hunt held the clock for over 30 minutes")
	posting.board_process(50)
	TEST_ASSERT_EQUAL(posting.expires_at, world.time + 150, "An old hunt still held the clock")

	// Time's up: it closes
	posting.expires_at = world.time - 1
	posting.board_process(0)
	TEST_ASSERT(QDELETED(posting), "An expired bounty stayed up")
	TEST_ASSERT(!(posting in GLOB.criminal_bounties), "An expired bounty stayed on the board")
	TEST_ASSERT_NULL(ship.get_waypoint("wanted_[REF(posting)]"), "An expired bounty left its waypoint on the hunter's helm")

	// A private offer's clock is never held
	var/datum/criminal_bounty/offer = board_test_posting(1, ship)
	TEST_ASSERT_EQUAL(offer.hunt(ship), TRUE, "The ship could not take its offer")
	TEST_ASSERT(!offer.board_clock_held(), "A private offer's clock was held")
	TEST_ASSERT(offer.expires_at >= world.time + 29 MINUTES, "A taken offer doesn't run for 30 minutes") // BOUNTY_PRIVATE_DURATION

// ===== HUNTS =====

/// One public hunt per ship, none again after abandoning, and a private offer only for its ship (D-A11)
/datum/unit_test/voidcrew_bounty_board/hunts

/datum/unit_test/voidcrew_bounty_board/hunts/Run()
	var/obj/structure/overmap/ship/ship = board_test_ship()
	var/obj/structure/overmap/ship/other = board_test_ship()
	var/datum/criminal_bounty/first = board_test_posting()
	var/datum/criminal_bounty/second = board_test_posting()
	var/missions_before = length(ship.active_missions)

	TEST_ASSERT_EQUAL(first.hunt(ship), TRUE, "The ship could not hunt a bounty")
	TEST_ASSERT(first.is_hunting(ship), "The ship isn't hunting it")
	TEST_ASSERT_EQUAL(length(ship.active_missions), missions_before, "A hunt took a mission slot")
	TEST_ASSERT(istext(first.hunt(ship)), "The ship hunted the same bounty twice")
	TEST_ASSERT(istext(second.hunt(ship)), "The ship hunted two public bounties at once")
	TEST_ASSERT_EQUAL(second.hunt(other), TRUE, "Another ship could not hunt the second bounty")
	TEST_ASSERT(istext(first.hunt(other)), "A ship hunting one public bounty took on a second")
	var/obj/structure/overmap/ship/third = board_test_ship()
	TEST_ASSERT_EQUAL(first.hunt(third), TRUE, "Two ships could not hunt the same bounty")
	TEST_ASSERT_EQUAL(length(first.hunter_ships()), 2, "The bounty doesn't count both hunters")

	TEST_ASSERT_EQUAL(first.abandon(ship), TRUE, "The ship could not abandon its hunt")
	TEST_ASSERT(!first.is_hunting(ship), "The ship is still hunting what it abandoned")
	TEST_ASSERT(istext(first.hunt(ship)), "The ship hunted again what it abandoned")
	TEST_ASSERT_EQUAL(second.hunt(ship), TRUE, "After abandoning, the ship could not hunt another")
	TEST_ASSERT(istext(second.abandon(board_test_ship())), "A ship abandoned a hunt it never had")

	// An offer: only its ship takes it, and it doesn't count as the public hunt
	var/datum/criminal_bounty/offer = board_test_posting(1, other)
	TEST_ASSERT(!offer.board_visible_to(ship), "Another ship's offer shows on this ship's board")
	TEST_ASSERT(offer.board_visible_to(other), "An offer doesn't show on its own ship's board")
	TEST_ASSERT(istext(offer.hunt(ship)), "A ship took another ship's offer")
	TEST_ASSERT_EQUAL(offer.hunt(other), TRUE, "The offer's ship could not take it while hunting a public bounty")
	TEST_ASSERT(offer.board_accepted, "A taken offer is not marked taken")
	TEST_ASSERT_EQUAL(SScriminal_bounties.board_public_hunts(other), 1, "Taking an offer counted as a public hunt")

// ===== TURN-IN REFUSALS =====

/// The pad takes only this bounty's criminal, standing free is refused, and the pad must be bolted and aboard (AR-A1, A2, B3)
/datum/unit_test/voidcrew_bounty_board/refusals

/datum/unit_test/voidcrew_bounty_board/refusals/Run()
	var/obj/structure/overmap/ship/ship = board_test_ship()
	var/obj/structure/overmap/ship/other = board_test_ship()
	var/turf/pad_turf = run_loc_floor_bottom_left
	var/turf/aside = locate(pad_turf.x + 2, pad_turf.y, pad_turf.z)
	var/obj/machinery/mission_pad/pad = allocate(/obj/machinery/mission_pad, pad_turf)
	var/datum/criminal_bounty/posting = board_test_posting()
	var/mob/living/basic/bounty_criminal/criminal = board_test_criminal(posting, aside)
	TEST_ASSERT_NOTNULL(criminal, "No criminal was spawned")
	var/list/found = list()

	// A pad that isn't aboard the ship, and one that isn't bolted
	TEST_ASSERT(istext(pad.bounty_turn_in_refusal(ship)), "A pad on the floor of nowhere took a turn-in")
	TEST_ASSERT(istext(posting.turn_in(pad, ship)), "The turn-in went through a pad that isn't aboard")
	pad.set_anchored(FALSE)
	TEST_ASSERT_EQUAL(pad.bounty_turn_in_refusal(ship), "the pad must be bolted down", "An unbolted pad took a turn-in")
	pad.set_anchored(TRUE)

	// Nothing of this bounty's on the pad: a person there is not looked at, and is left alone
	var/mob/living/carbon/human/consistent/bystander = allocate(/mob/living/carbon/human/consistent, pad_turf)
	TEST_ASSERT(istext(posting.board_target_refusal(pad, found)), "The pad took a bystander for the bounty")
	TEST_ASSERT(!QDELETED(bystander) && bystander.loc == pad_turf, "The refused bystander was moved or deleted")

	// Another bounty's criminal is the wrong mob
	var/datum/criminal_bounty/other_posting = board_test_posting()
	var/mob/living/basic/bounty_criminal/wrong = board_test_criminal(other_posting, aside)
	wrong.forceMove(pad_turf)
	TEST_ASSERT(istext(posting.board_target_refusal(pad, found)), "The pad took another bounty's criminal for this one")
	TEST_ASSERT(!QDELETED(wrong), "The wrong criminal was deleted")
	wrong.forceMove(aside)

	// This bounty's criminal, standing free on the pad
	criminal.forceMove(pad_turf)
	TEST_ASSERT_EQUAL(criminal.capture_state(), "free", "A fresh criminal is not free") // BOUNTY_STATE_FREE
	TEST_ASSERT_EQUAL(posting.board_target_refusal(pad, found), "they're standing free, subdue them first", "The pad took a criminal standing free")
	TEST_ASSERT(!QDELETED(criminal) && posting.is_open(), "Refusing a free criminal touched it or the bounty")

	// In a locker on the pad is not on the pad
	var/obj/structure/closet/locker = allocate(/obj/structure/closet, pad_turf)
	criminal.forceMove(locker)
	TEST_ASSERT(istext(posting.board_target_refusal(pad, found)), "The pad took a criminal inside a locker")
	criminal.forceMove(pad_turf)

	// Someone at the controls of the criminal
	var/datum/mind/rider = new("bounty test rider")
	criminal.mind = rider
	TEST_ASSERT_EQUAL(posting.board_target_refusal(pad, found), "the pad won't take them", "The pad took a criminal with a mind")
	criminal.mind = null
	qdel(rider)

	// Dead, it goes: the refusal clears and names the target and its state
	criminal.death()
	criminal.forceMove(pad_turf)
	TEST_ASSERT_NULL(posting.board_target_refusal(pad, found), "The pad refused this bounty's dead criminal")
	TEST_ASSERT_EQUAL(found["target"], criminal, "The pad found the wrong target")
	TEST_ASSERT_EQUAL(found["state"], "dead", "A dead criminal didn't read dead") // BOUNTY_STATE_DEAD

	// Another ship's private offer
	var/datum/criminal_bounty/offer = board_test_posting(1, other)
	TEST_ASSERT_EQUAL(offer.turn_in(pad, ship), "that offer is for another crew", "A ship turned in another ship's offer")
	TEST_ASSERT(offer.is_open(), "Refusing another ship's offer closed it")

// ===== PAY =====

/// Pay by the worst state reached: 100 / 100 / 60 / 25%, vouchers only on a full share (12.1)
/datum/unit_test/voidcrew_bounty_board/pay

/datum/unit_test/voidcrew_bounty_board/pay/Run()
	var/turf/pad_turf = run_loc_floor_bottom_left
	var/obj/machinery/mission_pad/pad = allocate(/obj/machinery/mission_pad, pad_turf)
	var/obj/structure/overmap/ship/ship = board_test_ship()
	// state, worst state, credits, vouchers: a value of 1000 and 1 voucher (VOUCHER_CREDIT_VALUE 1200)
	var/list/cases = list(
		list("restrained", "free", 1000, 1),
		list("stunned", "stunned", 1000, 1),
		list("downed", "downed", 1320, 0),
		list("dead", "dead", 550, 0),
		list("restrained", "downed", 1320, 0),
		list("stunned", "dead", 550, 0),
	)
	for(var/list/pay_case as anything in cases)
		var/datum/criminal_bounty/posting = board_test_posting()
		var/datum/bounty_record/record = posting.record
		var/mob/living/basic/bounty_criminal/criminal = board_test_criminal(posting, pad_turf)
		criminal.worst_state = pay_case[2]
		var/balance_before = ship.ship_account.account_balance
		var/vouchers_before = board_test_vouchers(pad_turf)
		var/list/paid = posting.board_claim(ship, pad, criminal, pay_case[1])
		TEST_ASSERT(islist(paid), "A [pay_case[1]] criminal (worst [pay_case[2]]) was refused: [paid]")
		TEST_ASSERT_EQUAL(paid[1], pay_case[3], "A [pay_case[1]] criminal (worst [pay_case[2]]) paid the wrong credits")
		TEST_ASSERT_EQUAL(paid[2], pay_case[4], "A [pay_case[1]] criminal (worst [pay_case[2]]) paid the wrong vouchers")
		TEST_ASSERT_EQUAL(ship.ship_account.account_balance - balance_before, pay_case[3], "The ship's account didn't get the credits")
		TEST_ASSERT_EQUAL(board_test_vouchers(pad_turf) - vouchers_before, pay_case[4], "The pad didn't get the vouchers")
		TEST_ASSERT(QDELETED(posting), "A claimed bounty stayed up")
		TEST_ASSERT(HAS_TRAIT(criminal, "bounty_removed"), "The claimed criminal isn't marked taken") // TRAIT_BOUNTY_REMOVED
		TEST_ASSERT(HAS_TRAIT(criminal, TRAIT_GODMODE), "The criminal isn't held still for the beam")
		TEST_ASSERT_NULL(bounty_drop_proof(criminal), "A criminal the pad took left proof of death")
		TEST_ASSERT_EQUAL(record.captor_name, ship.name, "The record doesn't name its captor")
		if(pay_case[1] == "dead")
			TEST_ASSERT_EQUAL(record.status, "dead", "A dead catch's record isn't closed dead") // BOUNTY_RECORD_DEAD
			TEST_ASSERT(!(record in GLOB.bounty_prisoner_pool), "A dead catch went to the prisoner pool")
		else
			TEST_ASSERT(record in GLOB.bounty_prisoner_pool, "A live catch didn't go to the prisoner pool")
			GLOB.bounty_prisoner_pool -= record

	// A second press finds it closed: one payment, one record (AR-A7)
	var/datum/criminal_bounty/posting = board_test_posting()
	var/mob/living/basic/bounty_criminal/criminal = board_test_criminal(posting, pad_turf)
	var/balance_before = ship.ship_account.account_balance
	TEST_ASSERT(islist(posting.board_claim(ship, pad, criminal, "restrained")), "The first press was refused")
	TEST_ASSERT(istext(posting.board_claim(ship, pad, criminal, "restrained")), "A second press paid again")
	TEST_ASSERT_EQUAL(ship.ship_account.account_balance - balance_before, 1000, "Two presses paid twice")
	var/pooled = 0
	for(var/datum/bounty_record/pooled_record as anything in GLOB.bounty_prisoner_pool)
		if(pooled_record.captor_name == ship.name)
			pooled++
			GLOB.bounty_prisoner_pool -= pooled_record
	TEST_ASSERT_EQUAL(pooled, 1, "One catch made [pooled] records")

	// A free criminal pays nothing
	var/datum/criminal_bounty/free_posting = board_test_posting()
	var/mob/living/basic/bounty_criminal/free_criminal = board_test_criminal(free_posting, pad_turf)
	TEST_ASSERT(istext(free_posting.board_claim(ship, pad, free_criminal, "free")), "A free criminal was paid for")
	TEST_ASSERT(free_posting.is_open(), "Refusing a free criminal closed the bounty")

// ===== A LIVE CATCH =====

/// A live catch reaches the pool with its captor, its hurt and the capturing crew's own running prison (decision 12)
/datum/unit_test/voidcrew_bounty_board_live_catch
	parent_type = /datum/unit_test/voidcrew_outpost_management

/datum/unit_test/voidcrew_bounty_board_live_catch/New()
	. = ..()
	board_test_begin()

/datum/unit_test/voidcrew_bounty_board_live_catch/Destroy()
	board_test_end()
	return ..()

/datum/unit_test/voidcrew_bounty_board_live_catch/Run()
	var/obj/structure/overmap/dynamic/player_outpost/home = prison_test_claim("bountyowner")
	TEST_ASSERT_NOTNULL(home, "The bounty test prison did not load")
	var/datum/outpost_prison/prison = test_prison(home)
	var/mob/living/carbon/human/owner = make_player(prison_spot(home, 3, 3), "bountyowner")
	home.founder_mind = WEAKREF(owner.mind)

	var/obj/structure/overmap/ship/ship = board_test_ship()
	TEST_ASSERT_NULL(bounty_preferred_prison(ship), "A ship with no prison of its own has a preferred prison")
	var/datum/team/voidcrew/crew = new
	crew.ship = ship
	crew.members |= owner.mind
	LAZYADD(owner.mind.ship_teams, crew)
	ship.ship_team = crew
	TEST_ASSERT_EQUAL(bounty_preferred_prison(ship), prison, "The crew's own running prison is not preferred")

	var/turf/pad_turf = run_loc_floor_bottom_left
	var/obj/machinery/mission_pad/pad = allocate(/obj/machinery/mission_pad, pad_turf)
	var/datum/criminal_bounty/posting = board_test_posting()
	var/datum/bounty_record/record = posting.record
	var/mob/living/basic/bounty_criminal/criminal = board_test_criminal(posting, pad_turf)
	criminal.adjustBruteLoss(round(criminal.maxHealth * 0.1))
	var/hurt = clamp(1 - criminal.health / criminal.maxHealth, 0, 1)
	TEST_ASSERT(islist(posting.board_claim(ship, pad, criminal, "restrained")), "The live catch was refused")
	TEST_ASSERT(record in GLOB.bounty_prisoner_pool, "The live catch didn't reach the prisoner pool")
	TEST_ASSERT_EQUAL(record.preferred_prison?.resolve(), prison, "The record isn't reserved for the crew's own prison")
	TEST_ASSERT_EQUAL(record.captor_ship?.resolve(), ship, "The record doesn't hold its captor ship")
	TEST_ASSERT_EQUAL(record.captor_name, ship.name, "The record doesn't name its captor")
	TEST_ASSERT_EQUAL(record.hurt_fraction, hurt, "The record doesn't carry how hurt they were")
	GLOB.bounty_prisoner_pool -= record

	LAZYREMOVE(owner.mind.ship_teams, crew)
	crew.members -= owner.mind
	ship.ship_team = null
	crew.ship = null
	qdel(crew)
	settle_prison_air(home)

// ===== PROOF AND RELIST =====

/// A destroyed body leaves proof that pays the dead share (AR-A6)
/datum/unit_test/voidcrew_bounty_board/proof

/datum/unit_test/voidcrew_bounty_board/proof/Run()
	var/turf/pad_turf = run_loc_floor_bottom_left
	var/turf/aside = locate(pad_turf.x + 2, pad_turf.y, pad_turf.z)
	var/obj/machinery/mission_pad/pad = allocate(/obj/machinery/mission_pad, pad_turf)
	var/obj/structure/overmap/ship/ship = board_test_ship()
	var/datum/criminal_bounty/posting = board_test_posting()
	var/mob/living/basic/bounty_criminal/criminal = board_test_criminal(posting, aside)
	var/obj/item/bounty_proof/proof = bounty_drop_proof(criminal)
	TEST_ASSERT_NOTNULL(proof, "A destroyed criminal left no proof")
	TEST_ASSERT_EQUAL(proof.loc, aside, "The proof isn't where the criminal was")
	TEST_ASSERT_EQUAL(proof.posting_ref?.resolve(), posting, "The proof isn't bound to its bounty")
	TEST_ASSERT_EQUAL(bounty_drop_proof(criminal), proof, "A second destruction made a second proof")
	qdel(criminal)
	sleep(2 SECONDS)
	TEST_ASSERT(posting.is_open() && !posting.board_relisting, "The bounty didn't stay up on its proof")

	proof.forceMove(pad_turf)
	var/balance_before = ship.ship_account.account_balance
	var/list/found = list()
	TEST_ASSERT_NULL(posting.board_target_refusal(pad, found), "The pad refused the proof")
	TEST_ASSERT_EQUAL(found["state"], "dead", "The proof didn't read dead") // BOUNTY_STATE_DEAD
	var/list/paid = posting.board_claim(ship, pad, found["target"], found["state"])
	TEST_ASSERT(islist(paid), "The proof was refused: [paid]")
	// 25% of 1000 + one voucher's 1200 (BOUNTY_SHARE_DEAD, VOUCHER_CREDIT_VALUE)
	TEST_ASSERT_EQUAL(ship.ship_account.account_balance - balance_before, 550, "The proof didn't pay the dead share")
	TEST_ASSERT(QDELETED(proof), "The pad left the proof behind")
	TEST_ASSERT(QDELETED(posting), "The bounty stayed up after its proof was turned in")

/// A criminal destroyed with nothing left relists at a new site after a delay, and never fails silently (AR-A6)
/datum/unit_test/voidcrew_bounty_board/relist

/datum/unit_test/voidcrew_bounty_board/relist/Run()
	var/obj/structure/overmap/ship/ship = board_test_ship()
	var/obj/structure/overmap/space_ruin/old_ruin = allocate(/obj/structure/overmap/space_ruin, outpost_lead_overmap_turf(44, 44))
	allocate(/obj/structure/overmap/space_ruin, outpost_lead_overmap_turf(48, 44))
	var/datum/criminal_bounty/posting = board_test_posting()
	posting.placement_kind = "ruin" // BOUNTY_PLACEMENT_RUIN
	posting.board_set_site(old_ruin)
	TEST_ASSERT_EQUAL(posting.hunt(ship), TRUE, "The ship could not hunt the bounty")
	TEST_ASSERT_NOTNULL(ship.get_waypoint("wanted_[REF(posting)]"), "Hunting didn't chart the site on the helm")
	var/turf/aside = locate(run_loc_floor_bottom_left.x + 2, run_loc_floor_bottom_left.y, run_loc_floor_bottom_left.z)
	var/mob/living/basic/bounty_criminal/criminal = board_test_criminal(posting, aside)
	var/expires_before = posting.expires_at
	qdel(criminal)
	sleep(2 SECONDS)
	TEST_ASSERT(posting.is_open(), "A bounty whose criminal was lost failed")
	TEST_ASSERT(posting.board_relisting, "A bounty whose criminal was lost didn't relist")
	TEST_ASSERT_NULL(posting.site(), "A relisting bounty kept its old site")
	TEST_ASSERT_NULL(ship.get_waypoint("wanted_[REF(posting)]"), "A relisting bounty kept the hunter's waypoint")
	TEST_ASSERT(posting.board_relist_at >= world.time + 4 MINUTES, "The relist doesn't wait 5 minutes") // BOUNTY_RELIST_DELAY
	TEST_ASSERT(posting.expires_at >= expires_before + 5 MINUTES, "The relist delay ate the clock")
	TEST_ASSERT(posting.is_hunting(ship), "The hunter lost its hunt to the relist")

	// The delay is over: a new site, never the old one, and the hunter's waypoint back
	posting.board_relist_at = world.time
	posting.board_process(0)
	if(!posting.is_open())
		TEST_NOTICE(src, "No site anywhere to relist at; the bounty closed")
		return
	TEST_ASSERT(!posting.board_relisting, "The bounty didn't list again when the delay was over")
	TEST_ASSERT_NOTNULL(posting.site(), "The relisted bounty has no site")
	TEST_ASSERT(posting.site() != old_ruin, "The bounty relisted where it was lost")
	TEST_ASSERT_NOTNULL(ship.get_waypoint("wanted_[REF(posting)]"), "The hunter didn't get the new waypoint")

// ===== CLOSING =====

/// close() removes the criminal, companions, decoys, marker and field protection, frees every hunt, and is safe twice (AR-G3, A7)
/datum/unit_test/voidcrew_bounty_board/close

/datum/unit_test/voidcrew_bounty_board/close/Run()
	var/obj/structure/overmap/ship/ship = board_test_ship()
	var/turf/spot = locate(run_loc_floor_bottom_left.x + 2, run_loc_floor_bottom_left.y + 2, run_loc_floor_bottom_left.z)
	var/datum/criminal_bounty/posting = board_test_posting()
	TEST_ASSERT_EQUAL(posting.hunt(ship), TRUE, "The ship could not hunt the bounty")
	var/mob/living/basic/bounty_criminal/criminal = board_test_criminal(posting, spot)
	ADD_TRAIT(criminal, "mission_field_mob", "bounty") // TRAIT_MISSION_FIELD_MOB, BOUNTY_TRAIT
	var/mob/living/basic/bounty_companion/companion = new(spot)
	posting.companions |= WEAKREF(companion)
	var/mob/living/basic/bounty_criminal/decoy/decoy = new(spot)
	posting.decoys |= WEAKREF(decoy)
	TEST_ASSERT(posting.board_move_sighting(TRUE), "The sighting marker wasn't placed")
	var/obj/effect/bounty_sighting/marker = posting.marker
	TEST_ASSERT_NOTNULL(marker, "There is no sighting marker")
	TEST_ASSERT(get_dist(marker, criminal) <= 5, "The sighting is further than 5 tiles off") // BOUNTY_SIGHTING_OFFSET
	// It moves again only after BOUNTY_SIGHTING_INTERVAL (120 s), unless forced
	TEST_ASSERT(posting.board_next_sighting >= world.time + 119 SECONDS, "The sighting doesn't wait 120 seconds to move again")
	TEST_ASSERT(!posting.board_move_sighting(), "The sighting moved again before its interval")

	// The GPS points at the marker, never the mob (AR-C3)
	var/obj/item/gps/gps = allocate(/obj/item/gps, spot)
	var/datum/component/gps/item/unit = gps.GetComponent(/datum/component/gps/item)
	TEST_ASSERT_EQUAL(bounty_link_gps(ship, unit), 1, "The hunter's GPS didn't get the sighting")
	var/tag = posting.board_gps_tag
	var/datum/weakref/tracked = LAZYACCESS(unit.linked_mission_signals, tag)
	TEST_ASSERT_EQUAL(tracked?.resolve(), marker, "The GPS tracks something other than the marker")
	TEST_ASSERT_EQUAL(bounty_link_gps(board_test_ship(), unit), 0, "A ship not hunting it got the sighting")

	var/received = FALSE
	RegisterSignal(posting, "bounty_posting_closed", PROC_REF(board_test_heard_close)) // COMSIG_BOUNTY_POSTING_CLOSED
	TEST_ASSERT(posting.close("admin"), "The first close didn't close it")
	received = board_test_close_heard
	TEST_ASSERT(received, "Closing sent no COMSIG_BOUNTY_POSTING_CLOSED")
	TEST_ASSERT(QDELETED(criminal), "Closing left the criminal")
	TEST_ASSERT(QDELETED(companion), "Closing left a companion")
	TEST_ASSERT(QDELETED(decoy), "Closing left a decoy")
	TEST_ASSERT(QDELETED(marker), "Closing left the sighting marker")
	TEST_ASSERT(!HAS_TRAIT(criminal, "mission_field_mob"), "Closing left the field protection on") // TRAIT_MISSION_FIELD_MOB
	TEST_ASSERT(!(posting in GLOB.criminal_bounties), "Closing left it on the board")
	TEST_ASSERT_NULL(ship.get_waypoint("wanted_[REF(posting)]"), "Closing left the hunter's waypoint")
	TEST_ASSERT_NULL(LAZYACCESS(unit.linked_mission_signals, tag), "Closing left the GPS beacon")
	TEST_ASSERT(!posting.close("admin"), "A second close did something")

/datum/unit_test/voidcrew_bounty_board/close
	/// Whether the closing signal was heard
	var/board_test_close_heard = FALSE

/datum/unit_test/voidcrew_bounty_board/close/proc/board_test_heard_close(datum/source, reason, winner)
	SIGNAL_HANDLER
	board_test_close_heard = TRUE

// ===== OLD WAYS OUT =====

/// A bluespace body bag won't fold with a living criminal inside, and a player bounty offer won't send a living mob (AR-E7, H1)
/datum/unit_test/voidcrew_bounty_board/guards

/datum/unit_test/voidcrew_bounty_board/guards/Run()
	var/turf/spot = locate(run_loc_floor_bottom_left.x + 1, run_loc_floor_bottom_left.y + 1, run_loc_floor_bottom_left.z)
	var/obj/structure/closet/body_bag/bluespace/bag = allocate(/obj/structure/closet/body_bag/bluespace, spot)
	TEST_ASSERT(!bounty_blocks_bag_fold(bag, null), "An empty bag won't fold")
	var/datum/criminal_bounty/posting = board_test_posting()
	var/mob/living/basic/bounty_criminal/criminal = board_test_criminal(posting, spot)
	criminal.forceMove(bag)
	TEST_ASSERT(bounty_blocks_bag_fold(bag, null), "A bag folded with a living criminal inside")
	criminal.death()
	TEST_ASSERT(!bounty_blocks_bag_fold(bag, null), "A bag won't fold with a dead criminal inside")

	var/obj/item/bodybag/bluespace/folded = allocate(/obj/item/bodybag/bluespace, spot)
	var/mob/living/basic/mouse/mouse = allocate(/mob/living/basic/mouse, spot)
	TEST_ASSERT_NULL(bounty_offer_refusal(list(folded)), "An empty folded bag was refused")
	mouse.forceMove(folded)
	TEST_ASSERT(istext(bounty_offer_refusal(list(folded))), "An offer sent a living mob inside an item")
	mouse.death()
	TEST_ASSERT_NULL(bounty_offer_refusal(list(folded)), "An offer refused a dead mob")

// ===== THE BOARD'S DATA =====

/// `wanted` and `wanted_hunt` per the data contract, every key there, and no picture in the live data (spec 11, AR-G1)
/datum/unit_test/voidcrew_bounty_board/ui_data

/datum/unit_test/voidcrew_bounty_board/ui_data/Run()
	var/obj/structure/overmap/ship/ship = board_test_ship()
	var/obj/structure/overmap/ship/other = board_test_ship()
	var/obj/machinery/computer/mission_board/console = allocate(/obj/machinery/computer/mission_board)
	var/datum/criminal_bounty/hunted = board_test_posting(3)
	var/datum/criminal_bounty/offer = board_test_posting(1, ship)
	var/datum/criminal_bounty/elsewhere = board_test_posting(1, other)
	TEST_ASSERT_EQUAL(hunted.hunt(ship), TRUE, "The ship could not hunt the bounty")

	var/list/data = list()
	console.board_add_wanted_data(data, ship, null)
	TEST_ASSERT(islist(data["wanted"]), "There is no wanted list")
	TEST_ASSERT("wanted_hunt" in data, "There is no wanted_hunt")
	TEST_ASSERT_EQUAL(data["wanted_hunt"], REF(hunted), "wanted_hunt isn't the ship's hunt")
	var/list/refs = list()
	var/list/contract = list("ref", "name", "alias", "species", "sex", "tier", "hint", "place", "zone", "mugshot_id", "value", "shares", "time_left", "status", "private", "hunting_by_us", "hunters", "can_turn_in", "turn_in_state")
	for(var/list/entry as anything in data["wanted"])
		refs += entry["ref"]
		for(var/key in contract)
			TEST_ASSERT(key in entry, "A wanted entry has no [key]")
		TEST_ASSERT(!("mugshot" in entry), "A wanted entry carries its mugshot in the live data")
		TEST_ASSERT(istext(entry["pay_note"]) && findtext(entry["pay_note"], "stun"), "A wanted card has no stun weapon hint")
		TEST_ASSERT_EQUAL(length(entry["shares"]), 3, "A wanted entry's shares are not three numbers")
		for(var/key in entry)
			var/entry_value = entry[key]
			TEST_ASSERT(!istext(entry_value) || length(entry_value) < 500, "The wanted entry's [key] is [length(entry_value)] characters, an image in the live data")
	TEST_ASSERT(REF(hunted) in refs, "The public bounty isn't listed")
	TEST_ASSERT(REF(offer) in refs, "The ship's own offer isn't listed")
	TEST_ASSERT(!(REF(elsewhere) in refs), "Another ship's offer is listed")

	for(var/list/entry as anything in data["wanted"])
		if(entry["ref"] != REF(hunted))
			continue
		TEST_ASSERT(entry["hunting_by_us"], "The hunted bounty doesn't say the ship hunts it")
		TEST_ASSERT_EQUAL(entry["hunters"], 1, "The hunted bounty doesn't count its hunter")
		TEST_ASSERT_EQUAL(entry["crew_note"], "Crew of 2+ recommended", "A green most wanted card doesn't recommend a crew of 2")
		TEST_ASSERT(!entry["can_turn_in"], "A bounty with nothing on a pad can be turned in")

	// The mugshots are static data, keyed by record id
	var/list/mugshots = console.board_wanted_mugshots(ship)
	TEST_ASSERT(hunted.record.id in mugshots, "The static data has no mugshot for the hunted bounty")
	TEST_ASSERT(!(elsewhere.record.id in mugshots), "The static data has another ship's offer's mugshot")

// ===== A REAL SHIP =====

/// On a real hull: the pad aboard and bolted takes the turn-in, and the ship's account is paid (AR-A2)
/datum/unit_test/voidcrew_bounty_board/aboard
	/// The hull the test built
	var/obj/structure/overmap/ship/board_test_hull

/datum/unit_test/voidcrew_bounty_board/aboard/Destroy()
	if(!QDELETED(board_test_hull))
		qdel(board_test_hull)
	board_test_hull = null
	return ..()

/datum/unit_test/voidcrew_bounty_board/aboard/Run()
	var/obj/structure/overmap/ship/ship = SSshuttle.create_ship(/datum/map_template/shuttle/voidcrew/box)
	TEST_ASSERT_NOTNULL(ship, "The test hull did not load")
	board_test_hull = ship
	var/turf/deck
	for(var/turf/tile as anything in ship.shuttle.return_turfs())
		if(isfloorturf(tile) && (get_area(tile) in ship.shuttle.shuttle_areas) && !tile.is_blocked_turf(exclude_mobs = TRUE) && !(locate(/obj/machinery) in tile))
			deck = tile
			break
	TEST_ASSERT_NOTNULL(deck, "The test hull has no free deck")
	var/obj/machinery/mission_pad/pad = new(deck)
	TEST_ASSERT_NULL(pad.bounty_turn_in_refusal(ship), "A bolted pad aboard refused its own ship: [pad.bounty_turn_in_refusal(ship)]")
	TEST_ASSERT(istext(pad.bounty_turn_in_refusal(board_test_ship())), "A pad aboard one ship took another ship's turn-in")
	pad.set_anchored(FALSE)
	TEST_ASSERT(istext(pad.bounty_turn_in_refusal(ship)), "An unbolted pad aboard took a turn-in")
	pad.set_anchored(TRUE)

	var/datum/criminal_bounty/posting = board_test_posting()
	var/mob/living/basic/bounty_criminal/criminal = board_test_criminal(posting, deck)
	criminal.death()
	criminal.forceMove(deck)
	var/balance_before = ship.ship_account.account_balance
	var/list/paid = posting.turn_in(pad, ship)
	TEST_ASSERT(islist(paid), "The pad aboard refused a dead criminal on it: [paid]")
	TEST_ASSERT_EQUAL(ship.ship_account.account_balance - balance_before, 550, "The turn-in didn't pay the dead share") // BOUNTY_SHARE_DEAD of 1000 + 1200
	TEST_ASSERT(QDELETED(posting), "The bounty stayed up after its turn-in")
	TEST_ASSERT(HAS_TRAIT(criminal, "bounty_removed"), "The pad didn't take the criminal") // TRAIT_BOUNTY_REMOVED
	qdel(pad)
