/**
 * Bounty hunting: P3 AI's tests, for voidcrew/modules/bounties/bounty_ai*.dm, bounty_activities.dm and bounty_companions.dm.
 *
 * Owner: P3 AI. Do not edit this file outside that package. P0 left a skeleton test here for the
 * package to replace with its own. Fork defines are included after the tests, so a test uses the
 * literal value with a comment naming the define.
 */
/datum/unit_test/voidcrew_bounty_ai_skeleton

/datum/unit_test/voidcrew_bounty_ai_skeleton/Run()
	TEST_ASSERT(ispath(/mob/living/basic/bounty_companion), "The companion type is missing")
