/**
 * Bounty hunting: P1 identity's tests, for voidcrew/modules/bounties/bounty_identity.dm and bounty_looks.dm.
 *
 * Owner: P1 identity. Do not edit this file outside that package. P0 left a skeleton test here for the
 * package to replace with its own. Fork defines are included after the tests, so a test uses the
 * literal value with a comment naming the define.
 */
/datum/unit_test/voidcrew_bounty_identity_skeleton

/datum/unit_test/voidcrew_bounty_identity_skeleton/Run()
	TEST_ASSERT(ispath(/datum/bounty_look), "The bounty look type is missing")
