/**
 * Bounty hunting: P4 bosses's tests, for voidcrew/modules/bounties/bounty_boss.dm and bounty_boss_kits.dm.
 *
 * Owner: P4 bosses. Do not edit this file outside that package. P0 left a skeleton test here for the
 * package to replace with its own. Fork defines are included after the tests, so a test uses the
 * literal value with a comment naming the define.
 */
/datum/unit_test/voidcrew_bounty_bosses_skeleton

/datum/unit_test/voidcrew_bounty_bosses_skeleton/Run()
	TEST_ASSERT(ispath(/mob/living/basic/bounty_criminal/boss/juggernaut), "The Juggernaut type is missing")
