/**
 * Bounty hunting: P6 outposts's tests, for voidcrew/modules/bounties/bounty_outpost.dm.
 *
 * Owner: P6 outposts. Do not edit this file outside that package. P0 left a skeleton test here for the
 * package to replace with its own. Fork defines are included after the tests, so a test uses the
 * literal value with a comment naming the define.
 */
/datum/unit_test/voidcrew_bounty_outpost_skeleton

/datum/unit_test/voidcrew_bounty_outpost_skeleton/Run()
	TEST_ASSERT(ispath(/mob/living/basic/bounty_criminal/decoy), "The decoy type is missing")
