/**
 * Bounty hunting: P6 outposts's tests, for voidcrew/modules/bounties/bounty_outpost.dm.
 *
 * Owner: P6 outposts. Do not edit this file outside that package. Fork defines are included after
 * the tests, so a test uses the literal value with a comment naming the define.
 *
 * The tests make a trader outpost out of the test room and drive the procs directly. They pin what
 * the other packages give back where it matters (a test fugitive that records being confronted, a
 * test posting that records being relisted), so they hold with P0's stubs and with the real
 * packages alike.
 */

/// A fugitive that remembers who confronted it
/mob/living/basic/bounty_criminal/meek/outpost_test
	/// Whoever on_confronted() was last called with
	var/confronted_by

/mob/living/basic/bounty_criminal/meek/outpost_test/on_confronted(mob/user)
	confronted_by = user
	return ..()

/// A posting that remembers being relisted, and doesn't go anywhere
/datum/criminal_bounty/outpost_test
	/// The reason relist() was last called with
	var/relisted_for

/datum/criminal_bounty/outpost_test/relist(reason)
	relisted_for = reason

/// A trader outpost made of the test room, and postings there
/datum/unit_test/voidcrew_bounty_outpost
	abstract_type = /datum/unit_test/voidcrew_bounty_outpost
	/// The outpost the test room stands in for
	var/obj/structure/overmap/trader_outpost/outpost

/datum/unit_test/voidcrew_bounty_outpost/Destroy()
	GLOB.criminal_bounties -= allocated
	return ..()

/// A trader outpost whose concourse is the test room
/datum/unit_test/voidcrew_bounty_outpost/proc/make_outpost(outpost_type = /obj/structure/overmap/trader_outpost)
	var/obj/structure/overmap/trader_outpost/new_outpost = allocate(outpost_type)
	new_outpost.outpost_template = allocate(/datum/map_template/trader_outpost)
	new_outpost.outpost_template.width = run_loc_floor_top_right.x - run_loc_floor_bottom_left.x + 1
	new_outpost.outpost_template.height = run_loc_floor_top_right.y - run_loc_floor_bottom_left.y + 1
	new_outpost.template_bottom_left = run_loc_floor_bottom_left
	return new_outpost

/// An open trader-outpost posting at `outpost` with its fugitive standing at `where`
/datum/unit_test/voidcrew_bounty_outpost/proc/make_posting(turf/where, fugitive_type = /mob/living/basic/bounty_criminal/meek/outpost_test)
	var/datum/bounty_record/record = generate_bounty_record(1, "meek", "trader_outpost") // BOUNTY_TIER_PETTY, BOUNTY_ARCHETYPE_MEEK, BOUNTY_PLACEMENT_TRADER_OUTPOST
	var/datum/criminal_bounty/outpost_test/posting = allocate(/datum/criminal_bounty/outpost_test)
	posting.record = record
	posting.placement_kind = "trader_outpost" // BOUNTY_PLACEMENT_TRADER_OUTPOST
	posting.site_ref = WEAKREF(outpost)
	posting.value = 1234
	var/mob/living/basic/bounty_criminal/fugitive = allocate(fugitive_type, where || run_loc_floor_bottom_left)
	fugitive.record = record
	fugitive.posting_ref = WEAKREF(posting)
	posting.criminal_ref = WEAKREF(fugitive)
	GLOB.criminal_bounties += posting
	return posting

/// A person with a mind, crewing `ship` if given
/datum/unit_test/voidcrew_bounty_outpost/proc/make_hunter(obj/structure/overmap/ship/ship)
	var/mob/living/carbon/human/hunter = allocate(/mob/living/carbon/human/consistent)
	hunter.mind_initialize()
	allocated += hunter.mind
	if(ship)
		var/datum/team/voidcrew/team = allocate(/datum/team/voidcrew)
		team.ship = ship
		hunter.mind.ship_teams = list(team)
	return hunter

/// The posting's decoys, resolved
/datum/unit_test/voidcrew_bounty_outpost/proc/decoys_of(datum/criminal_bounty/posting)
	. = list()
	for(var/datum/weakref/decoy_ref as anything in posting.decoys)
		var/mob/living/basic/bounty_criminal/decoy/decoy = decoy_ref?.resolve()
		if(decoy)
			. += decoy

/// Setting up: the fugitive blends in, three decoys share one or two of its features, and an outpost takes at most two fugitives and never a mini-boss
/datum/unit_test/voidcrew_bounty_outpost/blend

/datum/unit_test/voidcrew_bounty_outpost/blend/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "A trader-outpost posting could not be set up to blend in")
	TEST_ASSERT(fugitive.blended, "The fugitive is not blending in")

	var/list/decoys = decoys_of(posting)
	TEST_ASSERT_EQUAL(length(decoys), 3, "The fugitive did not get three decoys") // BOUNTY_DECOY_COUNT
	TEST_ASSERT_EQUAL(length(posting.outpost_decoy_shares), 3, "The decoys' shared features were not recorded")
	var/list/wanted_features = posting.record.features
	for(var/shared in posting.outpost_decoy_shares)
		TEST_ASSERT(shared >= 1 && shared <= 2, "A decoy was made to share [shared] features, not one or two")
		if(length(wanted_features))
			TEST_ASSERT(shared < length(wanted_features), "A decoy was made to share all [length(wanted_features)] of the fugitive's features")
	for(var/mob/living/basic/bounty_criminal/decoy/decoy as anything in decoys)
		TEST_ASSERT(decoy.blended, "A decoy is not blending in")
		TEST_ASSERT(decoy.record && decoy.record != posting.record, "A decoy has no record of its own")
		TEST_ASSERT_NULL(decoy.posting_ref, "A decoy is linked to the posting as if it were the criminal")
		TEST_ASSERT(decoy.loc != fugitive.loc, "A decoy spawned on the fugitive")
		// With P1's real records, check what make_decoy_record() gave back too
		var/list/decoy_features = decoy.record.features
		if(length(wanted_features) && length(decoy_features))
			var/shared = length(decoy_features & wanted_features)
			TEST_ASSERT(shared >= 1 && shared <= 2 && shared < length(wanted_features), "A decoy shares [shared] of the fugitive's [length(wanted_features)] features")

	// At most two fugitives at one outpost, and never a mini-boss (AR-C9)
	var/datum/criminal_bounty/outpost_test/second = make_posting(run_loc_floor_top_right)
	TEST_ASSERT(second.setup_outpost_blend(), "A second fugitive was refused at the outpost")
	var/datum/criminal_bounty/outpost_test/third = make_posting(run_loc_floor_top_right)
	TEST_ASSERT(!third.setup_outpost_blend(), "A third fugitive was let into one outpost")
	var/datum/criminal_bounty/outpost_test/boss_posting = make_posting(run_loc_floor_top_right, /mob/living/basic/bounty_criminal/boss)
	boss_posting.record.archetype = "boss" // BOUNTY_ARCHETYPE_BOSS
	second.status = "closed" // BOUNTY_POSTING_CLOSED: the outpost has room again
	TEST_ASSERT(!boss_posting.setup_outpost_blend(), "A mini-boss was set up at a trader outpost")
	TEST_ASSERT(third.setup_outpost_blend(), "A closed posting still counted against the outpost's fugitives")

/// The fugitive and its decoys look alike to a player: the same generic name, never the alias, and the same examine, body and speed
/datum/unit_test/voidcrew_bounty_outpost/names

/datum/unit_test/voidcrew_bounty_outpost/names/Run()
	outpost = make_outpost(/obj/structure/overmap/trader_outpost/outfitter)
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT(length(decoys), "No decoys to compare with")
	var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[1]

	TEST_ASSERT_EQUAL(fugitive.name, "dockhand", "The fugitive at the outfitter is not called a dockhand")
	TEST_ASSERT_EQUAL(decoy.name, fugitive.name, "A decoy's name differs from the fugitive's")
	TEST_ASSERT_EQUAL(decoy.real_name, fugitive.real_name, "A decoy's voice name differs from the fugitive's")
	TEST_ASSERT(fugitive.name != posting.record.name && fugitive.name != posting.record.alias, "The fugitive shows its name or alias")
	TEST_ASSERT_EQUAL(decoy.desc, fugitive.desc, "A decoy's description differs from the fugitive's")
	TEST_ASSERT_EQUAL(decoy.maxHealth, fugitive.maxHealth, "A decoy's health differs from the fugitive's")
	TEST_ASSERT_EQUAL(decoy.move_resist, fugitive.move_resist, "A decoy's move resistance differs from the fugitive's")
	TEST_ASSERT_EQUAL(decoy.cached_multiplicative_slowdown, fugitive.cached_multiplicative_slowdown, "A decoy's speed differs from the fugitive's")

	// Examine: the same lines once the feature lines and pictures are taken out
	decoy.gender = fugitive.gender
	var/mob/living/carbon/human/viewer = make_hunter()
	var/list/fugitive_lines = list()
	for(var/line in fugitive.examine(viewer) - fugitive.record.feature_lines())
		fugitive_lines += trim(STRIP_HTML_FULL("[line]", MAX_MESSAGE_LEN))
	var/list/decoy_lines = list()
	for(var/line in decoy.examine(viewer) - decoy.record.feature_lines())
		decoy_lines += trim(STRIP_HTML_FULL("[line]", MAX_MESSAGE_LEN))
	TEST_ASSERT_EQUAL(fugitive_lines.Join(" | "), decoy_lines.Join(" | "), "A decoy examines differently from the fugitive")

	// The other zones' names
	TEST_ASSERT_EQUAL(bounty_outpost_display_name(allocate(/obj/structure/overmap/trader_outpost/general)), "patron", "Halcyon's crowd is not patrons")
	TEST_ASSERT_EQUAL(bounty_outpost_display_name(allocate(/obj/structure/overmap/trader_outpost/black_market)), "spacer", "The Undertow's crowd is not spacers")

/// The warrant: on a decoy it raises the alert, on the fugitive it confronts it, and a ship waits between warrants
/datum/unit_test/voidcrew_bounty_outpost/warrant

/datum/unit_test/voidcrew_bounty_outpost/warrant/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/meek/outpost_test/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT(length(decoys) >= 2, "Too few decoys to test with")
	var/obj/structure/overmap/ship/ship = allocate(/obj/structure/overmap/ship)
	var/mob/living/carbon/human/hunter = make_hunter(ship)
	var/obj/item/paper/bounty_warrant/warrant = allocate(/obj/item/paper/bounty_warrant)
	warrant.posting_ref = WEAKREF(posting)

	// A shopper shown the warrant: nothing happens, and it costs no wait
	var/mob/living/carbon/human/shopper = make_hunter()
	warrant.show_warrant(shopper, hunter)
	TEST_ASSERT_EQUAL(posting.alert, 0, "Showing the warrant to a shopper raised the alert")
	TEST_ASSERT_EQUAL(posting.outpost_warrant_wait(hunter), 0, "Showing the warrant to a shopper started the wait")

	// A decoy: it protests, and the alert rises
	var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[1]
	warrant.show_warrant(decoy, hunter)
	TEST_ASSERT_EQUAL(posting.alert, 1, "A wrong warrant did not raise the alert")
	TEST_ASSERT(decoy.blended, "A decoy stopped blending in after a wrong warrant")

	// The ship waits 30 seconds (BOUNTY_WARRANT_COOLDOWN) before the next one, whoever shows it
	TEST_ASSERT(posting.outpost_warrant_wait(hunter) > 0, "A wrong warrant started no wait")
	var/mob/living/carbon/human/crewmate = make_hunter(ship)
	warrant.show_warrant(fugitive, crewmate)
	TEST_ASSERT_NULL(fugitive.confronted_by, "A crewmate got round the ship's warrant wait")
	// Another ship does not wait on this one
	var/mob/living/carbon/human/rival = make_hunter(allocate(/obj/structure/overmap/ship))
	TEST_ASSERT_EQUAL(posting.outpost_warrant_wait(rival), 0, "One ship's warrant made another ship wait")

	// The fugitive: confronted, exposed and holding a grudge
	posting.outpost_warrant_ready_at.Cut()
	warrant.show_warrant(fugitive, hunter)
	TEST_ASSERT_EQUAL(fugitive.confronted_by, hunter, "The right warrant did not confront the fugitive")
	TEST_ASSERT(!fugitive.blended, "The fugitive kept blending in after being confronted")
	TEST_ASSERT(WEAKREF(hunter) in fugitive.grudge, "The fugitive does not hold a grudge against whoever confronted it")
	TEST_ASSERT(!HAS_TRAIT_FROM(fugitive, "no_containment", "bounty_outpost"), "An exposed fugitive still can't be put in a locker") // TRAIT_NO_CONTAINMENT, BOUNTY_OUTPOST_TRAIT
	TEST_ASSERT_EQUAL(posting.alert, 1, "Confronting the right person raised the alert")

	// A closed posting's warrant does nothing
	posting.outpost_warrant_ready_at.Cut()
	posting.status = "closed" // BOUNTY_POSTING_CLOSED
	warrant.show_warrant(decoys[2], hunter)
	TEST_ASSERT_EQUAL(posting.alert, 1, "An out-of-date warrant raised the alert")

/// Two alerts: the fugitive and its decoys walk out and the bounty relists; an exposed fugitive stays
/datum/unit_test/voidcrew_bounty_outpost/alert

/datum/unit_test/voidcrew_bounty_outpost/alert/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)

	TEST_ASSERT(posting.raise_alert("a test"), "The alert did not rise")
	TEST_ASSERT_EQUAL(posting.alert, 1, "The first alert did not count")
	TEST_ASSERT_NULL(posting.relisted_for, "The bounty relisted at the first alert")
	TEST_ASSERT(posting.raise_alert("a test"), "The alert did not rise a second time")
	TEST_ASSERT_NOTNULL(posting.relisted_for, "Two alerts did not relist the bounty") // BOUNTY_OUTPOST_ALERT_SLIP
	TEST_ASSERT_NULL(posting.criminal(), "The posting kept hold of a fugitive that slipped away")
	TEST_ASSERT_NULL(fugitive.posting_ref, "A fugitive that slipped away still points at the posting")
	TEST_ASSERT_EQUAL(length(posting.decoys), 0, "The posting kept hold of its decoys")
	TEST_ASSERT(fugitive.GetComponent(/datum/component/bounty_outpost_exit), "The fugitive did not leave")
	for(var/mob/living/basic/bounty_criminal/decoy/decoy as anything in decoys)
		TEST_ASSERT(decoy.GetComponent(/datum/component/bounty_outpost_exit), "A decoy did not leave with the fugitive")

	// Once exposed, the chase is on: no more slipping away
	var/datum/criminal_bounty/outpost_test/exposed = make_posting(run_loc_floor_top_right)
	var/mob/living/basic/bounty_criminal/exposed_fugitive = exposed.criminal()
	TEST_ASSERT(exposed.setup_outpost_blend(), "The second posting could not be set up to blend in")
	exposed.outpost_confront(exposed_fugitive, make_hunter())
	exposed.raise_alert("a test")
	exposed.raise_alert("a test")
	TEST_ASSERT_NULL(exposed.relisted_for, "An exposed fugitive slipped away")
	TEST_ASSERT_EQUAL(exposed.criminal(), exposed_fugitive, "An exposed fugitive was let go")

	// Only trader-outpost postings have an alert
	var/datum/criminal_bounty/outpost_test/planet = make_posting(run_loc_floor_top_right)
	planet.placement_kind = "planet" // BOUNTY_PLACEMENT_PLANET
	TEST_ASSERT(!planet.raise_alert("a test"), "A planet bounty's alert rose")

/// A deliberate hit on a decoy is an outpost strike and raises the alert; hitting the fugitive only exposes it
/datum/unit_test/voidcrew_bounty_outpost/decoy_hit

/datum/unit_test/voidcrew_bounty_outpost/decoy_hit/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT(length(decoys) >= 2, "Too few decoys to test with")
	var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[1]

	// Someone with no mind behind them never counts
	var/mob/living/carbon/human/npc = allocate(/mob/living/carbon/human/consistent)
	npc.combat_mode = TRUE
	decoy.attack_hand(npc, list())
	TEST_ASSERT_EQUAL(posting.alert, 0, "A mindless hit on a decoy raised the alert")

	// A friendly touch never counts
	var/mob/living/carbon/human/hunter = make_hunter()
	decoy.attack_hand(hunter, list())
	TEST_ASSERT_EQUAL(posting.alert, 0, "Patting a decoy raised the alert")
	TEST_ASSERT_NULL(outpost.aggressor_strikes[hunter.mind], "Patting a decoy was an outpost strike")

	// A punch is a strike and an alert
	hunter.combat_mode = TRUE
	decoy.attack_hand(hunter, list())
	TEST_ASSERT_EQUAL(outpost.aggressor_strikes[hunter.mind], 1, "Punching a decoy was not an outpost strike")
	TEST_ASSERT_EQUAL(posting.alert, 1, "Punching a decoy did not raise the alert")

	// A shot aimed at a decoy counts; a shot at someone else passes through it
	var/mob/living/carbon/human/shooter = make_hunter()
	var/obj/projectile/bullet/stray = allocate(/obj/projectile/bullet)
	stray.firer = shooter
	stray.original = hunter
	var/mob/living/basic/bounty_criminal/decoy/other_decoy = decoys[2]
	TEST_ASSERT(SEND_SIGNAL(other_decoy, COMSIG_PROJECTILE_PREHIT, stray) & PROJECTILE_INTERRUPT_HIT_PHASE, "A shot at someone else hit a decoy")
	TEST_ASSERT_EQUAL(posting.alert, 1, "A stray shot through a decoy raised the alert")
	var/obj/projectile/bullet/aimed = allocate(/obj/projectile/bullet)
	aimed.firer = shooter
	aimed.original = other_decoy
	TEST_ASSERT(!(SEND_SIGNAL(other_decoy, COMSIG_PROJECTILE_PREHIT, aimed) & PROJECTILE_INTERRUPT_HIT_PHASE), "A shot aimed at a decoy passed through it")
	TEST_ASSERT_EQUAL(outpost.aggressor_strikes[shooter.mind], 1, "Shooting a decoy was not an outpost strike")
	TEST_ASSERT_NOTNULL(posting.relisted_for, "Two hits on decoys did not send the fugitive away")

	// Hitting the (next) fugitive exposes it: no strike, no alert
	var/datum/criminal_bounty/outpost_test/next = make_posting(run_loc_floor_top_right)
	var/mob/living/basic/bounty_criminal/next_fugitive = next.criminal()
	TEST_ASSERT(next.setup_outpost_blend(), "The second posting could not be set up to blend in")
	var/mob/living/carbon/human/brawler = make_hunter()
	brawler.combat_mode = TRUE
	next_fugitive.attack_hand(brawler, list())
	TEST_ASSERT(!next_fugitive.blended, "Punching the fugitive did not expose it")
	TEST_ASSERT(WEAKREF(brawler) in next_fugitive.grudge, "The fugitive holds no grudge against whoever hit it")
	TEST_ASSERT_EQUAL(next.alert, 0, "Hitting the fugitive raised the alert")
	TEST_ASSERT_NULL(outpost.aggressor_strikes[brawler.mind], "Hitting the fugitive was an outpost strike")

/// While blending in nobody can pull them and the turrets leave them alone; the fugitive's shots at the outpost reach only its grudge list
/datum/unit_test/voidcrew_bounty_outpost/security

/datum/unit_test/voidcrew_bounty_outpost/security/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT(length(decoys), "No decoys to test with")
	var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[1]
	var/mob/living/carbon/human/hunter = make_hunter()

	TEST_ASSERT(!decoy.can_be_pulled(hunter, MOVE_FORCE_OVERPOWERING), "A decoy can be pulled")
	TEST_ASSERT(!fugitive.can_be_pulled(hunter, MOVE_FORCE_OVERPOWERING), "The fugitive can be pulled while blending in")
	TEST_ASSERT(!decoy.may_attack(hunter), "A decoy may attack someone")

	var/obj/machinery/porta_turret/outpost/turret = allocate(/obj/machinery/porta_turret/outpost)
	turret.outpost = outpost
	TEST_ASSERT(!turret.valid_target(decoy), "The outpost turrets target a decoy")
	TEST_ASSERT(!turret.valid_target(fugitive), "The outpost turrets target a fugitive blending in")

	// The fugitive's own shots pass through anyone who hasn't crossed it
	var/mob/living/carbon/human/bystander = make_hunter()
	var/obj/projectile/bullet/shot = allocate(/obj/projectile/bullet)
	SEND_SIGNAL(fugitive, COMSIG_PROJECTILE_FIRER_BEFORE_FIRE, shot, fugitive, hunter)
	TEST_ASSERT(SEND_SIGNAL(shot, COMSIG_PROJECTILE_SELF_PREHIT, bystander) & PROJECTILE_INTERRUPT_HIT_PHASE, "The fugitive's shot hit a bystander")
	fugitive.grudge |= WEAKREF(hunter)
	TEST_ASSERT(!(SEND_SIGNAL(shot, COMSIG_PROJECTILE_SELF_PREHIT, hunter) & PROJECTILE_INTERRUPT_HIT_PHASE), "The fugitive's shot passed through someone on its grudge list")

/// Traders give a different clue each, once per ship, and only to a ship hunting the fugitive there
/datum/unit_test/voidcrew_bounty_outpost/clues

/datum/unit_test/voidcrew_bounty_outpost/clues/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting(run_loc_floor_bottom_left)
	// A haircut since the mugshot, so the hair clue is in the pool whatever P1 makes
	var/datum/bounty_look/now = new
	now.hairstyle = "Mohawk"
	now.hair_color = "#101010"
	var/datum/bounty_look/then = new
	then.hairstyle = "Bob Hair"
	then.hair_color = "#e0c060"
	posting.record.look = now
	posting.record.old_look = then
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT_EQUAL(length(decoys), 3, "The fugitive did not get three decoys")
	// One person to a corner, so where each stands picks them out
	var/list/corners = list(
		run_loc_floor_top_right,
		locate(run_loc_floor_bottom_left.x, run_loc_floor_top_right.y, run_loc_floor_bottom_left.z),
		locate(run_loc_floor_top_right.x, run_loc_floor_bottom_left.y, run_loc_floor_bottom_left.z),
	)
	for(var/index in 1 to 3)
		var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[index]
		decoy.forceMove(corners[index])

	var/list/traders = list()
	for(var/index in 1 to 3)
		var/mob/living/basic/outpost_trader/trader = allocate(/mob/living/basic/outpost_trader)
		trader.outpost = outpost
		traders += trader

	var/obj/structure/overmap/ship/ship = allocate(/obj/structure/overmap/ship)
	var/mob/living/carbon/human/hunter = make_hunter(ship)
	TEST_ASSERT_NULL(bounty_outpost_ask_posting(traders[1], hunter), "A ship not hunting the fugitive can ask about it")
	posting.claimants += WEAKREF(ship)
	TEST_ASSERT_EQUAL(bounty_outpost_ask_posting(traders[1], hunter), posting, "A ship hunting the fugitive can't ask about it")
	TEST_ASSERT(bounty_outpost_ask(traders[1], hunter), "Asking a trader did nothing")

	var/list/answers = list()
	for(var/mob/living/basic/outpost_trader/trader as anything in traders)
		answers += posting.outpost_clue_for(trader, ship)
	TEST_ASSERT_EQUAL(length(unique_list(answers)), 3, "Traders repeated each other: [answers.Join(" / ")]")
	TEST_ASSERT(!("Can't help you there." in answers), "A trader had nothing to say with clues still untold") // BOUNTY_OUTPOST_NO_CLUE

	// Asking again gets the same answer, not a new clue
	var/again = posting.outpost_clue_for(traders[1], ship)
	TEST_ASSERT(findtext(again, "I told you what I know") && findtext(again, answers[1]), "Asking twice got a new clue: [again]")

	// Another ship asking the same trader hears the same kind of clue
	var/obj/structure/overmap/ship/rival = allocate(/obj/structure/overmap/ship)
	var/list/kind_before = posting.outpost_trader_clues[REF(traders[2])]
	posting.outpost_clue_for(traders[2], rival)
	TEST_ASSERT_EQUAL(posting.outpost_trader_clues[REF(traders[2])], kind_before, "A trader changed their story for another ship")

	// The hair clue says how it changed
	var/hair = bounty_outpost_hair_clue(posting.record)
	TEST_ASSERT(findtext(hair, "mohawk") || findtext(hair, "Mohawk"), "The hair clue does not name the new style: [hair]")
	TEST_ASSERT(findtext(hair, "black"), "The hair clue does not name the new colour: [hair]")

	hunter.mind.ship_teams = null

/// The wanted board lists the open public postings and nothing else, and is outpost property
/datum/unit_test/voidcrew_bounty_outpost/board

/datum/unit_test/voidcrew_bounty_outpost/board/Run()
	outpost = make_outpost()
	var/obj/structure/bounty_wanted_board/board = allocate(/obj/structure/bounty_wanted_board)
	TEST_ASSERT(HAS_TRAIT(board, "outpost_property"), "The wanted board is not outpost property") // TRAIT_OUTPOST_PROPERTY

	var/datum/criminal_bounty/outpost_test/public_posting = make_posting()
	var/datum/criminal_bounty/outpost_test/private_posting = make_posting()
	private_posting.private_to = WEAKREF(allocate(/obj/structure/overmap/ship))
	var/datum/criminal_bounty/outpost_test/closed_posting = make_posting()
	closed_posting.status = "closed" // BOUNTY_POSTING_CLOSED

	var/list/ids = list()
	for(var/list/entry as anything in board.outpost_board_entries())
		ids[entry["id"]] = entry
	var/list/listed = ids[public_posting.record.id]
	TEST_ASSERT_NOTNULL(listed, "The board does not list a public posting")
	TEST_ASSERT_EQUAL(listed["reward"], 1234, "The board shows the wrong reward")
	TEST_ASSERT_EQUAL(listed["tier"], "Petty", "The board shows the wrong tier")
	TEST_ASSERT(findtext(listed["place"], outpost.name), "The board does not say where they were seen: [listed["place"]]")
	TEST_ASSERT(!ids[private_posting.record.id], "The board lists a private offer")
	TEST_ASSERT(!ids[closed_posting.record.id], "The board lists a closed posting")

	var/mob/living/carbon/human/reader = make_hunter()
	var/list/static_data = board.ui_static_data(reader)
	TEST_ASSERT(islist(static_data["mugshots"]), "The board sends no mugshots")
	TEST_ASSERT_EQUAL(board.outpost_static_signature, bounty_public_board_signature(), "The board's static data is out of date as soon as it is built")

/// When the posting closes the decoys and an uncaught fugitive walk out and fade
/datum/unit_test/voidcrew_bounty_outpost/cleanup

/datum/unit_test/voidcrew_bounty_outpost/cleanup/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/leaving = decoys_of(posting) + fugitive
	TEST_ASSERT_EQUAL(length(leaving), 4, "Expected the fugitive and three decoys")

	posting.status = "closed" // BOUNTY_POSTING_CLOSED
	SEND_SIGNAL(posting, "bounty_posting_closed", "expired", null) // COMSIG_BOUNTY_POSTING_CLOSED, BOUNTY_CLOSE_EXPIRED
	TEST_ASSERT_EQUAL(length(posting.decoys), 0, "The closed posting kept its decoys")
	TEST_ASSERT_NULL(posting.criminal(), "The closed posting kept its fugitive")
	for(var/mob/living/walker as anything in leaving)
		TEST_ASSERT(walker.GetComponent(/datum/component/bounty_outpost_exit), "[walker] did not leave when the posting closed")
		TEST_ASSERT(HAS_TRAIT(walker, TRAIT_GODMODE), "[walker] can be hurt on the way out")

	// No lift in the test room, so they fade where they stand
	var/deadline = world.time + 5 SECONDS
	UNTIL(world.time > deadline || !length(leaving - get_all_qdeleted(leaving)))
	for(var/mob/living/walker as anything in leaving)
		TEST_ASSERT(QDELETED(walker), "[walker] was still there after the posting closed")

/// Everything in `things` that has been deleted
/datum/unit_test/voidcrew_bounty_outpost/cleanup/proc/get_all_qdeleted(list/things)
	. = list()
	for(var/datum/thing as anything in things)
		if(QDELETED(thing))
			. += thing

/// Each trader outpost map has one wanted board, on a wall of its concourse
/datum/unit_test/voidcrew_bounty_outpost_maps

/datum/unit_test/voidcrew_bounty_outpost_maps/Run()
	for(var/outpost_type in list(
		/obj/structure/overmap/trader_outpost/general,
		/obj/structure/overmap/trader_outpost/outfitter,
		/obj/structure/overmap/trader_outpost/black_market,
	))
		var/obj/structure/overmap/trader_outpost/outpost = allocate(outpost_type)
		TEST_ASSERT(outpost.load_level(), "[outpost_type]'s interior failed to load")
		var/turf/bottom_left = outpost.template_bottom_left
		var/turf/top_right = locate(bottom_left.x + outpost.outpost_template.width - 1, bottom_left.y + outpost.outpost_template.height - 1, bottom_left.z)
		var/list/boards = list()
		for(var/turf/interior as anything in block(bottom_left, top_right))
			for(var/obj/structure/bounty_wanted_board/found in interior)
				boards += found
		TEST_ASSERT_EQUAL(length(boards), 1, "[outpost_type] has [length(boards)] wanted boards, not one")
		var/obj/structure/bounty_wanted_board/board = boards[1]
		TEST_ASSERT(isopenturf(board.loc), "[outpost_type]'s wanted board is not on a floor")
		TEST_ASSERT(isclosedturf(get_step(board, board.dir)), "[outpost_type]'s wanted board is not hung on a wall")
		TEST_ASSERT(HAS_TRAIT(board, "outpost_property"), "[outpost_type]'s wanted board is not outpost property") // TRAIT_OUTPOST_PROPERTY
		qdel(outpost)
