/**
 * Bounty hunting: P1 identity's tests, for voidcrew/modules/bounties/bounty_identity.dm and bounty_looks.dm.
 *
 * Owner: P1 identity. Do not edit this file outside that package. Fork defines are included after the
 * tests, so a test uses the literal value with a comment naming the define.
 */

/// Every tier, archetype and placement gets a record with every field set
/datum/unit_test/voidcrew_bounty_identity_records

/datum/unit_test/voidcrew_bounty_identity_records/Run()
	var/list/styles = list("brawler", "knife", "pistol", "shotgun", "club", "bottle") // BOUNTY_STYLE_*, normal
	var/list/kits = list("juggernaut", "pyromaniac", "demolitionist", "ghost", "heavy") // BOUNTY_KIT_*
	var/list/labels = bounty_feature_labels()
	// BOUNTY_TIER_*, BOUNTY_ARCHETYPE_*, BOUNTY_PLACEMENT_*
	for(var/tier in list(1, 2, 3))
		for(var/archetype in list("meek", "normal", "boss"))
			for(var/placement in list("planet", "ruin", "npc_ship", "trader_outpost"))
				var/datum/bounty_record/record = generate_bounty_record(tier, archetype, placement)
				var/label = "tier [tier] [archetype] at [placement]"
				TEST_ASSERT(record.id, "[label]: no id")
				TEST_ASSERT(istext(record.name) && length(record.name), "[label]: no name")
				TEST_ASSERT(istext(record.alias) && length(record.alias), "[label]: no alias")
				TEST_ASSERT(record.gender == MALE || record.gender == FEMALE, "[label]: gender is [record.gender]")
				TEST_ASSERT(ispath(record.species, /datum/species), "[label]: species is [record.species]")
				TEST_ASSERT(istext(record.crime) && length(record.crime), "[label]: no crime")
				TEST_ASSERT_EQUAL(record.tier, tier, "[label]: wrong tier")
				TEST_ASSERT_EQUAL(record.status, "wanted", "[label]: not wanted") // BOUNTY_RECORD_WANTED
				TEST_ASSERT(islist(record.prison_traits), "[label]: no prison traits list")
				// No mini-bosses at trader outposts (D-A8).
				var/expected = (archetype == "boss" && placement == "trader_outpost") ? "normal" : archetype
				TEST_ASSERT_EQUAL(record.archetype, expected, "[label]: wrong archetype")
				switch(record.archetype)
					if("meek")
						TEST_ASSERT_EQUAL(record.style, "holdout", "[label]: a meek criminal without the holdout") // BOUNTY_STYLE_HOLDOUT
						TEST_ASSERT_NULL(record.kit, "[label]: a meek criminal with a kit")
					if("normal")
						TEST_ASSERT(record.style in styles, "[label]: style [record.style]")
						TEST_ASSERT_NULL(record.kit, "[label]: a normal criminal with a kit")
					if("boss")
						TEST_ASSERT(record.kit in kits, "[label]: kit [record.kit]")
						TEST_ASSERT_NULL(record.style, "[label]: a mini-boss with a style")
				var/datum/bounty_look/look = record.look
				TEST_ASSERT(look, "[label]: no look")
				TEST_ASSERT_EQUAL(look.species, record.species, "[label]: the look is another species")
				TEST_ASSERT_EQUAL(look.physique, record.gender, "[label]: the look's body is the other sex")
				TEST_ASSERT(istext(look.hairstyle) && istext(look.eye_color), "[label]: no hair or eyes")
				TEST_ASSERT(length(look.features), "[label]: no species features")
				// BOUNTY_FEATURES_MIN, BOUNTY_FEATURES_MAX
				TEST_ASSERT(length(record.features) >= 2 && length(record.features) <= 3, "[label]: [length(record.features)] features")
				for(var/kind in record.features)
					TEST_ASSERT(labels[kind], "[label]: unknown feature [kind]")
					TEST_ASSERT(istext(record.features[kind]), "[label]: feature [kind] has no text")
				// A trader-outpost fugitive's mugshot shows an old look (AR-C1).
				if(placement == "trader_outpost")
					TEST_ASSERT(record.old_look, "[label]: no old look for the mugshot")
				else
					TEST_ASSERT_NULL(record.old_look, "[label]: an old look away from a trader outpost")

	// Every species in the pool: its own name, a skin tone only if it uses one, features it can have.
	for(var/species in GLOB.bounty_species_weights)
		for(var/attempt in 1 to 5)
			var/datum/bounty_record/record = generate_bounty_record(1, "normal", "planet", species)
			TEST_ASSERT_EQUAL(record.species, species, "A forced species was not kept")
			if(bounty_species_uses_skin_tones(species))
				TEST_ASSERT(record.look.skin_tone in GLOB.skin_tones, "[species] has skin tone [record.look.skin_tone]")
			else
				TEST_ASSERT_NULL(record.look.skin_tone, "[species] has a skin tone")
			for(var/kind in record.features)
				TEST_ASSERT(bounty_feature_allowed(kind, species), "[species] got a [kind] feature")
		TEST_ASSERT(bounty_species_name(species) != "Unknown", "[species] has no plain name")

	// Rolled archetypes follow the tier.
	for(var/attempt in 1 to 10)
		var/datum/bounty_record/most_wanted = generate_bounty_record(3, null, "planet")
		TEST_ASSERT_EQUAL(most_wanted.archetype, "boss", "A Most Wanted rolled no mini-boss")
		var/datum/bounty_record/petty = generate_bounty_record(1)
		TEST_ASSERT(petty.archetype in list("meek", "normal"), "A Petty criminal rolled a mini-boss")

	// The dialogue file has enough crimes and aliases.
	var/list/crimes = bounty_identity_strings("crimes")
	for(var/tier_key in list("petty", "wanted", "most_wanted"))
		TEST_ASSERT(length(crimes[tier_key]) >= 15, "Only [length(crimes[tier_key])] [tier_key] crimes")
	var/list/aliases = bounty_identity_strings("aliases")
	TEST_ASSERT(length(aliases["any"]) >= 20, "Too few aliases")

	// A bare record (like the seams test makes) gets a look the first time one is needed, and keeps it.
	var/datum/bounty_record/bare = new
	bare.gender = FEMALE
	var/datum/bounty_look/bare_look = bounty_ensure_look(bare)
	TEST_ASSERT(bare_look, "A bare record got no look")
	TEST_ASSERT_EQUAL(bare.species, /datum/species/human, "A bare record isn't human")
	TEST_ASSERT_EQUAL(bare_look.physique, FEMALE, "A bare record's look is the other sex")
	TEST_ASSERT_EQUAL(bounty_ensure_look(bare), bare_look, "A bare record's look changed")

/// The same record looks like the same person in any outfit, and each record and outfit is built once
/datum/unit_test/voidcrew_bounty_identity_same_face

/datum/unit_test/voidcrew_bounty_identity_same_face/Run()
	for(var/species in list(/datum/species/human, /datum/species/lizard, /datum/species/moth, /datum/species/human/felinid))
		var/datum/bounty_record/record = generate_bounty_record(2, "normal", "planet", species)
		var/datum/bounty_look/look = record.look
		var/mob/living/carbon/human/dummy/first = bounty_look_dummy(look, /datum/outfit/bounty_mugshot, record.features)
		var/mob/living/carbon/human/dummy/second = bounty_look_dummy(look, /datum/outfit/outpost_prisoner, record.features)
		for(var/mob/living/carbon/human/dummy/dummy as anything in list(first, second))
			TEST_ASSERT_EQUAL(dummy.dna.species.type, species, "A [species] look was built as [dummy.dna.species.type]")
			TEST_ASSERT_EQUAL(dummy.hairstyle, look.hairstyle, "[species]: hairstyle changed with the outfit")
			TEST_ASSERT_EQUAL(dummy.hair_color, look.hair_color, "[species]: hair colour changed with the outfit")
			TEST_ASSERT_EQUAL(dummy.facial_hairstyle, look.facial_hairstyle, "[species]: facial hair changed with the outfit")
			TEST_ASSERT_EQUAL(dummy.physique, look.physique, "[species]: body changed with the outfit")
			if(look.skin_tone)
				TEST_ASSERT_EQUAL(dummy.skin_tone, look.skin_tone, "[species]: skin tone changed with the outfit")
			for(var/feature in look.features)
				TEST_ASSERT_EQUAL(dummy.dna.features[feature], look.features[feature], "[species]: feature [feature] changed with the outfit")
		TEST_ASSERT_EQUAL(first.eye_color_left, second.eye_color_left, "[species]: eye colour changed with the outfit")
		qdel(first)
		qdel(second)

	// apply_bounty_look dresses a mob and caches one look per record and outfit.
	var/datum/bounty_record/record = generate_bounty_record(1, "meek", "planet")
	var/mob/living/basic/mouse/one = allocate(/mob/living/basic/mouse)
	var/mob/living/basic/mouse/two = allocate(/mob/living/basic/mouse)
	apply_bounty_look(one, record, /datum/outfit/bounty_mugshot)
	apply_bounty_look(two, record, /datum/outfit/bounty_mugshot/bomber)
	var/first_key = "[record.id]|[/datum/outfit/bounty_mugshot]"
	var/second_key = "[record.id]|[/datum/outfit/bounty_mugshot/bomber]"
	var/cached = GLOB.bounty_looks[first_key]
	TEST_ASSERT(cached, "The first outfit's look wasn't cached")
	TEST_ASSERT(GLOB.bounty_looks[second_key], "The second outfit's look wasn't cached")
	TEST_ASSERT_EQUAL(one.icon, 'icons/mob/human/human.dmi', "The dressed mob isn't drawn as a person")
	TEST_ASSERT(length(one.overlays), "The dressed mob has no overlays")
	var/mob/living/basic/mouse/three = allocate(/mob/living/basic/mouse)
	apply_bounty_look(three, record, /datum/outfit/bounty_mugshot)
	TEST_ASSERT(GLOB.bounty_looks[first_key] == cached, "The same record and outfit were built twice")
	bounty_forget_looks(record)
	TEST_ASSERT_NULL(GLOB.bounty_looks[first_key], "A forgotten record's look is still cached")
	TEST_ASSERT_NULL(GLOB.bounty_looks[second_key], "A forgotten record's look is still cached")

/// A decoy shares exactly the features asked for, never all of them, and differs in the rest
/datum/unit_test/voidcrew_bounty_identity_decoys

/datum/unit_test/voidcrew_bounty_identity_decoys/Run()
	for(var/attempt in 1 to 20)
		var/datum/bounty_record/wanted = generate_bounty_record(pick(1, 2), null, "trader_outpost")
		var/count = length(wanted.features)
		for(var/shared in 0 to count)
			var/datum/bounty_record/decoy = make_decoy_record(wanted, shared)
			var/expected = min(shared, count - 1)
			var/in_common = 0
			for(var/kind in decoy.features)
				if(decoy.features[kind] == wanted.features[kind])
					in_common++
			TEST_ASSERT_EQUAL(in_common, expected, "A decoy asked to share [shared] of [count] features shares [in_common]")
			TEST_ASSERT_EQUAL(length(decoy.features), count, "A decoy has [length(decoy.features)] features, the fugitive [count]")
			TEST_ASSERT_EQUAL(decoy.species, wanted.species, "A decoy is another species")
			TEST_ASSERT_EQUAL(decoy.gender, wanted.gender, "A decoy is the other sex")
			TEST_ASSERT_EQUAL(decoy.archetype, wanted.archetype, "A decoy talks like another archetype")
			TEST_ASSERT(decoy.id != wanted.id, "A decoy shares the fugitive's record id")
			// Rolled against the current look: the same face but for the hair.
			TEST_ASSERT_EQUAL(decoy.look.skin_tone, wanted.look.skin_tone, "A decoy's skin differs from the fugitive's")
			TEST_ASSERT_EQUAL(decoy.look.eye_color, wanted.look.eye_color, "A decoy's eyes differ from the fugitive's")
			for(var/feature in wanted.look.features)
				TEST_ASSERT_EQUAL(decoy.look.features[feature], wanted.look.features[feature], "A decoy's [feature] differs from the fugitive's")
			var/hair_shared = wanted.features["hair"] && decoy.features["hair"] == wanted.features["hair"] // BOUNTY_FEATURE_HAIR
			if(bounty_species_has_hair(wanted.species) && !hair_shared)
				TEST_ASSERT(bounty_hair_key(decoy.look) != bounty_hair_key(wanted.look), "A decoy's hair reads like the fugitive's without sharing it")
				if(wanted.old_look)
					TEST_ASSERT(bounty_hair_key(decoy.look) != bounty_hair_key(wanted.old_look), "A decoy's hair reads like the fugitive's mugshot")

/// A mugshot is built once per record; an old look differs in hair and clears it
/datum/unit_test/voidcrew_bounty_identity_mugshot

/datum/unit_test/voidcrew_bounty_identity_mugshot/Run()
	var/datum/bounty_record/record = generate_bounty_record(1, "meek", "planet", /datum/species/human)
	var/builds = GLOB.bounty_mugshot_builds
	var/first = bounty_record_mugshot(record)
	TEST_ASSERT(istext(first) && length(first) > 100, "No mugshot was built")
	TEST_ASSERT_EQUAL(GLOB.bounty_mugshot_builds, builds + 1, "Building one mugshot took [GLOB.bounty_mugshot_builds - builds] builds")
	TEST_ASSERT_EQUAL(bounty_record_mugshot(record), first, "The second call returned another mugshot")
	TEST_ASSERT_EQUAL(bounty_mugshot_asset(record), first, "The UI gets something other than the cached mugshot")
	TEST_ASSERT_EQUAL(GLOB.bounty_mugshot_builds, builds + 1, "The mugshot was built again")

	// The UI never builds in its own call: it gets "" and the build is queued.
	var/datum/bounty_record/unbuilt = generate_bounty_record(1, "meek", "planet")
	TEST_ASSERT_EQUAL(bounty_mugshot_asset(unbuilt), "", "The UI call built a mugshot itself")
	TEST_ASSERT(unbuilt.identity_mugshot_queued, "The UI call didn't queue the build")

	// An old look (AR-C1) keeps the face and changes the hair, and the next mugshot shows it.
	var/datum/bounty_look/current = record.look
	var/datum/bounty_look/old = make_old_look(record)
	TEST_ASSERT(old && record.old_look == old, "No old look was made")
	TEST_ASSERT(bounty_hair_key(old) != bounty_hair_key(current), "The old look's hair reads like the current one")
	TEST_ASSERT_EQUAL(old.species, current.species, "The old look is another species")
	TEST_ASSERT_EQUAL(old.skin_tone, current.skin_tone, "The old look has other skin")
	TEST_ASSERT_EQUAL(old.eye_color, current.eye_color, "The old look has other eyes")
	TEST_ASSERT_NULL(record.mugshot, "The mugshot built before the old look was kept")
	TEST_ASSERT_EQUAL(make_old_look(record), old, "A second call made another old look")

	// Every species in the pool renders someone in the frame.
	for(var/species in GLOB.bounty_species_weights)
		var/datum/bounty_record/sitter = generate_bounty_record(1, "normal", "planet", species)
		var/icon/portrait = bounty_mugshot_icon(sitter.look, sitter.features)
		TEST_ASSERT_EQUAL(portrait.Width(), 64, "A [species] mugshot is [portrait.Width()] wide") // (BOUNTY_MUGSHOT_X2 - X1 + 1) * BOUNTY_MUGSHOT_SCALE
		TEST_ASSERT_EQUAL(portrait.Height(), 64, "A [species] mugshot is [portrait.Height()] high")
		var/person = 0
		for(var/x in 1 to 16)
			for(var/y in 1 to 16)
				var/pixel = portrait.GetPixel(x * 4 - 1, y * 4 - 1)
				// BOUNTY_MUGSHOT_BACKDROP, BOUNTY_MUGSHOT_LINES
				if(pixel && lowertext(copytext(pixel, 1, 8)) != "#b9c0c7" && lowertext(copytext(pixel, 1, 8)) != "#949da6")
					person++
		TEST_ASSERT(person >= 40, "A [species] mugshot shows almost nobody ([person] of 256 samples)")

/// Examine lines have one layout, so a fugitive and its decoys read alike
/datum/unit_test/voidcrew_bounty_identity_feature_lines

/datum/unit_test/voidcrew_bounty_identity_feature_lines/Run()
	var/list/order = list("Hair", "Scar", "Tattoo", "Ears", "Eyewear", "Clothing", "Walk")
	var/regex/layout = regex(@"^(Hair|Scar|Tattoo|Ears|Eyewear|Clothing|Walk): [a-z][^<>]*\.$")
	for(var/attempt in 1 to 20)
		var/datum/bounty_record/wanted = generate_bounty_record(pick(1, 2), null, "trader_outpost")
		var/datum/bounty_record/decoy = make_decoy_record(wanted, 1)
		var/list/wanted_lines = wanted.feature_lines()
		var/list/decoy_lines = decoy.feature_lines()
		TEST_ASSERT_EQUAL(length(wanted_lines), length(wanted.features), "Not one line per feature")
		TEST_ASSERT_EQUAL(length(decoy_lines), length(wanted_lines), "A decoy reads [length(decoy_lines)] lines, the fugitive [length(wanted_lines)]")
		for(var/list/lines as anything in list(wanted_lines, decoy_lines))
			var/last_place = 0
			for(var/line in lines)
				TEST_ASSERT(layout.Find(line), "The line \"[line]\" breaks the layout")
				var/place = order.Find(copytext(line, 1, findtext(line, ":")))
				TEST_ASSERT(place > last_place, "The line \"[line]\" is out of order")
				last_place = place
	var/datum/bounty_record/plain = new
	TEST_ASSERT_EQUAL(length(plain.feature_lines()), 0, "A record without features has examine lines")

/// bounty_say(): every context has lines, and the cooldown and no-repeat window hold
/datum/unit_test/voidcrew_bounty_identity_say

/datum/unit_test/voidcrew_bounty_identity_say/Run()
	var/list/lines = bounty_identity_strings("lines")
	var/list/contexts = list(
		"idle_chat", "bar", "trade_haggle", "explore", "loot", "camp",
		"noticed", "flee", "winded", "hide", "found", "cornered", "draw_gun",
		"fight_start", "hurt", "surrender", "downed", "recover",
		"cuffed", "slipping_cuffs", "beamed_out",
		"accused_wrongly", "accused_rightly", "companion_reply",
	)
	for(var/kit in list("juggernaut", "pyromaniac", "demolitionist", "ghost", "heavy")) // BOUNTY_KIT_*
		contexts += list("[kit]_intro", "[kit]_ability", "[kit]_exhausted")
	for(var/context in contexts)
		var/list/by_voice = lines[context]
		TEST_ASSERT(length(by_voice?["any"]) >= 6, "The context [context] has fewer than 6 lines")
	for(var/voice in list("meek", "normal", "boss")) // BOUNTY_ARCHETYPE_*
		TEST_ASSERT(length(lines["idle_chat"][voice]) >= 3, "Too few [voice] small-talk lines")
		TEST_ASSERT(length(lines["bar"][voice]) >= 3, "Too few [voice] bar lines")

	var/mob/living/basic/mouse/speaker = allocate(/mob/living/basic/mouse)
	TEST_ASSERT(speaker.bounty_say("flee"), "The first line wasn't said")
	TEST_ASSERT(!speaker.bounty_say("flee"), "A second line was said inside the cooldown")
	TEST_ASSERT(speaker.bounty_say("flee", force = TRUE), "A forced line was held back by the cooldown")
	var/datum/component/bounty_identity_voice/voice = speaker.GetComponent(/datum/component/bounty_identity_voice)
	TEST_ASSERT(voice, "Speaking left no memory of it")
	TEST_ASSERT(!speaker.bounty_say("no_such_context", force = TRUE), "A line was said for a context the file doesn't have")

	// "flee" has 6 lines: all of them come up before any repeats.
	var/mob/living/basic/mouse/runner = allocate(/mob/living/basic/mouse)
	var/datum/component/bounty_identity_voice/runner_voice = runner.LoadComponent(/datum/component/bounty_identity_voice)
	var/list/said = list()
	for(var/attempt in 1 to 6)
		runner_voice.line_cooldown = 0
		TEST_ASSERT(runner.bounty_say("flee"), "Line [attempt] of 6 wasn't said")
		said |= runner_voice.last_line
	TEST_ASSERT_EQUAL(length(said), 6, "A line repeated inside the no-repeat window")
	runner_voice.line_cooldown = 0
	TEST_ASSERT(!runner.bounty_say("flee"), "An unforced line repeated inside the no-repeat window")
	TEST_ASSERT(runner.bounty_say("flee", force = TRUE), "A forced line wasn't said once every line was used")
	// Once the window has passed, lines come back.
	for(var/line in runner_voice.recent_lines)
		runner_voice.recent_lines[line] -= 600 // BOUNTY_SAY_NO_REPEAT
	runner_voice.line_cooldown = 0
	TEST_ASSERT(runner.bounty_say("flee"), "Lines didn't come back after the no-repeat window")

	// A line naming a placeholder is said only with a value for it.
	for(var/attempt in 1 to 12)
		runner_voice.line_cooldown = 0
		runner.bounty_say("cuffed", force = TRUE)
		TEST_ASSERT(!findtext(runner_voice.last_line, "{"), "A line was said with an empty placeholder: [runner_voice.last_line]")
	runner_voice.recent_lines.Cut()
	var/filled = FALSE
	for(var/attempt in 1 to 80)
		runner_voice.line_cooldown = 0
		runner_voice.recent_lines.Cut()
		runner.bounty_say("cuffed", list("{crime}" = "stealing a mop"))
		if(findtext(runner_voice.last_line, "stealing a mop"))
			filled = TRUE
			break
	TEST_ASSERT(filled, "A placeholder value never reached a line")

	// Criminals speak in their archetype's voice, except blended in, where they sound like their decoys.
	var/mob/living/basic/bounty_criminal/criminal = allocate(/mob/living/basic/bounty_criminal/meek)
	criminal.record = generate_bounty_record(1, "meek", "trader_outpost")
	TEST_ASSERT_EQUAL(criminal.identity_voice(), "meek", "A meek criminal doesn't talk like one")
	criminal.blended = TRUE
	TEST_ASSERT_NULL(criminal.identity_voice(), "A blended fugitive talks differently from its decoys")
	TEST_ASSERT_EQUAL(criminal.identity_line_values()?["{crime}"], criminal.record.crime, "A criminal doesn't know its own crime")
